"""One clutter rule, three consumers.

``provenance.hashing``, ``data.folderscan`` and ``scripts/declare_inputs.py``
all walk directories, and they must agree exactly. A file that one counts and
another skips produces a rollup that depends on which tool last looked at the
directory — and guard 3 would then abort a legitimate run for a reason having
nothing to do with the cohort.

Two measured facts make this concrete rather than hypothetical:

* every image carries a 4,096-byte AppleDouble sidecar ``._<name>.jpg``, which
  has an image extension and the real id in its stem
* Windows regenerates ``Thumbs.db`` whenever a directory is browsed
"""

from __future__ import annotations

import pytest

from cleft import clutter
from cleft.data import folderscan
from cleft.provenance import hash_dir

CLUTTER_SAMPLES = [
    "._1001.jpg",
    "._Thumbs.db",
    "._",
    "Thumbs.db",
    ".DS_Store",
    "desktop.ini",
]

DATA_SAMPLES = ["1001.jpg", "523.JPG", "values.csv", "MANIFEST.json", "a._b.jpg"]


# --------------------------------------------------------------------------
# the rule itself
# --------------------------------------------------------------------------


@pytest.mark.parametrize("name", CLUTTER_SAMPLES)
def test_clutter_is_recognised(name):
    assert clutter.is_clutter(name)


@pytest.mark.parametrize("name", DATA_SAMPLES)
def test_data_is_not_mistaken_for_clutter(name):
    assert not clutter.is_clutter(name)


def test_the_rule_is_by_basename_not_extension():
    """The crux: ``._1001.jpg`` ends in .jpg and is not an image."""
    assert clutter.is_clutter("._1001.jpg")
    assert not clutter.is_clutter("1001.jpg")
    # And a legitimate name merely containing "._" is data.
    assert not clutter.is_clutter("scan._raw.jpg")


# --------------------------------------------------------------------------
# the consumers agree
# --------------------------------------------------------------------------


def test_hashing_and_folderscan_skip_exactly_the_same_files(tmp_path):
    root = tmp_path / "photos"
    (root / "1").mkdir(parents=True)
    for name in ["1001.jpg", "1002.jpg", *CLUTTER_SAMPLES]:
        (root / "1" / name).write_bytes(b"x" * 16)

    hashed = set(hash_dir(root)["files"])
    scanned = folderscan.scan(root)

    assert hashed == {"1/1001.jpg", "1/1002.jpg"}, "hashing admitted clutter"
    assert scanned.folders[1] == [1001, 1002], "the scanner admitted clutter"
    assert scanned.skipped_clutter == len(CLUTTER_SAMPLES)


def test_both_consumers_call_the_shared_rule():
    """Not a copy of the list — the same function object.

    A duplicated list drifts. This asserts the identity so a future edit that
    reintroduces a local copy fails here rather than on the cluster.
    """
    from cleft.provenance import hashing

    assert hashing.clutter is clutter
    assert folderscan.clutter is clutter

    # And neither module defines its own collection of clutter names. Prose may
    # mention Thumbs.db -- explaining why the rule exists is the point -- but a
    # second list is what drifts.
    for module in (hashing, folderscan):
        for name, value in vars(module).items():
            if name.startswith("__") or not isinstance(value, (set, frozenset, list, tuple)):
                continue
            members = {str(v) for v in value}
            assert not (members & clutter.CLUTTER_NAMES), (
                f"{module.__name__}.{name} duplicates the clutter list; it must "
                "use cleft.clutter so the three consumers cannot drift apart"
            )


def test_declare_inputs_inherits_the_rule():
    """It hashes via hash_path, so it cannot have a different opinion."""
    source = (
        __import__("pathlib").Path(__file__).resolve().parents[1]
        / "scripts"
        / "declare_inputs.py"
    ).read_text(encoding="utf-8")
    assert "hash_path" in source
    assert "Thumbs.db" not in source


# --------------------------------------------------------------------------
# why it matters
# --------------------------------------------------------------------------


def test_a_regenerated_thumbs_db_does_not_change_the_rollup(tmp_path):
    """Windows rewrites Thumbs.db on browse. Guard 3 must not fire for that."""
    root = tmp_path / "photos"
    (root / "1").mkdir(parents=True)
    (root / "1" / "1001.jpg").write_bytes(b"image")

    before = hash_dir(root)["rollup"]
    (root / "1" / "Thumbs.db").write_bytes(b"freshly regenerated by explorer")
    after = hash_dir(root)["rollup"]

    assert before == after, (
        "browsing the directory on Windows changed the rollup; guard 3 would "
        "abort a run for a reason unrelated to the data"
    )


def test_sidecars_do_not_change_the_rollup(tmp_path):
    root = tmp_path / "photos"
    (root / "1").mkdir(parents=True)
    (root / "1" / "1001.jpg").write_bytes(b"image")

    before = hash_dir(root)["rollup"]
    (root / "1" / "._1001.jpg").write_bytes(b"\x00" * 4096)
    assert hash_dir(root)["rollup"] == before


def test_real_data_still_changes_the_rollup(tmp_path):
    """The exclusions must not become a hole in the guard."""
    root = tmp_path / "photos"
    (root / "1").mkdir(parents=True)
    (root / "1" / "1001.jpg").write_bytes(b"image")

    before = hash_dir(root)["rollup"]
    (root / "1" / "1001.jpg").write_bytes(b"imagE")
    assert hash_dir(root)["rollup"] != before


def test_the_rule_is_recorded_alongside_the_hash(tmp_path):
    """Auditable: a rollup states what it excluded."""
    root = tmp_path / "photos"
    (root / "1").mkdir(parents=True)
    (root / "1" / "1001.jpg").write_bytes(b"image")

    excluded = hash_dir(root)["excluded"]
    assert "._" in excluded["prefixes"]
    assert "Thumbs.db" in excluded["names"]
