"""Generate Phase 22's six ranking-arm configs.

Six arms = three pair sources x two heads (``phase22.HEAD_BOUNDING_RULED``).
Every setting is RULED and is written here rather than typed six times, so
the arms cannot drift apart in anything but the two factors that define
them.

**Two settings are still OPEN** -- R-syn's pretrain epochs and its
fine-tune trainability -- so the two R-syn configs carry the UNRULED
sentinel ``-1``. ``run.task_train_rank_cv`` refuses it by name.
``EXIT_CRITERIA`` criterion 13 is the reason: the phase may not start
with a setting silently defaulted.

Usage::

    python scripts/generate_phase22_configs.py            # write
    python scripts/generate_phase22_configs.py --check    # re-derive, diff
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
CONFIGS = REPO / "configs"

#: Carried VERBATIM from the shipped probe config -- no new hash enters.
DONOR = "p7_d1_vit_b16_imagenet_g1.yaml"

#: The UNRULED sentinel. Not a default: a value the task refuses.
UNRULED = -1

SOURCES = {
    "r_syn": (
        "synth_within_face",
        "the SYNTHETIC TPS ordering, exact by construction -- four "
        "magnitudes per face. WITHIN-FACE pairs, so PAIRING_AXIS_ASSUMPTION "
        "travels with every result this arm produces.",
    ),
    "r_all": (
        "cohort_all",
        "ALL cohort pairs ordered by panel mean, INCLUDING the 4,604 that "
        "carry a real but uncertain order below SE_diff. The 2,345 exact "
        "ties are dropped (TIE_RULE_RULED) -- an absent order is not an "
        "uncertain one.",
    ),
    "r_clear": (
        "cohort_se_diff",
        "cohort pairs CLEARING SE_diff = 0.398942, declared in advance and "
        "never a post-hoc filter. Ties are step 0 and were already outside "
        "this set, so the tie rule costs this arm nothing.",
    ),
}

HEADS = {
    "bounded": (True, "inner_val_mse",
                "scores on the 1-5 label scale, so MSE monitoring means "
                "what it means for every other arm"),
    "unbounded": (False, "inner_val_pcc",
                  "ORDER ONLY. DECLARED LIMITATION: this arm selects on "
                  "its claimed metric (MONITOR_BIND_RESOLVED). Its CSVs "
                  "carry RAW SCORES, never label-scale values."),
}


def _donor() -> dict:
    import yaml

    return yaml.safe_load((CONFIGS / DONOR).read_text(encoding="utf-8"))


def config_for(source: str, head: str) -> tuple[str, str]:
    """The config text for one arm, and its filename."""
    import yaml

    donor = _donor()
    pair_source, source_note = SOURCES[source]
    bounded, monitor, head_note = HEADS[head]
    arm = f"{source}_{head}"

    # **The input REFERENCES are carried from the donor too, not typed.**
    # [FIXED 2026-09-01] The first version carried `inputs` verbatim and
    # then hand-wrote the task's references to them -- `staged_g1` and
    # `pooled_vit_b16_imagenet_g1`, neither of which is a declared input
    # name anywhere. Both halves were self-consistent and disagreed at
    # the join. Reading the names off the donor's own task block makes
    # that disagreement impossible rather than unlikely.
    task = {
        "kind": "train_rank_cv",
        "arm": arm,
        "pair_source": pair_source,
        "bounded": bounded,
        "monitor": monitor,
        "manifest_artifact": donor["task"]["manifest_artifact"],
        "staged_artifact": donor["task"]["staged_artifact"],
        "embeddings_artifact": donor["task"]["embeddings_artifact"],
        "backbone": "vit_b16",
        "geometry": "g1",
        "label": "mean",
        "seeds": [1337, 2024, 7, 99, 12345],
        "init": "imagenet",
        "max_epochs": 40,
        "patience": 5,
        "inner_val_frac": 0.2,
        "expect_patients": 237,
    }
    if source == "r_clear":
        task["se_diff_threshold"] = 0.398942
    if source == "r_syn":
        # STILL OPEN -- settings 9 and 10. The task refuses these.
        task["pretrain_epochs"] = UNRULED
        task["finetune_trainable_code"] = UNRULED

    header = f"""\
# PHASE 22 RANKING ARM -- {arm}
#
# GENERATED by scripts/generate_phase22_configs.py. Do not
# hand-edit: --check re-derives and diffs.
#
# PAIR SOURCE: {source_note}
#
# HEAD: {head_note}
#
# THE RULED SETTINGS, none of them a config field because none
# of them may vary between arms:
#   loss             pairwise logistic, HARD targets (LOSS_RULED,
#                    TARGET_MAP_RULED). No margin -- the logistic
#                    needs none.
#   tie rule         TIED PAIRS DROPPED (TIE_RULE_RULED). A tie
#                    carries no order, so under a hard-target
#                    loss training on it teaches nothing true.
#                    Measured at 2,345 of 27,966 pairs (0.0839).
#   pairs            ALL pairs each epoch, formed INSIDE
#                    train_epoch, so fold honesty is STRUCTURAL
#                    and not policed. Nothing sampled, so no
#                    sampler seed exists to declare.
#   head             the shipped factory.build(num_outputs=1)
#                    scalar head, on the train/ldl.py precedent:
#                    a non-MSE objective in its own train_epoch,
#                    FROZEN APPARATUS UNTOUCHED.
#
# Gate 3: reset() places the bias so the epoch-0 prediction is
# the training-fold mean, and predict() returns that bias while
# the weights are still unallocated -- mirroring
# EmbeddingHeadBackbone.predict. [CORRECTED 2026-09-01: this
# header previously read "weights at zero and the bias placed so
# the untrained head predicts the training-fold mean". The
# weights are None, not zero, and until this cycle the untrained
# head could not predict at all. phase22.GATE_3_CLAIM_CORRECTED.]
#
# Evaluation is per-patient OOF PCC as every other arm, so the
# CSVs land in the format Phase 21's diagnostic already reads.
#
# Every input is CARRIED VERBATIM from {DONOR}.
# NO NEW HASH ENTERS.
#
#   bash -lc "cd /home/user/codex/cleft-aesthetics && PYTHONPATH=src \\
#     python -m cleft.run --config configs/p22_{arm}.yaml"
"""
    if source == "r_syn":
        header += """#
# *** THIS ARM CANNOT LAUNCH YET. ***
# pretrain_epochs and finetune_trainable_code carry the UNRULED
# sentinel -1. They are settings 9 and 10 of
# phase22.DECLARED_SETTINGS_22 and are STILL OPEN; EXIT_CRITERIA
# criterion 13 gates the run on every setting being ruled.
# task_train_rank_cv REFUSES the sentinel by name rather than
# letting a plausible default stand in for a ruling nobody made.
"""

    body = {
        "schema_version": 1,
        "phase": "p22",
        "tier": "keeper",
        "seed": 1337,
        "inputs": donor["inputs"],
        "task": task,
    }
    # The generator refuses to EMIT an unresolvable reference, so the
    # break cannot reach a file even if someone edits the names above.
    declared = {entry["name"] for entry in body["inputs"]}
    for field, value in task.items():
        if field.endswith("_artifact") and value not in declared:
            raise SystemExit(
                f"{arm}: task.{field} = {value!r} names no declared input. "
                f"Declared: {sorted(declared)}. Carry the reference from the "
                "donor's task block rather than typing it."
            )
    text = header + "\n" + yaml.safe_dump(body, sort_keys=False)
    return f"p22_{arm}.yaml", text


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    drift = []
    for source in SOURCES:
        for head in HEADS:
            name, text = config_for(source, head)
            path = CONFIGS / name
            if args.check:
                current = path.read_text(encoding="utf-8") if path.is_file() else ""
                if current != text:
                    drift.append(name)
            else:
                path.write_text(text, encoding="utf-8")
                print(f"wrote {name}")
    if args.check:
        if drift:
            print("DRIFT: " + ", ".join(drift))
            return 1
        print(f"{len(SOURCES) * len(HEADS)} configs match the generator")
    return 0


if __name__ == "__main__":
    sys.exit(main())
