"""Configs for post-closing addenda -- checks registered against a
phase that is already closed, whose inputs are runs that already exist.

Separate from the phase generators on purpose. An addendum is not a
stop: it adds no claim to the phase it follows, and putting its config
in that phase's generator would make it look like one.

    python scripts/generate_addendum_configs.py           # write
    python scripts/generate_addendum_configs.py --check    # drift only
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"
PLACEHOLDER = "0" * 64

#: The arm these predictions came from -- the project's best cleft-side
#: cell. The seeds and the label are READ FROM ITS SHIPPED CONFIG rather
#: than retyped, so "the same five seeds" is a fact about the file.
ARM_CONFIG = "p7_d1_vit_b16_imagenet_g1.yaml"
ARM_NAME = "p7_d1_vit_b16_imagenet_g1"
NAME = "p7_d1_classification_metrics.yaml"

#: **PASTED 2026-08-24, the maintainer.** The run-directory contract is
#: ``<stem>__<sha8>__<job-id>``, and the stem is the ARM CONFIG's stem --
#: which is what ties this addendum's input to the arm it claims to
#: describe. The sha8 is the git commit's short sha
#: (provenance/context.py:420), not the config's.
ARM_RUN_DIR = "p7_d1_vit_b16_imagenet_g1__3f71a6a9__p7-d1-vit-imagenet"

#: phase9's banked class3 majority floor. The task refuses unless the
#: truth column reproduces it.
BANKED_MAJORITY = 0.502


def source_config(name: str) -> dict:
    return yaml.safe_load(
        (REPO / "configs" / name).read_text(encoding="utf-8")
    )


def _carried(input_name: str, path: str) -> dict:
    """The generator owns the PATH; the shipped config carries only the
    HASH, and only when the two paths agree -- the path-pinned carry
    (phase 15's ``_carried_named``, same reasoning)."""
    entry = {"name": input_name, "path": path, "rollup_sha256": PLACEHOLDER}
    shipped = REPO / "configs" / NAME
    if not shipped.is_file():
        return entry
    payload = yaml.safe_load(shipped.read_text(encoding="utf-8")) or {}
    for candidate in payload.get("inputs") or []:
        if candidate.get("name") != input_name:
            continue
        if str(candidate.get("path")) != path:
            continue
        rollup = str(candidate.get("rollup_sha256") or "")
        if len(rollup) == 64 and set(rollup) != {"0"}:
            entry["rollup_sha256"] = rollup
    return entry


def _provenance(inputs: list) -> str:
    pending = sum(1 for e in inputs if "/PENDING_" in e["path"])
    unresolved = sum(1 for e in inputs if set(e["rollup_sha256"]) == {"0"})
    if pending:
        return (
            f"# **{pending} PATH(S) PENDING and {unresolved} ALL-ZERO\n"
            "# PLACEHOLDER HASH(ES).** A run directory carries a SHA and\n"
            "# a job id, neither derivable on a laptop. Two passes:\n"
            "# paste the run directory, then declare_inputs.py. Guard 3\n"
            "# refuses until both are real -- the PLACEHOLDER working.\n"
        )
    if unresolved:
        return (
            f"# **{unresolved} ALL-ZERO PLACEHOLDER HASH(ES) REMAIN.**\n"
            "# Every path is real; declare_inputs.py fills the rest and\n"
            "# guard 3 refuses until it does.\n"
        )
    return (
        "# **RESOLVED.** Every input declared at a real path with a\n"
        "# verified hash.\n"
    )


def render() -> str:
    arm = source_config(ARM_CONFIG)
    arm_inputs = {e["name"]: e for e in arm["inputs"]}
    seeds = list(arm["task"]["seeds"])

    inputs = [
        _carried("arm_run", f"{CLUSTER_ROOT}/runs/keeper/p7/{ARM_RUN_DIR}"),
        dict(arm_inputs["manifest_v1"]),
    ]
    payload = {
        "schema_version": 1,
        "phase": "p7",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": {
            "kind": "classification_metrics",
            "arm": ARM_NAME,
            "arm_run": "arm_run",
            "manifest_artifact": "manifest_v1",
            "seeds": seeds,
            "n_classes": 3,
            "expect_majority": BANKED_MAJORITY,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# POST-CLOSING ADDENDUM -- PRECISION, RECALL AND F1 ON THE BEST\n"
        "# ARM'S EXISTING PREDICTIONS.\n"
        "# classification.CLASSIFICATION_METRICS_SECONDARY.\n"
        "#\n"
        "# GENERATED by scripts/generate_addendum_configs.py, whose\n"
        f"# seed list is COPIED FROM {ARM_CONFIG} -- 'the same five\n"
        "# seeds' is a fact about the file, not a claim in a comment.\n"
        "#\n"
        "# **SECONDARY AND DESCRIPTIVE. NEVER A CLAIM. NEVER A LEDGER\n"
        "# ROW.** The arm's result is its PCC. This is a SECOND\n"
        "# DESCRIPTION of the same predictions, registered because\n"
        "# 'we did not compute them' is a weaker answer than 'we\n"
        "# computed them, and here is why they are secondary'.\n"
        "#\n"
        "# **POD ARITHMETIC**: no training, no inference, no GPU. It\n"
        "# reads the five seed_<n>__predictions.csv files the arm\n"
        "# already wrote and tabulates them.\n"
        "#\n"
        "# **THREE CLASSES, NOT FIVE, AND THAT IS DECLARED HERE.** Two\n"
        "# thresholds (2.5/3.5) cut a line into THREE parts. A 5-class\n"
        "# family would need FOUR thresholds; only two are registered,\n"
        "# so the 5-class family is UNDEFINED and is reported as\n"
        "# undefined rather than invented tonight\n"
        "# (classification.THREE_NOT_FIVE).\n"
        "#\n"
        "# **THE FLOOR IS DECLARED BEFORE THE RUN**: phase9's banked\n"
        f"# class3 majority of {BANKED_MAJORITY}. The task REFUSES if the\n"
        "# truth column does not reproduce it -- that would mean the\n"
        "# median grade was collapsed rather than the mean, and a\n"
        "# metric quoted against the wrong floor is worse than none.\n"
        "#\n"
        "# **THREE CAVEATS RIDE IN THE ARTIFACT** (a) the class-support\n"
        "# vector, (b) that macro-averaging weights the smallest class\n"
        "# equally with the largest, (c) that the discretisation is a\n"
        "# REPORTING step applied after training on the continuous\n"
        "# target -- not the training objective.\n"
        "#\n"
        "# Outputs are SHAREABLE: aggregate counts only, no patient rows.\n"
        "#\n"
        + _provenance(inputs)
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{NAME}\"\n\n"
    ) + body


CONFIGS = {NAME: render}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
