"""Emit Phase 27's paired config from the locked record.

    PYTHONPATH=src python scripts/generate_phase27_paired_config.py [--check]

PLAN section 4.3's condition 1 for the phase's single contrast, which was
UNCOMPUTED at the close (``phase27.THE_CONDITION_1_REQUIREMENT``). **This
run fits nothing.** Every vector it reads was written by a keeper run
that already happened.

The pair list is NOT a config field. It comes from
``phase27.paired_claim_pairs('p27')``, so the scope cannot grow through a
config edit, which is the guard every contrast task in this repository
carries.

**Five of the ten rollups are CARRIED and five are OWED.** The probe's
vectors are already declared at verified hashes in
``configs/p10_paired.yaml``, so they are read from there rather than
retyped. Phase 27's own five have never been declared anywhere, so they
are emitted as placeholders and the config is UNRESOLVED until a declare
pass fills them. The generator refuses to invent a hash.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from cleft import ladder, phase27  # noqa: E402

CONFIGS = REPO / "configs"
OUT = CONFIGS / "p27_paired.yaml"

#: The probe's five vectors, already declared and verified. Read rather
#: than retyped, so a correction there lands here as drift.
BASELINE_SOURCE = CONFIGS / "p10_paired.yaml"

#: Phase 27's own run directory, from the ledger row that names it, so
#: the generator and the ledger cannot disagree about which run this is.
def _arm_run_dir() -> str:
    from cleft import results_ledger

    row = next(
        e for e in results_ledger.ENTRIES
        if e["id"] == "p27-anchor-train-descriptive"
    )
    if len(row["run_dirs"]) != 1:
        raise SystemExit(f"the row names {len(row['run_dirs'])} runs, not one")
    return row["run_dirs"][0]


#: The cluster path every keeper run lives under. Read from the config
#: that already declares this phase's inputs rather than typed here.
def _cluster_root() -> str:
    import yaml

    config = yaml.safe_load(
        (CONFIGS / "p27_anchor_train.yaml").read_text(encoding="utf-8")
    )
    manifest = next(
        entry for entry in config["inputs"] if entry["name"] == "manifest_v1"
    )
    return manifest["path"].split("/data/")[0]


#: The established placeholder, the same one
#: ``scripts/generate_phase26_configs.py`` uses, and the schema accepts
#: it as a valid 64-character lowercase hex digest.
#:
#: **It is emitted QUOTED.** YAML parses an unquoted run of 64 zeros as
#: an INTEGER, and the config then fails validation with "expected a
#: string, got int" before it ever reaches the hash check. A filled
#: digest almost always carries a letter and needs no quoting.
PLACEHOLDER = "0" * 64
PLACEHOLDER_YAML = f'"{PLACEHOLDER}"'


def _declared(config_path: pathlib.Path) -> dict:
    import yaml

    config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    return {entry["name"]: entry for entry in config["inputs"]}


def render() -> str:
    pairs = phase27.paired_claim_pairs("p27")
    if len(pairs) != 1:
        raise SystemExit(f"the scope is {len(pairs)} pairs, not one")
    pair = pairs[0]
    stems = ladder.paired_claim_stems("p27", pairs=pairs)
    vectors = ladder.paired_claim_vectors("p27", pairs=pairs)

    baseline = _declared(BASELINE_SOURCE)
    root = _cluster_root()
    arm_dir = _arm_run_dir()

    existing = {}
    owed = []
    lines = []
    for stem, seed in vectors:
        name = f"oof_{stem}_seed_{seed}"
        if name in baseline:
            entry = baseline[name]
            existing[name] = entry
            lines.append(
                f"- name: {name}\n"
                f"  path: {entry['path']}\n"
                f"  rollup_sha256: {entry['rollup_sha256']}\n"
            )
        else:
            owed.append(name)
            lines.append(
                f"- name: {name}\n"
                f"  path: {root}/runs/keeper/p27/{arm_dir}/"
                f"seed_{seed}__predictions.csv\n"
                f"  rollup_sha256: {PLACEHOLDER_YAML}\n"
            )

    recorded = pair["recorded"]
    return (
        "# PHASE 27 -- PLAN SECTION 4.3 CONDITION 1 FOR THE SINGLE\n"
        "# CONTRAST. phase27.THE_CONDITION_1_REQUIREMENT.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase27_paired_config.py from\n"
        "# phase27.paired_claim_pairs('p27'). Do not hand-edit except to\n"
        "# fill the owed rollups: --check will fail on anything else.\n"
        "#\n"
        "# **THIS RUN FITS NOTHING.** Every vector was written by a\n"
        "# keeper run that already happened. No GPU, no training, no\n"
        "# re-extraction, and no patient leaves the cluster: the\n"
        "# computation goes to the data and an AGGREGATE summary comes\n"
        "# back (five deltas with their intervals and a verdict).\n"
        "#\n"
        f"# **SCOPE: p27.** {len(pairs)} pair over {len(stems)} run\n"
        f"# directories, {len(vectors)} vectors, the shared five seeds.\n"
        "# Same task, same BCa, same loader as every other scope. Only\n"
        "# the pair enumeration differs, and it lives in phase27.\n"
        "#\n"
        "# **THE PREDICTION IS ARITHMETIC ON RECORDED FIGURES** (derived\n"
        "# from THE_RESULT_OBSERVED and ladder.STAGE_D1_AT_G1, never\n"
        "# typed):\n"
        f"#   {pair['key']}\n"
        f"#     d {recorded['delta_of_means']:+.4f}  "
        f"threshold {recorded['threshold']:.4f}  "
        f"margin {recorded['margin']}x\n"
        "#   Condition 2 PASSES. Condition 1 is EXPECTED TO FAIL: the\n"
        "#   delta sits inside ladder.COHORT_CANNOT_RESOLVE's measured\n"
        "#   0.04 to 0.10 unresolvable band, where 30 comparisons have\n"
        "#   been tested and one survived. What the row becomes under\n"
        "#   either outcome is pre-written at\n"
        "#   phase27.THE_ROW_UNDER_EACH_OUTCOME.\n"
        "#\n"
        "# **THE oof_ PREFIX IS THE LOADER'S CONVENTION, NOT A CLAIM.**\n"
        "# This arm's vectors are PURE TEST, not out-of-fold: no cohort\n"
        "# patient was ever in the fit. That is stronger than\n"
        "# out-of-fold, not weaker.\n"
        "#\n"
        "# **THE ASYMMETRY TRAVELS**: the probe's 237 predictions come\n"
        "# from five models, one per fold, and this arm's from one\n"
        "# (phase27.PAIRED_CLAIM_COVERAGE).\n"
        "#\n"
        + (
            "# **UNRESOLVED.** "
            f"{len(existing)} of {len(vectors)} vectors are CARRIED from\n"
            "# configs/p10_paired.yaml at verified hashes. The other\n"
            f"# {len(owed)} have never been declared anywhere and are\n"
            "# emitted as all-zero placeholders. Fill them from the\n"
            "# output of scripts/declare_inputs.py on the cluster, never\n"
            "# from a chat log:\n"
            "#\n"
            "#   bash -lc \"cd /home/user/codex/cleft-aesthetics && "
            "PYTHONPATH=src \\\\\n"
            "#     python scripts/declare_inputs.py "
            "configs/p27_paired.yaml\"\n"
            "#\n"
            "# then, once the five are filled:\n"
            if owed else
            "# **RESOLVED.** All vectors declared at real paths with\n"
            "# verified hashes.\n"
        )
        + "#\n"
        "#   bash -lc \"cd /home/user/codex/cleft-aesthetics && "
        "PYTHONPATH=src \\\\\n"
        "#     python -m cleft.run --config configs/p27_paired.yaml\"\n"
        "\n"
        "schema_version: 1\n"
        "phase: p27\n"
        "tier: keeper\n"
        "seed: 1337\n"
        "inputs:\n"
        + "".join(lines)
        + "task:\n"
        "  kind: paired_claims\n"
        "  scope: p27\n"
        "  n_boot: 10000\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="compare against what is on disk instead of writing",
    )
    args = parser.parse_args()

    rendered = render()
    if not args.check:
        OUT.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"wrote {OUT.relative_to(REPO).as_posix()}")
        return 0

    if not OUT.is_file():
        print(f"MISSING {OUT.relative_to(REPO).as_posix()}")
        return 1
    on_disk = OUT.read_text(encoding="utf-8")
    if on_disk == rendered:
        print(f"{OUT.relative_to(REPO).as_posix()}: matches the record")
        return 0

    # A filled rollup is the ONE edit this config invites, so it is not
    # reported as drift. Everything else is.
    want = rendered.split("\n")
    got = on_disk.split("\n")
    if len(want) != len(got):
        print("DRIFT: the files differ in length")
        return 1
    filled = 0
    for number, (a, b) in enumerate(zip(want, got), start=1):
        if a == b:
            continue
        if a.strip() == f"rollup_sha256: {PLACEHOLDER_YAML}" and b.strip().startswith(
            "rollup_sha256: "
        ):
            candidate = b.strip().split(": ", 1)[1]
            if len(candidate) == 64 and set(candidate) <= set("0123456789abcdef"):
                filled += 1
                continue
        print(f"DRIFT at line {number}\n  record: {a!r}\n  disk:   {b!r}")
        return 1
    print(
        f"{OUT.relative_to(REPO).as_posix()}: matches the record "
        f"({filled} rollup(s) filled by a declare pass)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
