"""Write the Phase 9 configs from ``cleft.phase9`` and arm A's own config.

    PYTHONPATH=src python scripts/generate_phase9_configs.py [--check]

**Two configs.** Both run on arm A's inputs, CARRIED from its shipped
config -- the medoids' space and the external reference's heads are the
same arm, so "same space"/"same arm" are true by construction. [The
external reference was blocked until 2026-08-16's reads landed
(``phase9.DEALL_REFERENCE_READS``); its ``deall_set`` input starts
PENDING -- the folder path is the maintainer's to supply, then the declare
pass fills the hash, and this generator carries both verbatim.]

**The pre-registration is not here.** The space, distance, tie rule,
groupings, LOO scope, bootstrap statistic and the committed prior live in
``cleft.phase9`` where the suite checks them.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

from cleft import phase9  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"

#: Arm A -- the registered space's own arm; its verified input entries are
#: carried, never retyped.
SOURCE_CONFIG = "p7_d1_vit_b16_imagenet_g1.yaml"


def source(name: str = SOURCE_CONFIG) -> dict:
    return yaml.safe_load((REPO / "configs" / name).read_text(encoding="utf-8"))


def render_prototypes() -> str:
    arm = source()
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    spec = phase9.PROTOTYPES_REGISTERED
    payload = {
        "schema_version": 1,
        "phase": "p9",
        "tier": "keeper",
        "seed": spec["bootstrap"]["seed"],
        "inputs": [
            dict(inputs_by_name["manifest_v1"]),
            dict(inputs_by_name["staged_v1"]),
            dict(inputs_by_name["embeddings"]),
        ],
        "task": {
            "kind": "prototypes",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "embeddings_artifact": "embeddings",
            "geometry": arm["task"]["geometry"],
            "label": arm["task"]["label"],
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 9 — THE PROTOTYPES: MEDOIDS PER GRADE IN ARM A'S SPACE.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase9_configs.py from cleft.phase9\n"
        f"# and {SOURCE_CONFIG} (the space's own verified entries, carried).\n"
        "# LAUNCH-READY: all three inputs are already-declared paths.\n"
        "#\n"
        "# **THE REGISTRATION IS NOT HERE** (phase9.PROTOTYPES_REGISTERED,\n"
        "# every choice resolved by the maintainer 2026-08-16 BEFORE any\n"
        "# computation): Euclidean medoids in\n"
        f"# {spec['space']['embeddings']};\n"
        "# ties toward the lower patient id; PRIMARY = three class3\n"
        "# medoids, validated by LOO identity stability (ceiling (n-1)/n,\n"
        "# stated) with the nearest-medoid accuracy companion and the\n"
        "# majority baseline printed; bootstrap = identity persistence\n"
        f"# frequency, {spec['bootstrap']['n_boot']:,} resamples, seed\n"
        f"# {spec['bootstrap']['seed']}. SECONDARY = five-grade (median)\n"
        "# medoids, DESCRIPTIVE only.\n"
        "#\n"
        "# **THE COMMITTED PRIOR travels with the run**: the t-SNE\n"
        "# companion read 0.409 against majority 0.502, so the space's\n"
        "# neighbourhoods predict class3 WORSE than majority guessing --\n"
        "# unstable medoids CORROBORATE that; stable medoids would be the\n"
        "# surprise. Both readings committed before any number.\n"
        "#\n"
        "# MEDOIDS ARE PATIENT FACES: the sheet and the id-bearing json\n"
        "# are CLUSTER-ONLY; metrics.json carries numbers only.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p9_prototypes.yaml\"\n\n"
    ) + body


#: Copied verbatim from arm A's config for the refit -- the external
#: reference scores with arm A's heads, so "same arm" must be true by
#: construction (the phase-8 generators' rule).
COPIED = (
    "geometry", "label", "backbone", "seeds", "inner_val_frac",
    "max_epochs", "patience", "monitor", "learning_rate", "weight_decay",
    "batch_size",
)

PLACEHOLDER = "0" * 64

#: **[FILLED 2026-08-16, from the listing this session]** The
#: 25-set folder: 75 image files + Thumbs.db + cl_images_test_details.csv
#: inside -- 25 identities x 3 views, the CSV covered by the same rollup.
#: The HASH is carried from the shipped config once the declare pass has
#: filled it, and a placeholder until then -- the two-pass shape, like
#: the phase-8 generators' run-dir constants.
#: The 25-set, declared BY ROLE. The literal path named the holding
#: institution and one of the two national studies in its parents;
#: the value now comes from the environment on the cluster and the
#: declared rollup_sha256 verifies whatever resolved.
DEALL_SET_PATH = "${CLEFT_ANCHOR_SET}"
DEALL_INPUT = "deall_set"


def _deall_entry() -> dict:
    rollup = PLACEHOLDER
    shipped = REPO / "configs" / "p9_deall_reference.yaml"
    if shipped.is_file():
        payload = yaml.safe_load(shipped.read_text(encoding="utf-8"))
        for entry in payload.get("inputs") or []:
            if entry.get("name") != DEALL_INPUT:
                continue
            carried = str(entry.get("rollup_sha256") or "")
            if (
                entry.get("path") == DEALL_SET_PATH
                and len(carried) == 64
                and set(carried) <= set("0123456789abcdef")
                and set(carried) != {"0"}
            ):
                rollup = carried
    return {
        "name": DEALL_INPUT,
        "path": DEALL_SET_PATH,
        "rollup_sha256": rollup,
    }


def render_deall_reference() -> str:
    arm = source()
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    reads = phase9.DEALL_REFERENCE_READS
    deall_entry = _deall_entry()
    task = {
        "kind": "deall_reference",
        "manifest_artifact": "manifest_v1",
        "staged_artifact": "staged_v1",
        "embeddings_artifact": "embeddings",
        "deall_artifact": DEALL_INPUT,
    }
    missing = [name for name in COPIED if name not in arm["task"]]
    if missing:
        raise SystemExit(f"{SOURCE_CONFIG} no longer carries {missing}")
    task.update({name: arm["task"][name] for name in COPIED})
    payload = {
        "schema_version": 1,
        "phase": "p9",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        "inputs": [
            dict(inputs_by_name["manifest_v1"]),
            dict(inputs_by_name["staged_v1"]),
            dict(inputs_by_name["embeddings"]),
            deall_entry,
        ],
        "task": task,
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    pending = set(deall_entry["rollup_sha256"]) == {"0"}
    return (
        "# PHASE 9 — THE 25-IMAGE EXTERNAL REFERENCE: THE FROZEN BEST ARM\n"
        "# ON THE DEALL/CLEFTGNN BENCHMARK SET. NEVER POOLED WITH COHORT\n"
        "# RESULTS.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase9_configs.py from cleft.phase9\n"
        f"# and {SOURCE_CONFIG} (the refit block copied -- same arm, same\n"
        "# 0.2520 gate; no refitting touches the 25).\n"
        "#\n"
        "# **REGISTERED BEFORE ANY NUMBER** (phase9.DEALL_REFERENCE_\n"
        "# REGISTERED + _READS): generalisation to a DIFFERENT label -- the\n"
        "# survey-design key's five-grade Score (spread 3/7/6/6/3, asserted\n"
        "# at runtime), whose equality with the manuscript's 27-surgeon\n"
        "# consensus CANNOT be asserted from disk and is not forced.\n"
        "# External reference only; the first directly-placed number beside\n"
        "# CleftGNN Table 5, on the same 25 images. All 25 frozen heads\n"
        "# (5 seeds x 5 folds) score every image -- an external image\n"
        "# belongs to no fold -- mean and spread reported.\n"
        "#\n"
        "# **THE TRAP** (recorded, asserted): the labels are\n"
        f"# {phase9.DEALL_LABELS_FILENAME} INSIDE the images folder; the\n"
        "# The derived per-image labels CSV AND APScores.txt beside the set\n"
        "# are\n"
        "# the 251-row COHORT sheet in two forms, and the reader refuses\n"
        "# both by filename pin and 25-row assert.\n"
        "#\n"
        "# **STAGING** (the READS' answer): G1's whole-image input is the\n"
        "# PLAIN staged square; the trapezium is patch geometry only. The\n"
        "# LAUNCH waits on the eyeballed composite -- one image must show a\n"
        "# single nasolabial view, no montage, framed like the cohort's\n"
        "# crops; a fuller composition becomes a recorded caveat, the\n"
        "# maintainer's call. The run writes deall_staged_sheet.png, which\n"
        "# documents exactly what the backbone saw.\n"
        "#\n"
        + (
            (
                "# **deall_set's path is FILLED (2026-08-16, from the\n"
                "# maintainer's listing: 75 image files + Thumbs.db + the\n"
                "# labels CSV inside) and its hash is an all-zeros\n"
                "# PLACEHOLDER** pending declare_inputs.py -- ONE hash\n"
                "# covers folder AND labels CSV, since the CSV lives\n"
                "# inside. Guard 3 refuses the placeholder until filled,\n"
                "# which is the placeholder working.\n"
            )
            if pending
            else (
                "# deall_set is FILLED and carried: path from the maintainer's\n"
                "# listing, hash from the declare pass, both carried by this\n"
                "# generator verbatim.\n"
            )
        )
        + "# Every other hash is arm A's verified entry, carried.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p9_deall_reference.yaml\"\n\n"
    ) + body


def render_prototype_classifier() -> str:
    arm = source()
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    spec = phase9.PROTOTYPE_CLASSIFIER_REGISTERED
    payload = {
        "schema_version": 1,
        "phase": "p9",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        "inputs": [
            dict(inputs_by_name["manifest_v1"]),
            dict(inputs_by_name["staged_v1"]),
            dict(inputs_by_name["embeddings"]),
            _deall_entry(),
        ],
        "task": {
            "kind": "prototype_classifier",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "embeddings_artifact": "embeddings",
            "deall_artifact": DEALL_INPUT,
            "geometry": arm["task"]["geometry"],
            "label": arm["task"]["label"],
            "backbone": arm["task"]["backbone"],
            "batch_size": arm["task"]["batch_size"],
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 9 — THE PROTOTYPE CLASSIFIER: THE SUPERVISOR'S ACTUAL READING OF\n"
        "# \"PROTOTYPES\". THE 25 ANCHORS' GRADES REACH EACH COHORT PATIENT\n"
        "# THROUGH RAW FEATURE DISTANCE. NO TRAINING ANYWHERE.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase9_configs.py from cleft.phase9\n"
        f"# and {SOURCE_CONFIG}. FULLY DECLARED: every input is an\n"
        "# already-verified entry, carried (the deall_set hash from the\n"
        "# corrected-layout declare pass).\n"
        "#\n"
        "# **THE REGISTRATION IS NOT HERE**\n"
        "# (phase9.PROTOTYPE_CLASSIFIER_REGISTERED): 4 cells per metric\n"
        "# (k in {1,3} x plain/weighted -- {1,3} is the admissible set on\n"
        "# the CORRECTED arithmetic: strict majority for the 3-anchor\n"
        "# extreme grades fails outright at k>=6 and needs perfection at\n"
        "# k=4,5; k=3 is the largest k with slack), Euclidean primary and\n"
        "# cosine secondary, ALL cells reported, none selected after the\n"
        "# fact. Anchor grades are trusted SINGLE grades from the survey\n"
        "# lineage, not verified-unanimous -- recorded; supervision can confirm.\n"
        "#\n"
        "# **THE PREDICTION IS COMMITTED BOTH WAYS** before any number:\n"
        "# three convergent priors (t-SNE 0.409 below majority; medoid\n"
        "# companion 0.257 below chance; 769 fitted parameters needed for\n"
        "# 0.2520) say near-or-below chance -- which would be the THIRD\n"
        "# convergent measurement of the phase's central finding, by the supervision material's\n"
        "# own suggested method. Beating the priors would be genuinely\n"
        "# surprising and would matter more.\n"
        "#\n"
        "# GPU, small: the -3 external-reference run persisted scores and\n"
        "# sheet, NOT the 25 features, so this task re-extracts the 25\n"
        "# live through the same recorded path, parity check repeated.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p9_prototype_classifier.yaml\"\n\n"
    ) + body


CONFIGS = {
    "p9_prototypes.yaml": render_prototypes,
    "p9_deall_reference.yaml": render_deall_reference,
    "p9_prototype_classifier.yaml": render_prototype_classifier,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    print(
        f"prototypes and deall-reference inputs carried from "
        f"{SOURCE_CONFIG}; deall_set path filled, hash "
        + ("PLACEHOLDER pending the declare pass"
           if set(_deall_entry()["rollup_sha256"]) == {"0"}
           else "filled and carried")
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
