"""Write Road B Phase 2's configs from ``cleft.roadb``.

    PYTHONPATH=src python scripts/generate_roadb_configs.py [--check]

Ten staging configs, one per setting, plus the residual gate. **The setting
list is not in any config** -- ``roadb.staging_settings()`` derives it, so a
config cannot add a cell the axis does not contain.

Inputs are copied from Road A's Phase 2 config rather than retyped: the same
manifest and the same source folders, so "same sources" is true by
construction rather than by proofreading.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

from cleft import roadb  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"
SOURCE_CONFIG = "p2_stage_and_patch.yaml"
SHARED_INPUTS = ("manifest_v1", "patient_folders")
PLACEHOLDER = "0" * 64


def shared_inputs() -> list[dict]:
    payload = yaml.safe_load(
        (REPO / "configs" / SOURCE_CONFIG).read_text(encoding="utf-8")
    )
    by_name = {entry["name"]: entry for entry in payload["inputs"]}
    missing = [name for name in SHARED_INPUTS if name not in by_name]
    if missing:
        raise SystemExit(f"{SOURCE_CONFIG} no longer declares {missing}")
    return [dict(by_name[name]) for name in SHARED_INPUTS]


def existing(stem: str) -> dict:
    """Resolved entries only -- a placeholder is re-derivable by definition."""
    path = REPO / "configs" / f"{stem}.yaml"
    if not path.is_file():
        return {}
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {
        entry["name"]: entry
        for entry in payload.get("inputs", [])
        if entry.get("rollup_sha256") != PLACEHOLDER
    }


def existing_entries(stem: str) -> dict:
    """Entries with ANYTHING filled -- a resolved hash OR a resolved path.

    ``existing`` carries only resolved hashes, which is right when the path
    is known from the start and the hash arrives later. Where the PATH
    arrives first (a run directory pasted before its declare pass), that
    rule would discard the fill on the next regeneration.
    """
    path = REPO / "configs" / f"{stem}.yaml"
    if not path.is_file():
        return {}
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {
        entry["name"]: entry
        for entry in payload.get("inputs", [])
        if entry.get("rollup_sha256") != PLACEHOLDER
        or "/PENDING_" not in entry.get("path", "")
    }


def stage_config(setting: dict, inputs: list[dict]) -> str:
    task = {
        "kind": "roadb_stage",
        "setting": setting["name"],
        "manifest_artifact": "manifest_v1",
        "patient_folders": "patient_folders",
        "out_version": setting["artifact"],
    }
    payload = {
        "schema_version": 1, "phase": "roadb_p2", "tier": "keeper",
        "seed": 1337, "inputs": [dict(e) for e in inputs], "task": task,
    }
    expectation = setting["expected_non_content"]
    return (
        f"# ROAD B PHASE 2 — {setting['name']}\n"
        "#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from cleft.roadb.\n"
        "#\n"
        f"# {setting['resolution']}px, {setting['aspect']}, "
        f"{setting['geometry']} -> data/staged/{setting['artifact']}/\n"
        "#\n"
        "# **ITS OWN ARTIFACT.** Guard 3 verifies the rollup, so one shared\n"
        "# artifact would couple all ten: re-running any cell would break\n"
        "# guard 3 for every config declaring it, including ones whose own\n"
        "# setting never changed. roadb.ARTIFACT_PER_SETTING.\n"
        "#\n"
        + (
            "# **The square path reuses FROZEN code at a new argument.**\n"
            "# staging.stage takes `size` and has only ever run at 224, so\n"
            "# resize_nearest at this size is an untested regime -- cheap to\n"
            "# build, not free of risk. The residual gate is what catches it.\n"
            "# roadb_staging.FROZEN_CODE_NEW_REGIME.\n"
            if setting["aspect"] == "square" else
            "# **Non-square is new code**, in roadb_staging.stage_non_square,\n"
            "# reusing the frozen resize_nearest and Staged so the resampling\n"
            "# is the same operation the square path uses. A second resize\n"
            "# would make the aspect axis a resampling comparison too.\n"
        )
        + "#\n"
        + (
            f"# Expected non-content fraction: {expectation}. A saliency map\n"
            "# read on this staging needs THIS expectation, not another\n"
            "# setting's -- phase8's refuted framing finding is what happens\n"
            "# when one expectation is used for a different region.\n"
            if expectation is not None else
            "# Non-content is per PATIENT here (it depends on aspect ratio),\n"
            "# so the artifact records it per patient rather than per setting.\n"
        )
        + (
            "#\n"
            "# **This cell is half of the clean pad pair.** Against Road A's\n"
            "# staged_v1 it differs only by the pad -- stage pads THEN\n"
            "# resizes, so the content pixel box is identical. Every 512\n"
            "# comparison confounds pad removal with resolution; this does\n"
            "# not. A Phase 4 or 7 arm consumes it.\n"
            if setting["resolution"] == roadb.CONTROL_RESOLUTION else ""
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{setting['name'].lower()}.yaml\"\n\n"
        + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    )


def gate_config() -> str:
    stem = "roadb_p2_residual_gate"
    inputs, unresolved = artifact_inputs(stem)
    payload = {
        "schema_version": 1, "phase": "roadb_p2", "tier": "keeper",
        "seed": 1337, "inputs": inputs,
        "task": {"kind": "roadb_residual_gate"},
    }
    return (
        "# ROAD B PHASE 2 — THE PER-FAMILY RESIDUAL GATE\n"
        "#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from cleft.roadb.\n"
        "#\n"
        "# **A separate run because no single staging run sees all three\n"
        "# resolutions.** It reads each artifact's recorded pixel residual\n"
        "# plus Road A's 224 from roadb.ROAD_A_224_PIXEL_RESIDUAL.\n"
        "#\n"
        "# **The ordering is WITHIN a family** -- (aspect, geometry) -- because\n"
        "# the residual tracks column count: non-square 512 has ~379 columns\n"
        "# and a larger residual than square 512, which is fewer columns and\n"
        "# not a defect. A pooled ordering would report it as one.\n"
        "# roadb.RESIDUAL_FAMILIES.\n"
        "#\n"
        "# **It records the rollups it reads.** It reads artifacts it does not\n"
        "# own, so a re-run after the verdict leaves the verdict silently\n"
        "# wrong; the recorded rollups are how a later reader can tell whether\n"
        "# the verdict still describes what is on disk.\n"
        "#\n"
        + (
            f"# **THE {unresolved} HASHES BELOW ARE ALL-ZERO PLACEHOLDERS.**\n"
            "# The artifacts do not exist until the ten staging runs land.\n"
            "# Guard 3 refuses this run until they are real -- the placeholder\n"
            "# working rather than a mistake.\n"
            if unresolved else
            "# **RESOLVED.** All ten artifacts declared with verified hashes.\n"
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{stem}.yaml\"\n\n"
        + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    )


def artifact_inputs(stem: str) -> tuple[list[dict], int]:
    """The ten artifact declarations for a config that reads all ten.

    Resolved hashes are carried from this config's own file first, then from
    the gate's -- the sheets and the verdict must describe the SAME bytes,
    so re-pasting hashes independently would be a place for them to diverge.
    """
    carried = existing(stem)
    fallback = existing("roadb_p2_residual_gate") if stem != "roadb_p2_residual_gate" else {}
    inputs = []
    for setting in roadb.staging_settings():
        name = setting["artifact"]
        inputs.append(carried.get(name) or fallback.get(name) or {
            "name": name,
            "path": f"{CLUSTER_ROOT}/data/staged/{name}",
            "rollup_sha256": PLACEHOLDER,
        })
    unresolved = sum(1 for e in inputs if e["rollup_sha256"] == PLACEHOLDER)
    return inputs, unresolved


def sheets_config() -> str:
    stem = "roadb_p2_sheets"
    inputs, unresolved = artifact_inputs(stem)
    payload = {
        "schema_version": 1, "phase": "roadb_p2", "tier": "keeper",
        "seed": 1337, "inputs": inputs,
        "task": {"kind": "roadb_sheets", "max_patients": 41, "columns": 6},
    }
    return (
        "# ROAD B PHASE 2 — BOTH CONTACT SHEETS\n"
        "#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from cleft.roadb.\n"
        "#\n"
        "# **The review these feed gates Phase 3** (brief §6): every phase\n"
        "# that skipped the sheet produced a defect no test caught.\n"
        "# CLUSTER-ONLY PNGs -- patient faces.\n"
        "#\n"
        "# **The axis sheet**: 4 patients x all ten settings, downscaled to a\n"
        "# common display size. Patients are picked evenly across the aspect\n"
        "# ratios measured in the 224 non-square G1 artifact's geometry.csv,\n"
        "# extremes included -- the pad and the corners differ most at the\n"
        "# extremes, which is where framing defects live.\n"
        "#\n"
        "# **The detail strip**: every flagged upsampled patient at NATIVE\n"
        "# resolution -- measured frontal counts 1 at 512 and 41 at 768\n"
        "# (2026-08-09). max_patients 41 shows them all; columns 6 is the row\n"
        "# width, and a setting wraps across rows rather than truncating.\n"
        "#\n"
        "# Inputs are the same ten artifacts as the residual gate, at the\n"
        "# same hashes, so the sheets and the verdict describe the same\n"
        "# bytes.\n"
        + (
            f"#\n# **{unresolved} HASHES BELOW ARE ALL-ZERO PLACEHOLDERS** --\n"
            "# guard 3 refuses until the staging runs land.\n"
            if unresolved else ""
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{stem}.yaml\"\n\n"
        + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    )


#: Each Road B pretraining cell mirrors ONE Road A config -- the transformers'
#: masked_g1 runs, the graphs' native-scheme masked_g1 runs (native is the
#: machinery gate 3 measured). The task block is copied VERBATIM: since gate 2
#: the builder derives input size from the data, so the task carries no size
#: field and "same procedure, different input" is byte equality.
ROAD_A_PRETRAIN_COUNTERPARTS = {
    "vit_b16": "p6_pretrain_vit_b16_masked_g1",
    "swin_b": "p6_pretrain_swin_b_masked_g1",
    "srgnn": "p6_pretrain_srgnn_native_masked_g1",
    "agnet": "p6_pretrain_agnet_native_masked_g1",
}
MASKED_ARTIFACTS = {224: "masked_v1", 512: "masked_512_v1", 768: "masked_768_v1"}


def pretrain_config(backbone: str, size: int) -> tuple[str, str]:
    """One Phase 6 cell: Road A's counterpart with only the artifact changed."""
    counterpart = ROAD_A_PRETRAIN_COUNTERPARTS[backbone]
    source_payload = yaml.safe_load(
        (REPO / "configs" / f"{counterpart}.yaml").read_text(encoding="utf-8")
    )
    stem = f"roadb_{counterpart}_{size}"

    inputs = []
    masked_unresolved = False
    carried = existing(stem)
    for entry in source_payload["inputs"]:
        entry = dict(entry)
        if entry["name"] == "masked_scut":
            artifact = MASKED_ARTIFACTS[size]
            entry["path"] = f"{CLUSTER_ROOT}/data/scut/{artifact}"
            if size != 224:
                entry["rollup_sha256"] = (
                    carried.get("masked_scut", {}).get("rollup_sha256")
                    or PLACEHOLDER
                )
                masked_unresolved = entry["rollup_sha256"] == PLACEHOLDER
            # 224 keeps Road A's masked_v1 hash verbatim -- same artifact.
        inputs.append(entry)

    # [2026-08-10] The pretrained init as a DECLARED input, for the
    # transformer cells whose consumption route exists. The graph backbones'
    # route is a recorded follow-up and task_pretrain REFUSES the declaration
    # until it lands -- an input the run never reads would be a provenance
    # record claiming weights fed a run they did not feed.
    init_unresolved = False
    if backbone in ("vit_b16", "swin_b"):
        init_entry = carried.get("pretrained_init") or {
            "name": "pretrained_init",
            "path": f"{CLUSTER_ROOT}/data/inits/init_{backbone}_v1",
            "rollup_sha256": PLACEHOLDER,
        }
        init_unresolved = init_entry["rollup_sha256"] == PLACEHOLDER
        inputs.append(init_entry)

    payload = {
        "schema_version": source_payload["schema_version"],
        "phase": "roadb_p6",
        "tier": source_payload["tier"],
        "seed": source_payload["seed"],
        "inputs": inputs,
        # VERBATIM -- the field-for-field test asserts dict equality.
        "task": source_payload["task"],
    }

    is_first = backbone == "vit_b16" and size == 512
    heavy = backbone in ("vit_b16", "swin_b") and size == 768
    header = (
        f"# ROAD B PHASE 6 — {backbone} PRETRAINING AT {size} (masked G1)\n"
        "#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from "
        f"{counterpart}.yaml.\n"
        f"# The task block is that config's VERBATIM -- same fixed 30-epoch\n"
        "# budget, best-checkpoint selection, same monitor -- asserted "
        "field-for-\n"
        "# field by test. Since gate 2 the builder derives input size from "
        "the\n"
        "# data (roadb.PRETRAIN_BUILDER_THREADS_INPUT_SIZE), so ONLY the "
        "declared\n"
        "# masked artifact differs.\n"
        "#\n"
        + (
            "# **LAUNCH THIS CELL FIRST.** The frozen cliff was measured on "
            "ViT at\n"
            "# these sizes and the whole branch turns on it: if this trains "
            "stably\n"
            "# and lands in the published band, the other eleven are the same "
            "path\n"
            "# with different arguments; if it does not, that is learned on "
            "one run\n"
            "# rather than twelve. It is also the direct test of\n"
            "# SWIN_RESOLUTION_PREDICTION's trained-regime reading: whether\n"
            "# adapting the position grid repairs what interpolating it "
            "broke.\n"
            if is_first else
            "# LAUNCH ORDER: roadb_p6_pretrain_vit_b16_masked_g1_512 runs "
            "FIRST\n"
            "# (roadb.PHASE_6_TWELVE_CELLS) -- the cliff arm decides whether "
            "the\n"
            "# other eleven launch.\n"
        )
        + (
            "#\n"
            "# **COSTING NOTE -- the heaviest runs in the project.** At 768 "
            "this\n"
            "# transformer attends over a 48x48 patch grid (ViT: 2,304 tokens "
            "with\n"
            "# quadratic attention; Swin: padded 7-windows over a 192x192 "
            "grid),\n"
            "# over 3,300 training images for 30 fixed epochs. Cost is a fact "
            "to\n"
            "# plan around, not an argument (brief §1) -- but plan the queue "
            "for\n"
            "# it rather than discovering it there.\n"
            if heavy else ""
        )
        + (
            "#\n"
            "# **[MEASURED 2026-08-10] A 27.94 GiB GPU FRACTION OOMed at 768 "
            "after\n"
            "# six resume attempts** -- all four 768 cells, header-only "
            "curves, no\n"
            "# epochs completed. Plan a WHOLE device, not a fraction. "
            "Nothing about\n"
            "# the failures is scientific; they relaunch as-is with memory.\n"
            if size == 768 else ""
        )
        + (
            "#\n"
            "# **224 IS A RE-RUN OF ROAD A'S CELL under the Road B SHA** -- "
            "same\n"
            "# artifact, same procedure. vit/swin/srgnn measured bitwise in "
            "the\n"
            "# image, so the checkpoint should reproduce Road A's exactly (a "
            "free\n"
            "# end-to-end determinism check, the masked-rebuild pattern); "
            "agnet\n"
            "# reproduces to ~2.3e-05 (models/agnet.py TRAINING_DETERMINISM)."
            "\n"
            if size == 224 else ""
        )
        + "#\n"
        "# **Each cell is its OWN seed regime** (PLAN 4.12: a trained "
        "backbone's\n"
        "# band is never inherited). No Road B Phase 7 arm reads against "
        "this\n"
        "# cell before its band exists -- roadb.PHASE_6_TWELVE_CELLS.\n"
        + (
            "#\n"
            "# **THE pretrained_init HASH BELOW IS AN ALL-ZERO "
            "PLACEHOLDER.**\n"
            f"# data/inits/init_{backbone}_v1 is built by\n"
            f"# roadb_init_snapshot_{backbone}.yaml; paste that run's\n"
            "# metrics.json `artifact.rollup_sha256_for_configs`. Guard 3\n"
            "# refuses until then. The init was the one input guard 3 never\n"
            "# verified (roadb.PRETRAINED_INIT_IS_NOW_DECLARABLE); declared,\n"
            "# what this run started from is in inputs.json.\n"
            if init_unresolved else ""
        )
        + (
            "#\n"
            "# **THE masked_scut HASH BELOW IS AN ALL-ZERO PLACEHOLDER.**\n"
            f"# data/scut/{MASKED_ARTIFACTS[size]} is built by\n"
            f"# roadb_p5_masked_scut_{size}.yaml; paste that run's "
            "metrics.json\n"
            "# `artifact.rollup_sha256_for_configs` (declare_inputs.py "
            "discovers\n"
            "# this config). Guard 3 refuses until then -- the placeholder\n"
            "# working rather than a mistake.\n"
            if masked_unresolved else
            "#\n"
            f"# masked_scut RESOLVED: data/scut/{MASKED_ARTIFACTS[size]}'s "
            "own\n"
            "# `artifact.rollup_sha256_for_configs` (keeper rebuild). The "
            "four\n"
            f"# cells at {size} declare the identical artifact at the "
            "identical\n"
            "# hash -- asserted by test, because one sibling reading a "
            "different\n"
            "# artifact would make a backbone difference an input "
            "difference.\n"
            if size != 224 else ""
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{stem}.yaml\"\n\n"
        + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    )
    return stem, header


#: The staged artifact each resolution's extraction reads, at the verified
#: hashes (staged_v1 from Road A; the Road B pair from the residual gate).
STAGED_FOR_EXTRACTION = {
    224: ("staged_v1",
          "a06401b9b474c241182e07d697939a8903bdf92c9c470fdfe7a423add155a406"),
    512: ("roadb_512_square_g1_v1",
          "fa0ba0269491f33c055463081b81579f7991670860873494c518aa0c87865fca"),
    768: ("roadb_768_square_g1_v1",
          "b4cbd5150cb08f5ad6890687d6327c80cdc313027dd0478a38dc4a5d136822e8"),
}

#: The four declared init snapshots, from their build runs' own metrics.
INIT_HASHES = {
    "vit_b16": "c974c782e08b8791a3ecec38c5c3b96a919681a3576fc0808abb395fc94c1ea7",
    "swin_b": "934fb9804f23a91d34c0e36e24fae555837a5f0a94a6ba54d1d3fdd4ac118b39",
    "srgnn": "2c48719cb27b061b43c5ff9a7b75415399ecd92a8b1e111c46b1a6cb20e89cea",
    "agnet": "b3fdbbfe568f45c5ed7e3ac9f4f3e293c5f032643ccfec79fc40bf28e7a82cf5",
}

MANIFEST_HASH = "fb5177b31f2aa61bfac25f8a528004bf2075adb83128516a002e29eafbee0aff"


def extraction_config(entry: dict, detcheck: bool = False) -> tuple[str, str]:
    """One Phase 7 extraction cell: one set, its own artifact, per
    PHASE_7_EXTRACTION_PLAN's grouping decision."""
    from cleft.train import extract as extract_module

    backbone = entry["backbone"]
    resolution = entry["resolution"]
    init = entry["init"]
    short = "imagenet" if init == "imagenet" else "masked"
    scheme = (
        "native" if backbone in ("srgnn", "agnet") and init != "imagenet"
        else None
    )
    stem = f"roadb_p7_extract_{backbone}_{short}_{resolution}"
    out_version = f"roadb_emb_{backbone}_{short}_g1_{resolution}_v1"
    if detcheck:
        stem += "_detcheck"
        out_version = out_version.replace("_v1", "_detcheck_v1")

    staged_name, staged_hash = STAGED_FOR_EXTRACTION[resolution]
    inputs = [
        {"name": "manifest_v1",
         "path": f"{CLUSTER_ROOT}/data/manifests/cleft_v1",
         "rollup_sha256": MANIFEST_HASH},
        {"name": staged_name,
         "path": f"{CLUSTER_ROOT}/data/staged/{staged_name}",
         "rollup_sha256": staged_hash},
    ]
    pending = False
    if init == "imagenet":
        inputs.append({
            "name": "pretrained_init",
            "path": f"{CLUSTER_ROOT}/data/inits/init_{backbone}_v1",
            "rollup_sha256": INIT_HASHES[backbone],
        })
    else:
        ckpt_name = extract_module.checkpoint_input_name({
            "backbone": backbone, "variant": "masked_g1",
            "pretrain_scheme": scheme,
        })
        carried = existing(stem).get(ckpt_name)
        entry_ckpt = carried or {
            "name": ckpt_name,
            "path": (
                f"{CLUSTER_ROOT}/runs/keeper/roadb_p6/"
                f"PENDING_{backbone}_{resolution}/pretrained.npz"
            ),
            "rollup_sha256": PLACEHOLDER,
        }
        pending = entry_ckpt["rollup_sha256"] == PLACEHOLDER
        pending_path = "/PENDING_" in entry_ckpt["path"]
        inputs.append(entry_ckpt)

    set_entry = {"backbone": backbone, "init": init, "geometry": "g1"}
    if scheme:
        set_entry["pretrain_scheme"] = scheme
    payload = {
        "schema_version": 1, "phase": "roadb_p7", "tier": "keeper",
        "seed": 1337, "inputs": inputs,
        "task": {
            "kind": "extract_embeddings",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": staged_name,
            "out_version": out_version,
            "batch_size": 32,
            "per_fold_bn_reestimation": False,
            "sets": [set_entry],
        },
    }
    header = (
        f"# ROAD B PHASE 7 EXTRACTION — {backbone} {short} at {resolution}"
        + (" — THE DETERMINISM CHECK COPY" if detcheck else "") + "\n#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from\n"
        "# roadb.phase7_extraction_sets().\n#\n"
        "# ONE set, its OWN artifact (roadb.PHASE_7_EXTRACTION_PLAN "
        "grouping):\n"
        "# Phase 7 consumes selectively, and a shared artifact would stale\n"
        "# every declaration on any partial re-extraction. The resolution\n"
        "# lives in the artifact VERSION; the set name repeats across\n"
        "# resolutions by design.\n"
        + (
            "#\n# imagenet extracts from the DECLARED snapshot "
            "(init-vintage rule:\n"
            "# every point of the trend starts from the same verified "
            "bytes).\n"
            if init == "imagenet" else
            "#\n# **THE CHECKPOINT PATH AND HASH BELOW ARE PLACEHOLDERS.** "
            "Fill both\n"
            "# from the run records per the DRAW-PICK RULE: the first "
            "completed\n"
            "# Blackwell run of this cell at the current unfused SHA, by "
            "launch\n"
            "# order, NEVER by score (roadb.PHASE_7_EXTRACTION_PLAN). "
            "Guard 3\n"
            "# refuses until then -- the placeholder working.\n"
            if pending else
            "#\n# **HASH FILLED; THE PATH IS STILL A PLACEHOLDER RUN "
            "DIRECTORY.**\n"
            "# The checkpoint's rollup came from the run's record; the run "
            "DIRECTORY\n"
            "# name was not pasted, so the path still says PENDING and "
            "guard 3\n"
            "# refuses to resolve it -- paste the directory from the run "
            "record.\n"
            if pending_path else
            "#\n# Checkpoint resolved from the run records"
            + (" (roadb.VIT_DRAW_PICKS\n# carries this cell's pick "
               "rationale).\n" if backbone == "vit_b16" else ".\n")
        )
        + (
            "#\n# **RUNS SECOND, after its twin.** Same set, out_version "
            "*_detcheck_v1\n"
            "# -- no config ever declares it. Payload rollups byte-equal "
            "clears the\n"
            "# whole batch (on_pass, one recorded decision) and this "
            "artifact is\n"
            "# then DELETED; a difference stops the batch (on_fail).\n"
            if detcheck else ""
        )
        + (
            "#\n# **LEADS THE QUEUE, then its _detcheck twin.** The pair "
            "is the\n"
            "# pre-registered ViT extraction determinism confirmation.\n"
            if (backbone, resolution, init, detcheck)
            == ("vit_b16", 512, "imagenet", False) else ""
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{stem}.yaml\"\n\n"
        + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    )
    return stem, header


#: Each Road B arm mirrors ONE Road A ladder arm at G1 -- the harness and
#: regime hyperparameters ride through VERBATIM; only identity fields
#: (backbone, init, artifacts, seeds by regime) are overridden. All
#: counterparts are already at G1, so no geometry override exists anywhere.
#: GRAPH counterparts are PER BACKBONE: agnet arms carry a field srgnn's
#: never do (`deterministic: false` -- the measured roi_align bound,
#: declared rather than defaulted, schema-enforced), so copying srgnn's
#: task for an agnet arm ships an invalid config. The schema caught
#: exactly that on the first generation.
ROAD_A_ARM_COUNTERPARTS = {
    ("transformer", "imagenet"): "p7_d1_vit_b16_imagenet_g1",
    ("transformer", "scut_masked"): "p7_c_swin_b_scut_masked_g1",
    ("srgnn", "imagenet"): "p7_d1_srgnn_imagenet_g1_native",
    ("srgnn", "scut_masked"): "p7_d1_srgnn_scut_masked_g1_native",
    ("agnet", "imagenet"): "p7_d1_agnet_imagenet_g1_native",
    ("agnet", "scut_masked"): "p7_d1_agnet_scut_masked_g1_native",
}


def _counterpart_key(arm: dict) -> tuple[str, str]:
    kind = arm["backbone"] if arm["regime"] == "graph" else "transformer"
    return kind, arm["init"]

SWEEP_STEM = "roadb_p7_graph_seed_band"


def _arm_stem(arm: dict) -> str:
    short = "imagenet" if arm["init"] == "imagenet" else "masked"
    return f"roadb_p7_arm_{arm['backbone']}_{short}_{arm['resolution']}"


def _arm_payload(
    arm: dict, stem: str, fallback_stem: str | None = None
) -> tuple[dict, dict]:
    """One arm's payload -- also the sweep's, for the band cell, which is
    how "task block identical by construction" is construction rather
    than proofreading. Returns (payload, state) where state carries what
    the header needs to say."""
    from cleft import embedding_plan, ladder

    backbone, resolution = arm["backbone"], arm["resolution"]
    init, regime = arm["init"], arm["regime"]
    counterpart = ROAD_A_ARM_COUNTERPARTS[_counterpart_key(arm)]
    source = yaml.safe_load(
        (REPO / "configs" / f"{counterpart}.yaml").read_text(encoding="utf-8")
    )
    task = dict(source["task"])
    staged_name, staged_hash = STAGED_FOR_EXTRACTION[resolution]
    task["backbone"] = backbone
    task["init"] = init
    task["staged_artifact"] = staged_name
    task["seeds"] = list(ladder.SEED_POOL[: arm["seeds"]])

    inputs = [
        {"name": "manifest_v1",
         "path": f"{CLUSTER_ROOT}/data/manifests/cleft_v1",
         "rollup_sha256": MANIFEST_HASH},
        {"name": staged_name,
         "path": f"{CLUSTER_ROOT}/data/staged/{staged_name}",
         "rollup_sha256": staged_hash},
    ]
    state = {"counterpart": counterpart}

    if "bitwise reuse" in arm["set_artifact"]:
        # The counterpart IS Road A's swin masked-G1 224 arm, so its own
        # entries are the reuse entries -- copied verbatim, "same bytes"
        # by construction.
        road_a = {e["name"]: e for e in source["inputs"]}
        emb_entry = dict(road_a["embeddings"])
        ckpt_entry = dict(road_a["ckpt_swin_b_masked_g1"])
        inputs += [emb_entry, ckpt_entry]
        task["checkpoint"] = ckpt_entry["name"]
        state.update(reuse=True, emb_placeholder=False, ckpt_state="resolved")
        payload = {
            "schema_version": 1, "phase": "roadb_p7", "tier": "keeper",
            "seed": 1337, "inputs": inputs, "task": task,
        }
        return payload, state

    scheme = "native" if regime == "graph" and init != "imagenet" else None
    set_dir = embedding_plan.set_name({
        "backbone": backbone, "init": init, "geometry": "g1",
        "pretrain_scheme": scheme,
    })
    carried = existing(stem).get("embeddings")
    if not carried and fallback_stem:
        carried = existing(fallback_stem).get("embeddings")
    emb_entry = carried or {
        "name": "embeddings",
        "path": (
            f"{CLUSTER_ROOT}/data/embeddings/{arm['set_artifact']}/{set_dir}"
        ),
        "rollup_sha256": PLACEHOLDER,
    }
    inputs.append(emb_entry)
    state.update(
        reuse=False,
        emb_placeholder=emb_entry["rollup_sha256"] == PLACEHOLDER,
        ckpt_state=None,
    )

    if init != "imagenet":
        # The paired checkpoint, copied VERBATIM from the extraction
        # config -- the run refuses a mismatch between the set's recorded
        # checkpoint and the declared one, and copying is how the two
        # configs cannot disagree. Placeholder states mirror through.
        ex_stem = f"roadb_p7_extract_{backbone}_masked_{resolution}"
        ex_payload = yaml.safe_load(
            (REPO / "configs" / f"{ex_stem}.yaml").read_text(encoding="utf-8")
        )
        ckpts = [
            e for e in ex_payload["inputs"] if e["name"].startswith("ckpt_")
        ]
        if len(ckpts) != 1:
            raise SystemExit(f"{ex_stem} declares {len(ckpts)} checkpoints")
        ckpt_entry = dict(ckpts[0])
        inputs.append(ckpt_entry)
        task["checkpoint"] = ckpt_entry["name"]
        state["ckpt_state"] = (
            "placeholder" if ckpt_entry["rollup_sha256"] == PLACEHOLDER
            else "resolved"
        )

    payload = {
        "schema_version": 1, "phase": "roadb_p7", "tier": "keeper",
        "seed": 1337, "inputs": inputs, "task": task,
    }
    return payload, state


def arm_config(arm: dict) -> tuple[str, str]:
    """One Phase 7 arm, derived from roadb.phase7_arms()."""
    stem = _arm_stem(arm)
    is_band_cell = (arm["backbone"], arm["resolution"], arm["init"]) == (
        "srgnn", 512, "scut_masked"
    )
    payload, state = _arm_payload(
        arm, stem, SWEEP_STEM if is_band_cell else None
    )
    short = "imagenet" if arm["init"] == "imagenet" else "masked"
    blocked = state["ckpt_state"] == "placeholder"
    family_gated = (
        arm["init"] == "scut_masked"
        and arm["backbone"] in ("swin_b", "vit_b16")
        and arm["resolution"] != 768
    )
    header = (
        f"# ROAD B PHASE 7 ARM — {arm['backbone']} {short} at "
        f"{arm['resolution']}\n"
        "#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from\n"
        "# roadb.phase7_arms().\n"
        "#\n"
        f"# family {arm['family']} | {arm['regime']} regime, "
        f"{arm['seeds']} seeds (roadb.PHASE_7_SEED_COUNTS)\n"
        f"# artifact: {arm['set_artifact']}\n"
        f"# reporting: {arm['reporting']}\n"
        "#\n"
        f"# The task block is {state['counterpart']}.yaml's in every "
        "harness and\n"
        "# hyperparameter field -- only identity fields differ (backbone, "
        "init,\n"
        "# artifacts, seeds by regime), asserted field-for-field by test. "
        "This\n"
        "# arm reports its OWN seed SD (4.12.1); bands plan, never "
        "denominate.\n"
        + (
            "#\n"
            "# **ROAD A'S SET, BITWISE REUSE -- fully resolved; launchable "
            "now.**\n"
            "# The checkpoint measured bitwise-identical and the extraction "
            "path is\n"
            "# unchanged, so Road A's set IS this cell's (identity, not\n"
            "# assumption -- roadb.phase7_extraction_sets). Both entries "
            "below are\n"
            "# copied verbatim from p7_c_swin_b_scut_masked_g1.yaml.\n"
            if state["reuse"] else ""
        )
        + (
            "#\n"
            "# **BLOCKED ON THE -3 CELL.** The checkpoint does not exist "
            "yet (the\n"
            "# whole-GPU relaunch is queued), so neither does the set: "
            "BOTH hashes\n"
            "# below are ALL-ZERO PLACEHOLDERS, the checkpoint entry "
            "mirroring the\n"
            "# extraction config's state. Guard 3 refuses -- the "
            "placeholder\n"
            "# working. This arm's FAMILY reports nothing until this point "
            "lands\n"
            "# (roadb.PHASE_7_PARTIAL_LAUNCH).\n"
            if blocked else ""
        )
        + (
            "#\n"
            "# **THE embeddings HASH BELOW IS AN ALL-ZERO PLACEHOLDER.** "
            "The set\n"
            "# is built and verified on the cluster but never DECLARED: "
            "one\n"
            "# scripts/declare_inputs.py pass over the extraction "
            "artifacts fills\n"
            "# every arm's hash -- the blocker is a paste, not a build\n"
            "# (roadb.PHASE_7_PARTIAL_LAUNCH). Guard 3 refuses until then "
            "-- the\n"
            "# placeholder working.\n"
            if state["emb_placeholder"] and not blocked else
            "#\n"
            "# embeddings RESOLVED: the declare pass over the built set\n"
            "# (roadb.PHASE_7_PARTIAL_LAUNCH.declaration_pass_landed).\n"
            if not state["emb_placeholder"] and not state["reuse"] else ""
        )
        + (
            "#\n"
            "# Checkpoint entry copied VERBATIM from the extraction config "
            "-- the\n"
            "# run refuses a mismatch between the set's recorded "
            "checkpoint and\n"
            "# the declared one, and copying is how the two configs cannot\n"
            "# disagree.\n"
            if state["ckpt_state"] == "resolved" and not state["reuse"]
            else ""
        )
        + (
            "#\n"
            "# **THE SWEEP DOUBLES AS THIS ARM'S RUN** "
            "(roadb_p7_graph_seed_band:\n"
            "# same cell, same ten seeds, task block identical by "
            "construction).\n"
            "# Relaunching this config after the sweep duplicates it "
            "bit-for-bit;\n"
            "# read this arm's numbers from the sweep's run directory.\n"
            if is_band_cell else ""
        )
        + (
            "#\n"
            "# **LAUNCH GATE: waits on the graph band sweep's READING**\n"
            "# (roadb.PHASE_7_GRAPH_BAND_SWEEP). Inside the F-interval -> "
            "proceed;\n"
            "# outside -> per-resolution graph bands and the design "
            "re-reads\n"
            "# first.\n"
            if arm["regime"] == "graph" and not is_band_cell else ""
        )
        + (
            "#\n"
            "# Not gated by the sweep: frozen-head fits are the regime\n"
            "# SEED_BAND_RESOLVED already banded across resolutions -- "
            "zero new\n"
            "# bands.\n"
            if arm["regime"] == "transformer" else ""
        )
        + (
            "#\n"
            "# **DESCRIPTIVE, decided before any arm ran**: this cell is "
            "ONE\n"
            "# checkpoint draw (roadb.VIT_DRAW_PICKS names it; the "
            "measured draw\n"
            "# spread -- 0.055 at 224, 0.027 at 512 -- rides ON TOP of "
            "this arm's\n"
            "# seed SD, and the arm cannot see it). No trend claim from "
            "this\n"
            "# family.\n"
            if arm["backbone"] == "vit_b16" else ""
        )
        + (
            "#\n"
            "# **FAMILY REPORT GATE** (roadb.PHASE_7_PARTIAL_LAUNCH): this "
            "arm\n"
            "# RUNS now, but its family reports only when the 768 point "
            "lands --\n"
            "# a two-point family is a line, not a shape.\n"
            if family_gated else ""
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{stem}.yaml\"\n\n"
        + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    )
    return stem, header


def sweep_config() -> str:
    """The graph-head seed band sweep -- the srgnn masked-512 arm's
    payload verbatim, wrapped in the pre-registered decision rule. It
    runs BEFORE any other graph arm; its reading is their launch gate."""
    band_arm = [
        a for a in roadb.phase7_arms()
        if (a["backbone"], a["resolution"], a["init"]) == (
            "srgnn", 512, "scut_masked"
        )
    ]
    if len(band_arm) != 1:
        raise SystemExit("phase7_arms() no longer names the band cell once")
    arm = band_arm[0]
    payload, state = _arm_payload(arm, SWEEP_STEM, _arm_stem(arm))
    sweep = roadb.PHASE_7_GRAPH_BAND_SWEEP
    against = sweep["compared_against"]
    return (
        "# ROAD B PHASE 7 — THE GRAPH-HEAD SEED BAND SWEEP. RUNS BEFORE "
        "ANY\n"
        "# GRAPH ARM.\n"
        "#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from\n"
        "# roadb.PHASE_7_GRAPH_BAND_SWEEP.\n"
        "#\n"
        "# TEN seeds of the srgnn masked-512 arm. The task block below is\n"
        "# roadb_p7_arm_srgnn_masked_512.yaml's, identical by construction "
        "(one\n"
        "# generator function builds both), so this run DOUBLES AS that "
        "arm's\n"
        "# run: relaunching the arm config afterwards would duplicate it\n"
        "# bit-for-bit. train_graph_cv reports seed_variance.json from its "
        "own\n"
        "# ten seeds -- the p6_srgnn_seed_band procedure.\n"
        "#\n"
        f"# **F-COMPARED against Road A's measured graph band**: SD "
        f"{against['sd']},\n"
        f"# ten seeds, run {against['run']}\n"
        "# (graph_cleft.MEASURED_GRAPH_SEED_BAND). Same ladder.SEED_POOL "
        "ten, so\n"
        "# the comparison is like-for-like. The statistic is the F-based "
        "95% CI\n"
        "# on SD_roadB/SD_roadA -- F(9,9), the observed ratio x [1/2.01, "
        "2.01].\n"
        "#\n"
        "# **BOTH READINGS, REGISTERED BEFORE THE RUN** (the Phase 3 "
        "discipline\n"
        "# -- SEED_BAND_DESIGN.decision_rule_preregistered: a window "
        "chosen\n"
        "# after seeing the result is a forking path):\n"
        "#\n"
        "#   * CI CONTAINS 1 -> the sweep cannot distinguish the regimes: "
        "ONE\n"
        "#     graph planning band, the LARGER of the two SDs (the\n"
        "#     conservatism Phase 3's three-point application settled), "
        "and\n"
        "#     the graph arms PROCEED.\n"
        "#   * CI EXCLUDES 1 -> per-resolution graph bands, and the "
        "design\n"
        "#     RE-READS before any further graph arm launches. "
        "Transformer\n"
        "#     arms are not gated either way (SEED_BAND_RESOLVED covers "
        "them,\n"
        "#     zero new bands).\n"
        "#\n"
        "# Sensitivity, stated with the rule: ten-vs-ten F(9,9) detects "
        "only\n"
        "# ~2x divergence.\n"
        "#\n"
        "# **What the seed varies** -- the SAME three things as Road A's "
        "band,\n"
        "# NOT graph-layer init (warm-started from the paired checkpoint,\n"
        "# byte-identical across seeds): classifier init, batch order, "
        "and the\n"
        "# inner-val split. Quote all three when quoting either band "
        "(4.12.1).\n"
        + (
            "#\n"
            "# **THE embeddings HASH BELOW IS AN ALL-ZERO PLACEHOLDER.** "
            "The set\n"
            "# is built and verified on the cluster but never DECLARED: "
            "one\n"
            "# scripts/declare_inputs.py pass fills it (and every arm's). "
            "Guard 3\n"
            "# refuses until then -- the placeholder working. The "
            "checkpoint\n"
            "# entry is the extraction config's, resolved.\n"
            if state["emb_placeholder"] else
            "#\n"
            "# **ALL FOUR INPUT HASHES ARE REAL — READY TO LAUNCH.** The\n"
            "# embeddings rollup came from the declare pass over the "
            "built set;\n"
            "# the checkpoint entry is the extraction config's, resolved.\n"
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{SWEEP_STEM}.yaml\"\n\n"
        + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    )


PAIRED_STEM = "roadb_p7_paired_resolution"

#: Branch 3's staged artifact -- one of the residual gate's verified ten,
#: so its declaration is CARRIED from the gate rather than retyped.
NONSQUARE_768_G2 = "roadb_768_nonsquare_g2_v1"


def regioncrop_control_configs() -> list[tuple[str, str]]:
    """The whole-frame control arm at the CROPS' staging: one extraction,
    one five-seed arm.

    This is defect 1 of the brief, corrected
    (roadb.REGION_CROP_STRUCTURE): §3 nominated Road B's existing 768
    arm, which reads square G1 while the crops come from non-square G2.
    Both configs use existing machinery -- ViT imagenet from the declared
    snapshot, frozen, head-only -- so the control is buildable now while
    the crop path is still a build.
    """
    from cleft import ladder

    name = NONSQUARE_768_G2
    gate = existing("roadb_p2_residual_gate")
    if name not in gate:
        raise SystemExit(f"{name} is not resolved in the residual gate")
    staged = gate[name]

    emitted = []
    extract_stem = "roadb_p7c_crops_vit_b16_whole"
    out_version = "roadb_emb_crops_vit_b16_whole_g2_768nsq_v1"
    extract_payload = {
        "schema_version": 1, "phase": "roadb_p7c", "tier": "keeper",
        "seed": 1337,
        "inputs": [
            {"name": "manifest_v1",
             "path": f"{CLUSTER_ROOT}/data/manifests/cleft_v1",
             "rollup_sha256": MANIFEST_HASH},
            dict(staged),
            {"name": "pretrained_init",
             "path": f"{CLUSTER_ROOT}/data/inits/init_vit_b16_v1",
             "rollup_sha256": INIT_HASHES["vit_b16"]},
        ],
        "task": {
            "kind": "roadb_region_crop_extract",
            "staged_artifact": name,
            "out_version": out_version,
            "backbone": "vit_b16",
            "init": "imagenet",
            "layout": "whole",
            "batch_size": 32,
        },
    }
    emitted.append((extract_stem,
        "# ROAD B BRANCH 3 — THE CONTROL (whole frame, 768 NON-SQUARE "
        "G2)\n#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from\n"
        "# roadb.regioncrop_arms().\n#\n"
        "# **THE BRIEF'S CONTROL WAS MISMATCHED AND THIS REPLACES IT.**\n"
        "# §3 nominated Road B's existing 768 ViT arm, which reads\n"
        "# roadb_768_square_g1_v1 -- while the crops come from "
        "NON-SQUARE G2\n"
        "# (§2.1: at G1 the lateral anatomy regions fall 76.4% on "
        "white).\n"
        "# Comparing them would vary cropping, aspect AND geometry at "
        "once --\n"
        "# the matched-pipeline trap roadb.PHASE_7_RESOLUTION_PAIRING "
        "records.\n#\n"
        "# **[CORRECTED 2026-08-14] It runs through the CROP path, not "
        "the\n"
        "# extraction task.** The first attempt used extract_embeddings "
        "and\n"
        "# died in phase3.load_inputs: that path wants "
        "staged_patient_g2.npy,\n"
        "# the STACKED tensor, and a non-square artifact can never have "
        "one --\n"
        "# the shapes differ per patient, and stacking them was one of "
        "the\n"
        "# five original stage-task defects. Even given a loader, "
        "non-square\n"
        "# frames cannot batch and would give every patient a different "
        "ViT\n"
        "# token count.\n#\n"
        "# So the control is ONE region that is the whole content box, "
        "cut and\n"
        "# resized to 224 exactly as each crop is. crop-vs-whole then "
        "differs\n"
        "# in CONTENT ALONE -- one whole face against 22 magnified "
        "regions --\n"
        "# rather than in content plus batching plus token count, and "
        "the\n"
        "# control inherits the same square stretch the crops get, which "
        "is\n"
        "# what makes it a comparator rather than a confound.\n#\n"
        "# Output is an ordinary POOLED set (n_patients, dim), the shape\n"
        "# train_cv reads -- its single region is not a region.\n#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{extract_stem}.yaml\"\n\n"
        + yaml.safe_dump(extract_payload, sort_keys=False,
                         default_flow_style=False)))

    source = yaml.safe_load(
        (REPO / "configs" / "p7_d1_vit_b16_imagenet_g1.yaml")
        .read_text(encoding="utf-8")
    )
    arm_stem = "roadb_p7c_arm_control_whole_vit"
    task = dict(source["task"])
    task["staged_artifact"] = name
    task["geometry"] = "g2"
    task["seeds"] = list(ladder.SEED_POOL[:5])
    # The control reads an ordinary pooled set -- declared, so it reads
    # the same way every other arm does rather than by omission.
    task["consume"] = "pooled"
    carried = existing_entries(arm_stem)
    # **Carrying must not survive a PATH change.** The control's set moved
    # when it switched to the crop path, and a carried entry kept pointing
    # at the old out_version -- an arm declaring a set nothing produces.
    # So the carry is conditional on the path still being the derived one.
    expected_emb = (
        f"{CLUSTER_ROOT}/data/embeddings/{out_version}/"
        "vit_b16__imagenet__whole"
    )
    emb = carried.get("embeddings")
    if emb is None or emb.get("path") != expected_emb:
        emb = {
            "name": "embeddings",
            "path": expected_emb,
            "rollup_sha256": PLACEHOLDER,
        }
    arm_payload = {
        "schema_version": 1, "phase": "roadb_p7c", "tier": "keeper",
        "seed": 1337,
        "inputs": [
            {"name": "manifest_v1",
             "path": f"{CLUSTER_ROOT}/data/manifests/cleft_v1",
             "rollup_sha256": MANIFEST_HASH},
            dict(staged),
            emb,
        ],
        "task": task,
    }
    # The three crop sets the five arms read: ViT anatomy, ViT random, and
    # SR-GNN anatomy (the graph arm and its matched concat partner share it).
    for backbone, layout in (
        ("vit_b16", "anatomy"), ("vit_b16", "random"), ("srgnn", "anatomy"),
    ):
        stem = f"roadb_p7c_crops_{backbone}_{layout}"
        emitted.append((stem,
            f"# ROAD B BRANCH 3 — CROP EXTRACTION ({backbone}, {layout})\n#\n"
            "# GENERATED by scripts/generate_roadb_configs.py.\n#\n"
            "# **RUNS ONLY AFTER THE SHEET IS REVIEWED** "
            "(roadb_p7c_region_crop_sheet):\n"
            "# whether a box labelled philtral_column contains one is an eye\n"
            "# question, and no arm may consume crops that failed it.\n#\n"
            "# 22 anatomy regions per patient, cut from the non-square G2\n"
            "# staging and resized to the 224 backbone input -- the\n"
            "# magnification is in the CROP, not the input size. Extracted\n"
            "# **ONCE**: frozen backbone, head-only fits downstream, so "
            "every\n"
            "# arm reads this set and nothing re-extracts per epoch.\n#\n"
            "# **No new torch surface**: the crops are flattened into one\n"
            "# stack and handed to the same extract_features every Road B "
            "set\n"
            "# used, then reshaped to (n_patients, 22, dim) and saved as\n"
            "# kind `region_vectors` with its ORDERED region names, so a\n"
            "# consumer asks which column is philtral_column rather than\n"
            "# trusting position (embeddings.REGION_VECTORS_IS_NOT_PER_"
            "REGION).\n"
            + (
                "#\n"
                "# **The random control.** Same 22 boxes, re-placed inside "
                "the\n"
                "# mask at a fixed seed -- count, size distribution and "
                "total\n"
                "# area match the anatomy set EXACTLY, so placement is the "
                "only\n"
                "# difference. This is the arm that decides whether a "
                "positive\n"
                "# finding is about anatomy or about cropping.\n"
                if layout == "random" else ""
            )
            + "#\n"
            f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
            f"#     python -m cleft.run --config configs/{stem}.yaml\"\n\n"
            + yaml.safe_dump({
                "schema_version": 1, "phase": "roadb_p7c", "tier": "keeper",
                "seed": 1337,
                "inputs": [
                    {"name": "manifest_v1",
                     "path": f"{CLUSTER_ROOT}/data/manifests/cleft_v1",
                     "rollup_sha256": MANIFEST_HASH},
                    dict(staged),
                    {"name": "pretrained_init",
                     "path": f"{CLUSTER_ROOT}/data/inits/init_{backbone}_v1",
                     "rollup_sha256": INIT_HASHES[backbone]},
                ],
                "task": {
                    "kind": "roadb_region_crop_extract",
                    "staged_artifact": name,
                    "out_version": (
                        f"roadb_emb_crops_{backbone}_{layout}_g2_768nsq_v1"
                    ),
                    "backbone": backbone,
                    "init": "imagenet",
                    "layout": layout,
                    "batch_size": 32,
                },
            }, sort_keys=False, default_flow_style=False)))

    # The four crop arms (the control ships above). Each DECLARES how it
    # reads its set -- concat or nodes -- because one region_vectors
    # artifact serves both and the wrong pairing is silent.
    crop_sets = {
        ("vit_b16", "anatomy"): "roadb_emb_crops_vit_b16_anatomy_g2_768nsq_v1",
        ("vit_b16", "random"): "roadb_emb_crops_vit_b16_random_g2_768nsq_v1",
        ("srgnn", "anatomy"): "roadb_emb_crops_srgnn_anatomy_g2_768nsq_v1",
    }
    for arm in roadb.regioncrop_arms():
        if arm["key"] == "control_whole_vit":
            continue
        arm_stem_c = f"roadb_p7c_arm_{arm['key']}"
        graph = arm["combination"] == "graph"
        layout = "random" if "random" in arm["key"] else "anatomy"
        set_version = crop_sets[(arm["backbone"], layout)]
        counterpart_stem = (
            "p7_d1_srgnn_imagenet_g1_native" if graph
            else "p7_d1_vit_b16_imagenet_g1"
        )
        source_c = yaml.safe_load(
            (REPO / "configs" / f"{counterpart_stem}.yaml")
            .read_text(encoding="utf-8")
        )
        task_c = dict(source_c["task"])
        task_c["backbone"] = arm["backbone"]
        task_c["staged_artifact"] = name
        task_c["geometry"] = "g2"
        task_c["seeds"] = list(ladder.SEED_POOL[: arm["seeds"]])
        task_c["consume"] = "nodes" if graph else "concat"
        if not graph:
            task_c.pop("region_scheme", None)
            task_c["trainable"] = "head"

        expected_c = (
            f"{CLUSTER_ROOT}/data/embeddings/{set_version}/"
            f"{arm['backbone']}__imagenet__{layout}"
        )
        carried_c = existing_entries(arm_stem_c).get("embeddings")
        emb_c = (
            carried_c if carried_c and carried_c.get("path") == expected_c
            else {"name": "embeddings", "path": expected_c,
                  "rollup_sha256": PLACEHOLDER}
        )
        emitted.append((arm_stem_c,
            f"# ROAD B BRANCH 3 ARM — {arm['key']}\n#\n"
            "# GENERATED by scripts/generate_roadb_configs.py from\n"
            "# roadb.regioncrop_arms().\n#\n"
            f"# {arm['tests']}\n#\n"
            f"# Reads {set_version}\n"
            f"# and declares **consume: {task_c['consume']}** "
            "(embeddings.as_consumed).\n"
            "# One region_vectors set serves BOTH concat and nodes, so the "
            "shape\n"
            "# is DECLARED rather than inferred: a graph arm handed a "
            "flattened\n"
            "# vector would train happily and report a number. Flattening "
            "is C\n"
            "# order -- 22 contiguous blocks of D, in the set's own "
            "`regions`\n"
            "# order, which is what makes a flattened vector "
            "interpretable.\n#\n"
            + (
                "# **Pooled to 2048 per crop, and NOT SR-GNN as "
                "published**\n"
                "# (roadb.GRAPH_ARM_POOLS_TO_VECTORS): pooling makes\n"
                "# SeqSelfAttention a smaller layer. This arm tests "
                "message passing\n"
                "# over anatomy-crop embeddings, not the published "
                "architecture.\n#\n"
                if arm["backbone"] == "srgnn" else ""
            )
            + (
                "# **The control that decides what a positive finding is "
                "ABOUT.**\n"
                "# The same 22 boxes as the anatomy arm, re-placed inside "
                "the mask:\n"
                "# count, size distribution and total area match exactly, "
                "so\n"
                "# placement is the only difference. Its regions are named "
                "random_NN\n"
                "# because laterality is anatomical and a moved box has "
                "none\n"
                "# (roadb.RANDOM_ARM_NAMES_WERE_THE_DEFECT).\n#\n"
                if layout == "random" else ""
            )
            + f"# Frozen backbone, head-only, {arm['seeds']} seeds "
            f"({arm['regime']} regime).\n"
            "# Reports its OWN seed SD (4.12.1). The bar is unchanged: "
            "this cohort\n"
            "# resolves ViT-collapse-sized effects and nothing smaller.\n"
            + (
                "#\n"
                "# **THE embeddings HASH BELOW IS AN ALL-ZERO "
                "PLACEHOLDER.** The\n"
                "# crop set is built and verified on the cluster but not "
                "yet\n"
                f"# DECLARED: run scripts/declare_inputs.py over\n"
                f"# {set_version}. Guard 3 refuses until then -- the\n"
                "# placeholder working rather than a mistake.\n"
                if emb_c["rollup_sha256"] == PLACEHOLDER else
                "#\n# embeddings RESOLVED from the declare pass.\n"
            )
            + "#\n"
            f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
            f"#     python -m cleft.run --config configs/{arm_stem_c}.yaml\""
            "\n\n"
            + yaml.safe_dump({
                "schema_version": 1, "phase": "roadb_p7c", "tier": "keeper",
                "seed": 1337,
                "inputs": [
                    {"name": "manifest_v1",
                     "path": f"{CLUSTER_ROOT}/data/manifests/cleft_v1",
                     "rollup_sha256": MANIFEST_HASH},
                    dict(staged),
                    emb_c,
                ],
                "task": task_c,
            }, sort_keys=False, default_flow_style=False)))

    for mode, why in (
        ("native", "the crops AS CUT -- the information present"),
        ("as_fed", "the crops AS THE BACKBONE RECEIVES THEM"),
    ):
        sheet_stem = (
            "roadb_p7c_region_crop_sheet"
            + ("" if mode == "native" else "_as_fed")
        )
        native = mode == "native"
        emitted.append((sheet_stem,
            f"# ROAD B BRANCH 3 — THE CROP SHEET ({mode}). THE GATE.\n#\n"
            "# GENERATED by scripts/generate_roadb_configs.py.\n#\n"
            "# **NO BRANCH 3 ARM RUNS UNTIL BOTH SHEETS ARE REVIEWED**\n"
            "# (brief §5 criterion 3). Whether a box labelled\n"
            "# `philtral_column` contains a philtral column is checked by "
            "eye\n"
            "# or not at all.\n#\n"
            f"# **This sheet shows {why}.**\n#\n"
            + (
                "# The face with its 22 boxes drawn and named answers *is "
                "this the\n"
                "# right anatomy*; the crops at NATIVE resolution answer "
                "*does a\n"
                "# ~150 px philtral column show anything* -- the "
                "magnification\n"
                "# premise. **It does NOT show the square resize**, which "
                "is what\n"
                "# the _as_fed sheet is for.\n"
                if native else
                "# **The second sheet, and the one that closes a real gap.**\n"
                "# `crop_region` resizes every window to 224x224, so a "
                "149x124 box\n"
                "# arrives at the backbone STRETCHED -- measured ratios "
                "span 0.72\n"
                "# to 1.54 before squaring. The native sheet deliberately "
                "hides\n"
                "# that, so the first review confirmed anatomy and "
                "magnification\n"
                "# while never seeing what the model receives. Captions "
                "name the\n"
                "# source size and the ratio.\n#\n"
                "# It confounds no contrast -- every arm is squared "
                "identically,\n"
                "# and the whole-frame control is squared too -- but a "
                "stretched\n"
                "# philtral column looks fine in the numbers and wrong to a\n"
                "# clinician (roadb.SHEETS_MUST_SHOW_WHAT_THE_CONSUMER_"
                "RECEIVES).\n"
            )
            + "#\n"
            "# **The random control is rendered too**: it decides what a "
            "positive\n"
            "# finding is ABOUT, so its placement gets the same eye.\n#\n"
            "# CLUSTER-ONLY PNGs (patient faces); patient ids stay in the\n"
            "# CLUSTER-ONLY size record, never in metrics.json.\n#\n"
            f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
            f"#     python -m cleft.run --config configs/{sheet_stem}.yaml\""
            "\n\n"
            + yaml.safe_dump({
                "schema_version": 1, "phase": "roadb_p7c", "tier": "keeper",
                "seed": 1337,
                "inputs": [
                    {"name": "manifest_v1",
                     "path": f"{CLUSTER_ROOT}/data/manifests/cleft_v1",
                     "rollup_sha256": MANIFEST_HASH},
                    dict(staged),
                ],
                "task": {
                    "kind": "roadb_region_crop_sheet",
                    "staged_artifact": name,
                    "n_patients": 8,
                    "columns": 6,
                    "mode": mode,
                },
            }, sort_keys=False, default_flow_style=False)))

    emitted.append((arm_stem,
        "# ROAD B BRANCH 3 — THE CONTROL ARM (whole frame, 768 "
        "non-square G2)\n#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from\n"
        "# roadb.regioncrop_arms().\n#\n"
        "# **The real control**, replacing the brief's mismatched one -- "
        "which\n"
        "# read square G1 against crops from non-square G2, varying "
        "cropping,\n"
        "# aspect and geometry at once. Task block is\n"
        "# p7_d1_vit_b16_imagenet_g1.yaml's, with only the staging, "
        "geometry\n"
        "# and seed count changed -- asserted field-for-field by test.\n#\n"
        "# Frozen, head-only, five seeds (transformer regime,\n"
        "# roadb.PHASE_7_SEED_COUNTS). Reports its OWN seed SD; bands "
        "plan\n"
        "# and never denominate (4.12.1).\n#\n"
        "# **The bar this branch must clear is recorded before it runs**\n"
        "# (roadb.ROAD_B_PHASE_7_CLOSING): this cohort resolves effects "
        "of\n"
        "# ViT-collapse size and nothing smaller. A 0.03 improvement "
        "will\n"
        "# not be claimable however real it is.\n"
        + (
            "#\n"
            "# **THE embeddings HASH IS AN ALL-ZERO PLACEHOLDER** -- the "
            "set is\n"
            "# built by the extraction config beside this one. Guard 3 "
            "refuses\n"
            "# until it is declared; the placeholder working.\n"
            if emb["rollup_sha256"] == PLACEHOLDER else
            "#\n# embeddings RESOLVED from the declare pass.\n"
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{arm_stem}.yaml\"\n\n"
        + yaml.safe_dump(arm_payload, sort_keys=False,
                         default_flow_style=False)))
    return emitted


def paired_config() -> str:
    """PLAN 4.3 condition 1 over Road B's resolution axis. Fits nothing.

    Same task, same BCa, same loader as Road A's scopes -- only the pair
    enumeration differs, and it is derived in roadb.paired_claim_pairs.
    """
    from cleft import ladder

    pairs = roadb.paired_claim_pairs("roadb_resolution")
    vectors = ladder.paired_claim_vectors("roadb_resolution", pairs=pairs)
    stems = ladder.paired_claim_stems("roadb_resolution", pairs=pairs)
    # **Carried on the PATH as well as the hash.** These vectors resolve in
    # two passes -- run directories first (from the run listing), hashes
    # after (declare_inputs discovers the config only once the paths are
    # real) -- so carrying resolved-hash-only would revert 170 filled paths
    # on the next regeneration. Same three-state shape as the extraction
    # configs' checkpoints, arrived at from the other side.
    carried = existing_entries(PAIRED_STEM)

    inputs = []
    for stem, seed in vectors:
        name = f"oof_{stem}_seed_{seed}"
        inputs.append(carried.get(name) or {
            "name": name,
            "path": (
                f"{CLUSTER_ROOT}/runs/keeper/roadb_p7/"
                f"PENDING_{stem}/seed_{seed}__predictions.csv"
            ),
            "rollup_sha256": PLACEHOLDER,
        })
    unresolved = sum(1 for e in inputs if e["rollup_sha256"] == PLACEHOLDER)
    pending_paths = sum(1 for e in inputs if "/PENDING_" in e["path"])

    payload = {
        "schema_version": 1, "phase": "roadb_p7", "tier": "keeper",
        "seed": 1337, "inputs": inputs,
        "task": {
            "kind": "paired_claims",
            "scope": "roadb_resolution",
            "n_boot": 10000,
        },
    }
    endpoints = [p for p in pairs if p["recorded"]["is_endpoint"]]
    return (
        "# ROAD B PHASE 7 — PLAN 4.3 CONDITION 1 OVER THE RESOLUTION "
        "AXIS\n"
        "#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from\n"
        "# roadb.paired_claim_pairs().\n"
        "#\n"
        "# **THIS RUN FITS NOTHING.** Every vector it reads was written "
        "by an\n"
        "# arm run that already happened -- no GPU, no re-extraction, no "
        "new\n"
        "# seeds. It is the SAME task, BCa and loader Road A's scopes "
        "use\n"
        "# (task_paired_claims, phase7b.paired_comparison); only the "
        "pair\n"
        "# enumeration is Road B's, and it is derived from the arms.\n"
        "#\n"
        "# **WHY THIS AND NOT MORE SEEDS** (roadb.PHASE_7_SWIN_512): the "
        "seed\n"
        "# thresholds are already met -- Swin-512 clears at 7.2 sigma "
        "and\n"
        "# survives single_run_95. Seed precision is not the binding\n"
        "# uncertainty. What is open is whether the COHORT can tell, "
        "and\n"
        "# only patient-level pairing answers that. Road A's history is "
        "the\n"
        "# reason to expect it to bite: the same criterion withdrew all "
        "nine\n"
        "# of Phase 7C's verdicts, 0 of 45 intervals excluding zero\n"
        "# (phase7c.PAIRED_BCA_WITHDREW_EVERY_VERDICT), and a 3.62x\n"
        "# condition-2 margin failed it.\n"
        "#\n"
        f"# **SCOPE: every resolution contrast among arms that have run** "
        f"--\n"
        f"# {len(pairs)} pairs ({len(endpoints)} of them the 224->768 "
        "endpoints,\n"
        "# the rest interior), over "
        f"{len(stems)} run directories and {len(vectors)} vectors.\n"
        "# Uniform BY CONSTRUCTION: running it only on the interesting "
        "cell\n"
        "# would re-introduce the selection it defends against\n"
        "# (roadb.PAIRED_CLAIM_COVERAGE). The init contrasts are "
        "excluded --\n"
        "# they are descriptive and carry no claims to withdraw.\n"
        "#\n"
        "# Seed bands are NOT uniform (transformer 5, graph 10), so the "
        "run\n"
        "# walks seed GROUPS and refuses a short band -- condition 1 is "
        "a\n"
        "# universal over the seeds present, so fewer seeds is an EASIER "
        "bar.\n"
        "#\n"
        "# **Every stem is its OWN arm's run directory.** Two cells also "
        "have a\n"
        "# duplicate run (srgnn masked 512 ran as the band sweep too; swin\n"
        "# masked 224 has Road A's Stage C run), and neither duplicate is\n"
        "# declared -- each arm's own run keeps every family's points at "
        "ONE\n"
        "# code SHA (roadb.PAIRED_CLAIM_DUPLICATE_RUNS). The duplicates "
        "are a\n"
        "# free head-fit determinism check if anyone wants one.\n"
        + (
            "#\n"
            f"# **ALL {unresolved} VECTOR HASHES BELOW ARE ALL-ZERO "
            "PLACEHOLDERS,\n"
            "# and the paths are PENDING run directories.** Fill both "
            "from the\n"
            "# arm run records (scripts/declare_inputs.py discovers this "
            "config\n"
            "# once the paths are real). Guard 3 refuses until then -- "
            "the\n"
            "# placeholder working rather than a mistake.\n"
            if unresolved and pending_paths else
            "#\n"
            f"# **PATHS RESOLVED; ALL {unresolved} HASHES ARE STILL "
            "PLACEHOLDERS.**\n"
            "# The run directories came from the run listing "
            "(2026-08-12); the\n"
            "# declare pass fills the hashes now that the paths are "
            "real. Guard 3\n"
            "# refuses until then -- the placeholder working.\n"
            "#\n"
            "# Each stem is its OWN arm's run directory. Two cells also "
            "have a\n"
            "# duplicate run elsewhere (the sweep for srgnn masked 512, "
            "Road A's\n"
            "# Stage C for swin masked 224) and neither is declared "
            "here: using\n"
            "# each arm's own run keeps every family's points at ONE "
            "code SHA\n"
            "# (roadb.PAIRED_CLAIM_DUPLICATE_RUNS).\n"
            if unresolved else
            "#\n# **RESOLVED.** Every vector declared at a real path "
            "with a\n# verified hash.\n"
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{PAIRED_STEM}.yaml\"\n\n"
        + yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    )


def regioncrop_paired_config() -> str:
    """PLAN 4.3 condition 1 over Branch 3's contrasts. Fits nothing.

    Only the contrasts whose BOTH arms have run -- graph_vs_concat enters
    when the node path lands, without an edit here.
    """
    from cleft import ladder

    stem = "roadb_p7c_paired_regioncrop"
    pairs = roadb.paired_claim_pairs("roadb_regioncrop")
    vectors = ladder.paired_claim_vectors("roadb_regioncrop", pairs=pairs)
    stems = ladder.paired_claim_stems("roadb_regioncrop", pairs=pairs)
    carried = existing_entries(stem)

    inputs = []
    for arm_stem, seed in vectors:
        name = f"oof_{arm_stem}_seed_{seed}"
        inputs.append(carried.get(name) or {
            "name": name,
            "path": (
                f"{CLUSTER_ROOT}/runs/keeper/roadb_p7c/"
                f"PENDING_{arm_stem}/seed_{seed}__predictions.csv"
            ),
            "rollup_sha256": PLACEHOLDER,
        })
    unresolved = sum(1 for e in inputs if e["rollup_sha256"] == PLACEHOLDER)
    observed = roadb.REGION_CROP_ARMS_OBSERVED

    return (
        "# ROAD B BRANCH 3 — PLAN 4.3 CONDITION 1. THIS IS WHAT DECIDES.\n"
        "#\n"
        "# GENERATED by scripts/generate_roadb_configs.py from\n"
        "# roadb.paired_claim_pairs('roadb_regioncrop').\n#\n"
        "# **THIS RUN FITS NOTHING.** Every vector was written by an arm "
        "that\n"
        "# already ran -- no GPU, no re-extraction, no new seeds. Same "
        "task,\n"
        "# same BCa, same loader as every other scope.\n#\n"
        f"# **SCOPE: {len(pairs)} of 4 contrasts** -- the ones whose BOTH "
        "arms have\n"
        "# run, over "
        f"{len(stems)} run directories and {len(vectors)} vectors.\n"
        "# graph_vs_concat is absent because its arms are blocked on the "
        "node\n"
        "# path (roadb.GRAPH_NODE_PATH_IS_NOT_WIRED); it enters this "
        "config\n"
        "# automatically when they record values.\n#\n"
        "# **What is at stake** (roadb.REGION_CROP_ARMS_OBSERVED, "
        "observed and\n"
        "# NOT yet a result):\n"
        f"#   anatomy {observed['values']['anatomy_concat_vit']['pcc']}  "
        f"whole {observed['values']['control_whole_vit']['pcc']}  "
        f"random {observed['values']['random_concat_vit']['pcc']}\n"
        "#\n"
        "# anatomy-vs-random is +0.077 at 2.6x -- the STRICTLY one-factor\n"
        "# contrast, so a survivor is about ANATOMY rather than about\n"
        "# cropping, which would be this project's first time placement\n"
        "# mattered and the opposite of what Charm (2025) reported.\n#\n"
        "# **Precedent says it may withdraw.** Swin's 3.66x failed "
        "condition 1\n"
        "# at 1 of 5, Road A's two HIGHEST margins failed, and 2.6x is "
        "below\n"
        "# both. Condition 2 does not predict condition 1 -- measured "
        "across\n"
        "# 26 pairs. That is why this runs before anything is written up.\n"
        + (
            "#\n"
            f"# **ALL {unresolved} VECTOR HASHES ARE ALL-ZERO "
            "PLACEHOLDERS** and the\n"
            "# paths are PENDING run directories. Fill both from the arm "
            "run\n"
            "# records; guard 3 refuses until then -- the placeholder "
            "working.\n"
            if unresolved else
            "#\n# **RESOLVED.** Every vector at a real path with a "
            "verified hash.\n"
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{stem}.yaml\"\n\n"
        + yaml.safe_dump({
            "schema_version": 1, "phase": "roadb_p7c", "tier": "keeper",
            "seed": 1337, "inputs": inputs,
            "task": {
                "kind": "paired_claims",
                "scope": "roadb_regioncrop",
                "n_boot": 10000,
            },
        }, sort_keys=False, default_flow_style=False)
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    inputs = shared_inputs()
    emitted = [
        (REPO / "configs" / f"{s['name'].lower()}.yaml", stage_config(s, inputs))
        for s in roadb.staging_settings()
    ]
    emitted.append(
        (REPO / "configs" / "roadb_p2_residual_gate.yaml", gate_config())
    )
    emitted.append(
        (REPO / "configs" / "roadb_p2_sheets.yaml", sheets_config())
    )
    for backbone in ROAD_A_PRETRAIN_COUNTERPARTS:
        for size in sorted(MASKED_ARTIFACTS):
            stem, text = pretrain_config(backbone, size)
            emitted.append((REPO / "configs" / f"{stem}.yaml", text))
    for entry in roadb.phase7_extraction_sets():
        if entry["reuses"]:
            continue  # swin-224-masked: Road A's set, by bitwise identity
        stem, text = extraction_config(entry)
        emitted.append((REPO / "configs" / f"{stem}.yaml", text))
        if (entry["backbone"], entry["resolution"], entry["init"]) == (
            "vit_b16", 512, "imagenet"
        ):
            stem, text = extraction_config(entry, detcheck=True)
            emitted.append((REPO / "configs" / f"{stem}.yaml", text))
    # The sweep first -- it precedes the arms and its reading gates the
    # graph ones -- then the 24 arms from roadb.phase7_arms().
    emitted.append((REPO / "configs" / f"{SWEEP_STEM}.yaml", sweep_config()))
    for arm in roadb.phase7_arms():
        stem, text = arm_config(arm)
        emitted.append((REPO / "configs" / f"{stem}.yaml", text))
    # Condition 1 over the resolution axis -- reads the arms' outputs,
    # fits nothing, so it comes last.
    emitted.append((REPO / "configs" / f"{PAIRED_STEM}.yaml", paired_config()))
    emitted.append((
        REPO / "configs" / "roadb_p7c_paired_regioncrop.yaml",
        regioncrop_paired_config(),
    ))
    # Branch 3: the corrected control only. The crop arms wait on the
    # crop-extraction build (REGION_CROP_STRUCTURE.the_real_build_cost).
    for stem, text in regioncrop_control_configs():
        emitted.append((REPO / "configs" / f"{stem}.yaml", text))

    drifted, written = [], 0
    for path, text in emitted:
        if args.check:
            if not path.is_file():
                drifted.append(f"{path.name}: missing")
            elif path.read_text(encoding="utf-8") != text:
                drifted.append(f"{path.name}: differs from the derived setting")
        else:
            path.write_text(text, encoding="utf-8")
            written += 1

    if args.check:
        for line in drifted:
            print(f"  DRIFT {line}")
        print(f"{len(emitted)} configs checked, {len(drifted)} drifted")
        return 1 if drifted else 0

    print(
        f"wrote {written} configs -- {len(roadb.staging_settings())} staging "
        "settings, the residual gate, the sheets, the twelve Phase 6 "
        "pretraining cells, the 23+1 Phase 7 extractions, the graph seed "
        "band sweep, and the 24 Phase 7 arms"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
