"""Write the Phase 10 config from ``cleft.phase10`` and the shipped inputs.

    PYTHONPATH=src python scripts/generate_phase10_configs.py [--check]

One config: the CleftGNN replication run. Inputs are CARRIED -- manifest
and staged from arm A's shipped config, the primary score sheet from
Phase 1's (its ``Median`` column IS the training label; corrected
2026-08-17 -- ``phase10.CONSENSUS_LABEL_IS_THE_MEDIAN``). The
registration is NOT here: the region set (notebook-36), the
SABM form, the calibrated CE init, both output readings, and every caveat
live in ``cleft.phase10`` where the suite checks them; the recipe knobs
below are written down because scientific knobs are never defaulted.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

from cleft import phase10  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"

SOURCE_CONFIG = "p7_d1_vit_b16_imagenet_g1.yaml"
P1_CONFIG = "p1_build_manifest.yaml"


def source(name: str) -> dict:
    return yaml.safe_load((REPO / "configs" / name).read_text(encoding="utf-8"))


def render_cleftgnn() -> str:
    arm = source(SOURCE_CONFIG)
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    p1 = {e["name"]: e for e in source(P1_CONFIG)["inputs"]}
    built = phase10.CLEFTGNN_BUILT
    payload = {
        "schema_version": 1,
        "phase": "p10",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        "inputs": [
            dict(inputs_by_name["manifest_v1"]),
            dict(inputs_by_name["staged_v1"]),
            dict(p1["scoresheet_primary"]),
        ],
        "task": {
            "kind": "cleftgnn_cv",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "scoresheet_artifact": "scoresheet_primary",
            "geometry": arm["task"]["geometry"],
            "label": arm["task"]["label"],
            "seeds": arm["task"]["seeds"],
            "inner_val_frac": 0.2,
            "max_epochs": 40,
            "patience": 5,
            "monitor": "inner_val_mse",
            "learning_rate": 0.01,
            "momentum": 0.0,
            "batch_size": 16,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 10 — THE CleftGNN REPLICATION UNDER THIS PROJECT'S\n"
        "# CRITERION. TRAIN AS THEY TRAINED, EVALUATE AS WE EVALUATE.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase10_configs.py from\n"
        f"# cleft.phase10, {SOURCE_CONFIG} (manifest/staged/seeds) and\n"
        f"# {P1_CONFIG} (the score sheet). FULLY DECLARED -- every hash is\n"
        "# a verified entry, carried.\n"
        "#\n"
        "# **THE REGISTRATION IS NOT HERE** (phase10.PHASE_10_REGISTERED +\n"
        "# PHASE_10_UNBLOCKED + CLEFTGNN_BUILT): notebook-36 regions (the\n"
        "# maintainer's re-decision on the measured facts; Thursday-flagged\n"
        "# finding); SABM eqs 7-9 with m_i = y_center/224 committed blind;\n"
        "# ResNet-50 ImageNet, backbone FROZEN [FIDELITY CORRECTION\n"
        "# 2026-08-17, phase10.BACKBONE_IS_FROZEN: the full fine-tune was\n"
        "# an inference from 'ResNet-50 backbone', not their recipe; the\n"
        "# notebook freezes its backbone and lr 0.01 belongs to that\n"
        "# regime -- and it makes the contrast against 0.2520\n"
        "# LIKE-FOR-LIKE, frozen backbone + trained head on both sides];\n"
        "# calibrated CE init with LAPLACE smoothing (count+1)/(N+K)\n"
        "# [phase10.THIN_CLASS_SMOOTHING]; BOTH\n"
        "# output readings (expected-value primary, Top-1 beside), neither\n"
        "# selected after the fact.\n"
        "#\n"
        "# **THE RECIPE, literal**: cross-entropy on the group's\n"
        "# consensus grade, which is the score sheet's OWN Median\n"
        "# column -- read by scoresheet.load_median and VERIFIED row by\n"
        "# row against the recomputed median of the five rater cells,\n"
        "# any disagreement fatal. [CORRECTED 2026-08-17: the mode\n"
        "# reading AND the premise that a consensus column exists are\n"
        "# both refuted by measurement -- the sheet holds RanaPhotoID,\n"
        "# five raters, Average, Median. phase10.CONSENSUS_LABEL_IS_THE\n"
        "# _MEDIAN.] Its learnability is 0.5708 on the 237 -- measured\n"
        "# LESS learnable than the mean's 0.6022, which travels with\n"
        "# the result. Plain SGD lr 0.01,\n"
        "# momentum 0 (the literal reading -- the caveat travels); batch 16\n"
        "# (the standing cleft default; the notebook states none). The ONE\n"
        "# deliberate divergence: inner-val early stopping (0.2/40/5,\n"
        "# monitor inner_val_mse on expected-value vs consensus) -- the\n"
        "# paper states no epoch budget anywhere (measured), and fixed\n"
        "# budgets measured post-collapse endpoints on this cohort (peaks\n"
        "# at epochs 2-11).\n"
        "#\n"
        "# Per-seed OOF expected-value CSVs land in the baseline's exact\n"
        "# layout, so the standing paired-BCa tooling consumes them against\n"
        "# the 0.2520 arm's; the paired config follows this run's\n"
        "# directory. Comparability caveats are stamped into metrics.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p10_cleftgnn.yaml\"\n\n"
    ) + body



def render_cleftgnn_notebook() -> str:
    """The NOTEBOOK-recipe cell, beside the manuscript-recipe one.

    Same three inputs, same carried hashes, same evaluation block -- the
    task differs in exactly four keys (``recipe``, ``optimizer``,
    ``learning_rate``, and the absence of ``momentum``, which Adam does
    not have). Building it from the same source configs is what makes
    "the evaluation criterion unchanged" true by construction rather than
    by inspection.
    """
    arm = source(SOURCE_CONFIG)
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    p1 = {e["name"]: e for e in source(P1_CONFIG)["inputs"]}
    payload = {
        "schema_version": 1,
        "phase": "p10",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        "inputs": [
            dict(inputs_by_name["manifest_v1"]),
            dict(inputs_by_name["staged_v1"]),
            dict(p1["scoresheet_primary"]),
        ],
        "task": {
            "kind": "cleftgnn_cv",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "scoresheet_artifact": "scoresheet_primary",
            "geometry": arm["task"]["geometry"],
            "label": arm["task"]["label"],
            "seeds": arm["task"]["seeds"],
            "recipe": "notebook",
            "inner_val_frac": 0.2,
            "max_epochs": 40,
            "patience": 5,
            "monitor": "inner_val_mse",
            "optimizer": "adam",
            "learning_rate": 0.001,
            "batch_size": 16,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 10 — THE NOTEBOOK-RECIPE CELL. THE SAME ARCHITECTURE\n"
        "# FAMILY UNDER THE GROUP'S *OTHER* ARTIFACT -- the only one of\n"
        "# theirs that executes. phase10.NOTEBOOK_RECIPE_CELL_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase10_configs.py from the same\n"
        f"# {SOURCE_CONFIG} and {P1_CONFIG} as p10_cleftgnn.yaml, so 'the\n"
        "# evaluation criterion is unchanged' is true BY CONSTRUCTION.\n"
        "# FULLY DECLARED -- the three hashes are carried, none new.\n"
        "#\n"
        "# **p10_cleftgnn.yaml IS UNTOUCHED.** Its registration, recipe,\n"
        "# numbers and record all stand. This is a SECOND cell.\n"
        "#\n"
        "# **THE FOUR DIFFERENCES, every one verified in the notebook's\n"
        "# own source**: (1) Adam at lr 0.001, torch-default betas/eps, no\n"
        "# weight decay -- cell 9's optim.Adam(trainable_params, lr=LR),\n"
        "# against the manuscript's SGD 0.01; (2) MULTIPLICATIVE fusion\n"
        "# f_t + f_t*v, the notebook's literal expression, against eq\n"
        "# (9)'s additive sum; (3) a frozen ViT-B/16 read through the\n"
        "# notebook's own extraction path, including its omission of the\n"
        "# final model.norm, against ResNet-50; (4) their attention head\n"
        "# -- a learned acm_w_beta softmax over regions plus a closing\n"
        "# sigmoid -- against SABM's fixed vertical mask. Batch 16 is NOT\n"
        "# a difference: both artifacts state it.\n"
        "#\n"
        "# **AND NEITHER LayerNorm.** Both of ours were measured repairs\n"
        "# for the additive path; the notebook normalises nowhere, and\n"
        "# carrying ours would make a spanning result unreadable. With v\n"
        "# in (0,1) the multiplicative fused feature is LARGER than the\n"
        "# additive one that broke SGD -- so this cell is harder, not\n"
        "# easier, and whether Adam absorbs that scale is the hypothesis\n"
        "# under test rather than an assumption it rests on.\n"
        "#\n"
        "# **ITS OWN THREE DEVIATIONS** (phase10.NOTEBOOK_CELL_DEVIATIONS),\n"
        "# against the NOTEBOOK: this project's early stopping (0.2/40/5)\n"
        "# instead of the notebook's fixed EPOCHS = 5 -- defect-cited, and\n"
        "# the ONE deviation this cell shares with the manuscript cell;\n"
        "# this project's normalisation instead of the notebook's CIFAR-10\n"
        "# statistics under an ImageNet-pretrained ViT, which is a DEFECT\n"
        "# rather than a recipe choice; and the Laplace-biased classifier\n"
        "# bias held constant across both cells so the difference between\n"
        "# them is the group's four and not ours as well.\n"
        "#\n"
        "# **FOUR OUTCOMES ARE COMMITTED BEFORE THE RUN**, including\n"
        "# divergence -- which would be RECORDED, NOT REPAIRED.\n"
        "#\n"
        "# **THE SCOPE CAVEAT TRAVELS WITH EVERY NUMBER**: the notebook's\n"
        "# recipe is demonstrated on CIFAR-10. This tests 'their\n"
        "# executable recipe on our data', NOT 'the recipe that produced\n"
        "# their cleft numbers', which we have never seen.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p10_cleftgnn_notebook.yaml\"\n\n"
    ) + body


#: The 25-set, declared BY ROLE. The literal path named the holding
#: institution and one of the two national studies in its parents;
#: the value now comes from the environment on the cluster and the
#: declared rollup_sha256 verifies whatever resolved.
DEALL_SET_PATH = "${CLEFT_ANCHOR_SET}"


def _carried(config_name: str, input_name: str, path: str) -> str:
    """A verified hash carried from a shipped config while its path still
    matches -- the standing two-pass carry."""
    shipped = REPO / "configs" / config_name
    if not shipped.is_file():
        return "0" * 64
    payload = yaml.safe_load(shipped.read_text(encoding="utf-8"))
    for entry in payload.get("inputs") or []:
        if entry.get("name") == input_name and entry.get("path") == path:
            rollup = str(entry.get("rollup_sha256") or "")
            if len(rollup) == 64 and set(rollup) != {"0"}:
                return rollup
    return "0" * 64


def render_faithful() -> str:
    arm = source(SOURCE_CONFIG)
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    p1 = {e["name"]: e for e in source(P1_CONFIG)["inputs"]}
    spec = phase10.FAITHFUL_ARM_REGISTERED
    payload = {
        "schema_version": 1,
        "phase": "p10",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        "inputs": [
            dict(inputs_by_name["manifest_v1"]),
            dict(inputs_by_name["staged_v1"]),
            dict(p1["scoresheet_primary"]),
            {
                "name": "deall_set",
                "path": DEALL_SET_PATH,
                "rollup_sha256": _carried(
                    "p9_deall_reference.yaml", "deall_set", DEALL_SET_PATH
                ),
            },
        ],
        "task": {
            "kind": "cleftgnn_faithful",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "scoresheet_artifact": "scoresheet_primary",
            "deall_artifact": "deall_set",
            "geometry": arm["task"]["geometry"],
            "label": arm["task"]["label"],
            "inner_val_frac": 0.2,
            "max_epochs": 40,
            "patience": 5,
            "learning_rate": 0.01,
            "momentum": 0.0,
            "batch_size": 16,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 10 — THE FAITHFUL ARM: CleftGNN UNDER *THEIR* PROTOCOL.\n"
        "# The cell BESIDE p10_cleftgnn, which runs the same architecture\n"
        "# under OURS. The two differ ONLY in protocol, so any gap between\n"
        "# them is attributable to PROTOCOL rather than architecture --\n"
        "# which is the direct answer to 'why are we at 0.252 while they\n"
        "# reach 0.598'. phase10.FAITHFUL_ARM_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase10_configs.py. FULLY\n"
        "# DECLARED -- every hash is a verified entry, carried.\n"
        "#\n"
        "# **THEIR PROTOCOL, as our cohort allows**: rater-specific models\n"
        "# (one per rater, FIVE models, each trained on that rater's own\n"
        "# grades); an 85:15 stratified split, seeded; their metrics --\n"
        "# Top-1 macro precision, recall, F1 and PCC; a SINGLE run with NO\n"
        "# intervals, which is their form and is recorded rather than\n"
        "# repaired. Evaluated on BOTH their test-set shapes: the held-out\n"
        "# 15% (their Study Test Set shape) and the 25-image benchmark\n"
        "# against Score (their Benchmark shape -- the same 25 images).\n"
        "#\n"
        "# **NOTHING HERE IS CLAIMABLE** under this project's criterion,\n"
        "# by construction: one run, no intervals. That is the point of\n"
        "# the cell.\n"
        "#\n"
        "# The arithmetic on their 0.598, carried in the record: one of\n"
        "# FIFTEEN cells, n=25, no published interval, Fisher ~[0.27,\n"
        "# 0.80]; and the same rater-E model scored 0.283 on their n=28\n"
        "# Study set -- a doubling between two test sets of one task, the\n"
        "# signature of sampling noise.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p10_cleftgnn_faithful.yaml\"\n\n"
    ) + body


def render_rater_screen() -> str:
    arm = source(SOURCE_CONFIG)
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    p1 = {e["name"]: e for e in source(P1_CONFIG)["inputs"]}
    spec = phase10.RATER_SCREEN_REGISTERED
    payload = {
        "schema_version": 1,
        "phase": "p10",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        "inputs": [
            dict(inputs_by_name["manifest_v1"]),
            dict(inputs_by_name["staged_v1"]),
            dict(inputs_by_name["embeddings"]),
            dict(p1["scoresheet_primary"]),
        ],
        "task": {
            "kind": "rater_screen",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "embeddings_artifact": "embeddings",
            "scoresheet_artifact": "scoresheet_primary",
            "geometry": arm["task"]["geometry"],
            "label": arm["task"]["label"],
            "seeds": arm["task"]["seeds"],
            "inner_val_frac": arm["task"]["inner_val_frac"],
            "max_epochs": arm["task"]["max_epochs"],
            "patience": arm["task"]["patience"],
            "monitor": arm["task"]["monitor"],
            "learning_rate": arm["task"]["learning_rate"],
            "weight_decay": arm["task"]["weight_decay"],
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 10 — THE RATER-SPECIFIC SCREEN: the 0.2520 arm, refit\n"
        "# once per rater. phase10.RATER_SCREEN_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase10_configs.py; the refit\n"
        f"# block is COPIED from {SOURCE_CONFIG} so 'the same arm' is true\n"
        "# by construction. FULLY DECLARED -- every hash carried.\n"
        "#\n"
        "# **THE PRIOR IS COMMITTED BOTH WAYS, BEFORE ANY NUMBER**: Phase 1\n"
        "# learnability puts the panel mean at 0.6022 and the single-rater\n"
        "# orthodontist at 0.4944, and averaging five raters cancels noise\n"
        "# a single rater carries -- so the registered prediction is that\n"
        "# EVERY rater-specific cell lands BELOW 0.2520.\n"
        "#   * all five below -> rater-specific modelling measured WORSE on\n"
        "#     this cohort: a direct, intervalled test of the literature's\n"
        "#     central premise;\n"
        "#   * any cell beyond the arm's own seed band (sd 0.0148) -> the\n"
        "#     prior is REFUTED and the full rater ladder (5 x 4 x 2 x 2 x\n"
        "#     5 = 400 runs, phase10.RATER_LADDER_CONDITIONAL) is\n"
        "#     justified immediately.\n"
        "#\n"
        "# Cheap: the arm is frozen-backbone, so only the head refits, on\n"
        "# embeddings already extracted and declared. Each rater is a\n"
        "# DIFFERENT target, so these are not paired against the 0.2520\n"
        "# arm's vectors -- the reading is the registered one, level\n"
        "# against the arm and its seed band.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p10_rater_screen.yaml\"\n\n"
    ) + body


PAIRED_NAME = "p10_paired.yaml"
PLACEHOLDER = "0" * 64


def _carried_vectors() -> dict:
    """Entries ``p10_paired.yaml`` has already resolved, by name.

    Three-state, the standing shape: a resolved PATH is carried even when
    its hash is still a placeholder, because the two resolve in separate
    passes and the path is the half that cannot be re-derived here. A
    PENDING path is never carried -- it IS the re-derivable state.
    """
    path = REPO / "configs" / PAIRED_NAME
    if not path.is_file():
        return {}
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {
        entry["name"]: entry
        for entry in payload.get("inputs") or []
        if "/PENDING_" not in entry["path"]
    }


def _known_hashes() -> dict:
    """Every prediction vector any shipped config already declares, by
    path. A path's contents are immutable, so one verified hash serves
    every config declaring it -- which is what makes the 0.2520 arm's
    five vectors need no cluster round trip at all."""
    known: dict[str, str] = {}
    for path in sorted((REPO / "configs").glob("*.yaml")):
        payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for entry in payload.get("inputs") or []:
            rollup = entry.get("rollup_sha256") or ""
            if (
                len(rollup) == 64 and set(rollup) != {"0"}
                and entry["path"].endswith("__predictions.csv")
            ):
                known.setdefault(entry["path"], rollup)
    return known


def render_paired() -> str:
    """PLAN 4.3 condition 1 for the replication against the 0.2520 arm.

    Same task, same BCa, same loader as Road A's and Road B's scopes --
    only the pair enumeration differs, and it is derived in
    ``phase10.paired_claim_pairs``. The Road B precedent, applied rather
    than re-implemented.
    """
    from cleft import ladder

    pairs = phase10.paired_claim_pairs("p10")
    vectors = ladder.paired_claim_vectors("p10", pairs=pairs)
    stems = ladder.paired_claim_stems("p10", pairs=pairs)
    carried = _carried_vectors()
    known = _known_hashes()
    # A stem another config already resolved: reuse its run directory's
    # full prefix so the path matches byte for byte and the hash carries.
    resolved_prefix = {}
    for path in known:
        directory = path.rpartition("/")[0]
        run_dir = directory.rpartition("/")[2]
        resolved_prefix.setdefault(run_dir.split("__")[0], directory)

    inputs = []
    for stem, seed in vectors:
        name = f"oof_{stem}_seed_{seed}"
        if name in carried:
            inputs.append(carried[name])
            continue
        if stem in resolved_prefix:
            path = f"{resolved_prefix[stem]}/seed_{seed}__predictions.csv"
        else:
            # PENDING, not a glob: a glob wears the run-directory SHAPE
            # the mistyped-launch sweep checks, and would be rejected as a
            # sha. PENDING_<stem> has no `__` and stays outside it.
            path = (
                f"{CLUSTER_ROOT}/runs/keeper/p10/PENDING_{stem}/"
                f"seed_{seed}__predictions.csv"
            )
        inputs.append({
            "name": name, "path": path,
            "rollup_sha256": known.get(path, PLACEHOLDER),
        })

    unresolved = sum(1 for e in inputs if e["rollup_sha256"] == PLACEHOLDER)
    pending = sum(1 for e in inputs if "/PENDING_" in e["path"])
    spec = phase10.PHASE_10_PAIRED_REGISTERED
    recorded = pairs[0]["recorded"]
    if pending:
        provenance = (
            f"# **{unresolved} HASHES ARE ALL-ZERO PLACEHOLDERS and "
            f"{pending} paths\n"
            "# are PENDING_<stem>.** A run directory carries a SHA and a job\n"
            "# id, neither derivable on a laptop -- and a glob would wear the\n"
            "# run-directory shape the mistyped-launch sweep checks, so the\n"
            "# pending form stays outside it. Two passes: paste the run\n"
            "# directory from the listing (path), then declare_inputs.py\n"
            "# (hash). Guard 3 refuses the run until both are real -- the\n"
            "# placeholder working, not a mistake.\n"
        )
    elif unresolved:
        provenance = (
            "# **PATHS RESOLVED, HASHES PENDING.** Every path is a real run\n"
            f"# directory; the {unresolved} remaining hashes are all-zero\n"
            "# placeholders until declare_inputs.py verifies the files.\n"
        )
    else:
        provenance = (
            f"# **RESOLVED.** All {len(inputs)} vectors declared at real\n"
            "# paths with verified hashes. Guard 3 checks every one before a\n"
            "# row is read.\n"
        )

    payload = {
        "schema_version": 1,
        "phase": "p10",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": {"kind": "paired_claims", "scope": "p10", "n_boot": 10000},
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 10 — PLAN §4.3 CONDITION 1: THE REPLICATION AGAINST THE\n"
        "# 0.2520 ARM. The phase's FOURTH EXIT CRITERION and its LAST\n"
        "# OUTSTANDING RUN. phase10.PHASE_10_PAIRED_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase10_configs.py from\n"
        "# phase10.paired_claim_pairs('p10').\n"
        "#\n"
        "# **THIS RUN FITS NOTHING.** Every vector it reads was written by\n"
        "# a keeper run that already happened. No GPU, no training, no\n"
        "# re-extraction.\n"
        "#\n"
        f"# **SCOPE: p10.** One pair over {len(stems)} run directories,\n"
        f"# {len(inputs)} vectors, the five shared seeds. Same task, same\n"
        "# BCa, same loader as Road A's and Road B's scopes -- only the\n"
        "# PAIR ENUMERATION differs, and it lives in phase10 because that\n"
        "# phase's structure is its own file's business. A second paired\n"
        "# implementation is the duplication R10 forbids; a scope is not.\n"
        "#\n"
        "# **THE PREDICTION IS REGISTERED, WITH ITS CAUSE**: delta\n"
        f"# {recorded['delta_of_means']}, threshold {recorded['threshold']},\n"
        f"# margin {recorded['margin']}x -- DERIVED from ROUTE_3_OBSERVED and\n"
        "# ladder.STAGE_D1_AT_G1 (the D1 ARTIFACT path, which is what the\n"
        "# declared vectors are -- the live 0.25206/0.01483 would record\n"
        "# 0.2280 for vectors that produced 0.2279) through the frozen\n"
        "# combined_claimable_delta, never typed. That margin lands INSIDE\n"
        "# the mixed region 3.6x-4.7x (3.83x passed; 4.34x and 4.69x\n"
        "# failed), so the margin does NOT order it and condition 1\n"
        "# decides. The cause of so small a margin for so large a delta:\n"
        "# the replication's seed SD is 0.0676 against the baseline's\n"
        "# 0.0148 -- 4.6x -- and the threshold is driven by the noisier\n"
        "# arm. AN UNSTABLE ARM IS HARD TO BEAT CLAIMABLY EVEN WHEN FAR\n"
        "# BEHIND.\n"
        "#\n"
        "# **BOTH READINGS ARE COMMITTED BEFORE THE RUN.** Claimable ->\n"
        "# the 0.2520 arm is claimably ahead UNDER THIS PROTOCOL, which is\n"
        "# a statement about our protocol's outcome and NOT architectural\n"
        "# superiority, since the loser does not span the label range. Not\n"
        "# claimable -> Phase 10 cannot claim even that, and closes on the\n"
        "# comparison being unresolvable at this cohort's resolution -- a\n"
        "# fourth independent arrival at COHORT_CANNOT_RESOLVE.\n"
        "#\n"
        "# The notebook cell is NOT here and has no vectors: it was refused\n"
        "# entry at gate 3 and yields a finding, not a number\n"
        "# (phase10.PAIRED_CLAIM_COVERAGE).\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{PAIRED_NAME}\"\n\n"
    ) + body


CONFIGS = {
    "p10_cleftgnn.yaml": render_cleftgnn,
    PAIRED_NAME: render_paired,
    "p10_cleftgnn_notebook.yaml": render_cleftgnn_notebook,
    "p10_cleftgnn_faithful.yaml": render_faithful,
    "p10_rater_screen.yaml": render_rater_screen,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    print(
        f"cleftgnn inputs carried from {SOURCE_CONFIG} and {P1_CONFIG}; "
        "recipe per phase10.PHASE_10_UNBLOCKED"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
