"""Write the record-versus-artifact check config.

    PYTHONPATH=src python scripts/generate_record_audit_configs.py [--check]

One config. Its inputs are CARRIED from ``configs/p18_metric_space.yaml``
-- the same 68 run directories, same verified hashes, byte for byte --
because the check reads exactly the artifacts Phase 18 read. No hash is
new here.

**No banked value appears in the config.** The arms carry only identity,
seeds, CSV stem and row count; the task takes each arm's banked PCC from
``cleft.record_audit.banked_arm_pcc()`` at run time. Putting the figures
in the config would turn a record-versus-artifact check into a
document-versus-artifact one, which is the thing it exists to avoid.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

from cleft import record_audit  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"
SOURCE_CONFIG = "p18_metric_space.yaml"
NAME = "record_artifact_check.yaml"


def source(name: str) -> dict:
    return yaml.safe_load((REPO / "configs" / name).read_text(encoding="utf-8"))


def render() -> str:
    p18 = source(SOURCE_CONFIG)
    arms = [
        {
            "name": arm["name"],
            "input": arm["input"],
            "seeds": list(arm["seeds"]),
            "csv": arm["csv"],
            "n_patients": arm["n_patients"],
        }
        for arm in p18["task"]["arms"]
    ]
    payload = {
        "schema_version": 1,
        "phase": "audit",
        "tier": "keeper",
        "seed": p18["seed"],
        "inputs": [dict(entry) for entry in p18["inputs"]],
        "task": {
            "kind": "record_artifact_check",
            "manifest_artifact": p18["task"]["manifest_artifact"],
            "arms": arms,
            "threshold": record_audit.AGREEMENT_THRESHOLD,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    gaps = record_audit.BANKED_VALUE_GAPS
    coverage = (
        f"# ALL 68 ARMS COVERED. The gap that existed on 2026-08-31 --\n"
        f"# five arms whose PCCs lived only in prose -- closed the same\n"
        f"# day (record_audit.BANKED_VALUE_GAPS_CLOSED).\n"
        if not gaps else
        f"# NOT COVERED ({len(gaps)} of 68): {', '.join(gaps)}\n"
        "# -- their PCCs exist only in prose, so no machine-readable\n"
        "# banked value exists to compare against. Named, never silently\n"
        "# dropped (record_audit.BANKED_VALUE_GAP_REASONS).\n"
    )
    return (
        "# RECORD-VERSUS-ARTIFACT AGREEMENT — THE STANDING CHECK.\n"
        "#\n"
        "# Does every arm's PCC as WRITTEN IN THE RECORDS still equal the\n"
        "# PCC recomputed from that arm's own prediction CSVs?\n"
        "# record_audit.STANDING_CHECK_DESIGN.\n"
        "#\n"
        "# GENERATED by scripts/generate_record_audit_configs.py. Inputs\n"
        f"# CARRIED from {SOURCE_CONFIG} -- the same run directories and\n"
        "# the same verified hashes, byte for byte. No hash is new here.\n"
        "#\n"
        "# **NO BANKED VALUE APPEARS BELOW.** The arms carry identity,\n"
        "# seeds, CSV stem and row count only; the task reads each arm's\n"
        "# banked PCC from the RECORDS at run time\n"
        "# (record_audit.banked_arm_pcc). Putting the figures here would\n"
        "# make this a document-versus-artifact check, which is exactly\n"
        "# what it exists to avoid.\n"
        "#\n"
        "# It reuses cluster_csv.read_cluster_csv and the frozen\n"
        "# eval.metrics.pcc -- the same reader and metric Phase 18 used --\n"
        "# and does not touch the Phase 18 task, whose run 5 is citable\n"
        "# and whose exit criteria are locked.\n"
        "#\n"
        "# A mismatch is REPORTED, not raised: the deliverable is a table\n"
        "# of deltas to rule on, and dying on the first disagreement\n"
        "# would hide the rest.\n"
        "#\n"
        + coverage +
        "#\n"
        "# Pure CPU arithmetic over already-written CSVs: no training, no\n"
        "# GPU, seconds. CLUSTER-ONLY inputs; metrics.json is SHAREABLE.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{NAME}\"\n\n"
    ) + body


CONFIGS = {NAME: render}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    print(f"inputs carried from {SOURCE_CONFIG}; no banked value in the config")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
