"""Write the Phase 10 ANNEX compute-gate config from the shipped inputs.

    PYTHONPATH=src python scripts/generate_phase10_annex_configs.py [--check]

One config: the compute gate (``phase10_annex.COMPUTE_GATE_DESIGNED``) --
ONE plain-random 153/28 draw, ONE rater, ONE full-trainable ResNet-50
CleftGNN fit under the notebook's recipe and its CIFAR-10 statistics.
Inputs are CARRIED from ``p10_cleftgnn_faithful.yaml``'s verified
entries (manifest, staged, the primary score sheet) -- same name, same
path, same hash, byte for byte; no new hash is invented here. The
registration is NOT here: the rulings, the prohibition, the committed
readings and the floors discipline live in ``cleft.phase10_annex``
where the suite checks them. NO draw-count key exists ON PURPOSE: N is
declared only after this gate's measured cost, by the ruling.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"

SOURCE_CONFIG = "p10_cleftgnn_faithful.yaml"
GATE_NAME = "p10x_gate_fullfit.yaml"

#: The gate's rater: the FIRST of the sheet's five columns, in sheet
#: order -- a rule, not a selection; the maintainer can rule another before
#: launch. All five run only after N is ruled (RULING_A: N x 5 fits).
GATE_RATER = "Rater 7 - Cleft patient"


def source(name: str) -> dict:
    return yaml.safe_load((REPO / "configs" / name).read_text(encoding="utf-8"))


def render_gate() -> str:
    faithful = source(SOURCE_CONFIG)
    inputs_by_name = {e["name"]: e for e in faithful["inputs"]}
    payload = {
        "schema_version": 1,
        "phase": "p10x",
        "tier": "keeper",
        "seed": faithful["seed"],
        "inputs": [
            dict(inputs_by_name["manifest_v1"]),
            dict(inputs_by_name["staged_v1"]),
            dict(inputs_by_name["scoresheet_primary"]),
        ],
        "task": {
            "kind": "p10x_gate_fullfit",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "scoresheet_artifact": "scoresheet_primary",
            "geometry": faithful["task"]["geometry"],
            "label": faithful["task"]["label"],
            "rater": GATE_RATER,
            "split_seed": faithful["seed"],
            "train_size": 153,
            "test_size": 28,
            "region_count": 36,
            "trainable": "full",
            "recipe": {
                "optimizer": "adam",
                "learning_rate": 0.001,
                "batch_size": 16,
                "epochs": 5,
                "loss": "cross_entropy",
                "model_selection": "last_epoch",
            },
            "normalisation": {
                "mean": [0.4914, 0.4822, 0.4465],
                "std": [0.2023, 0.1994, 0.2010],
            },
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 10 ANNEX — THE COMPUTE GATE. ONE 153/28 DRAW, ONE\n"
        "# RATER, ONE FULL FIT. MEASURE BEFORE DECLARING: N is ruled by\n"
        "# the maintainer only after this run's per-fit wall-clock exists\n"
        "# (phase10_annex.COMPUTE_GATE_DESIGNED, the Phase 17 lesson).\n"
        "#\n"
        "# GENERATED by scripts/generate_phase10_annex_configs.py. FULLY\n"
        f"# DECLARED -- all three hashes CARRIED from {SOURCE_CONFIG}'s\n"
        "# verified entries, byte for byte; none new. Re-verify with\n"
        "# declare_inputs.py before launch if anything moved.\n"
        "#\n"
        "# **EVERY KNOB IS PINNED BY SCHEMA to the registered value** --\n"
        "# the gate exists to measure cost, not to admit variants:\n"
        "# 153/28 (their sizes, drawn PLAIN from OUR cohort -- the\n"
        "# 181-analogue is NOT derived; SUPERVISION_28_DEPENDENCY); 36 regions\n"
        "# (what their code ran; 27 is refused BY NAME); trainable FULL\n"
        "# (RULING_B: a scoped departure -- a frozen backbone would\n"
        "# leave 'we froze it' as a permanent alternative explanation);\n"
        "# Adam 0.001, batch 16, EPOCHS = 5, cross-entropy, last epoch\n"
        "# IS the model (NOTEBOOK_RECIPE_IS_ADAM, cell 9 -- the\n"
        "# manuscript's SGD 0.01 is UNREGISTERED); the notebook's\n"
        "# CIFAR-10 statistics (NORMALISATION_RULED: a deliberately\n"
        "# replicated defect, replicated KNOWINGLY, never 'a recipe').\n"
        "#\n"
        "# **The rater is the sheet's FIRST column, in sheet order** --\n"
        "# a rule, not a selection; a sheet identity, UNMATCHED to\n"
        "# their A-E (RATER_PANEL_DISCREPANCY_EIGHTH). All five raters\n"
        "# run only after N is ruled (RULING_A: N x 5 fits).\n"
        "#\n"
        "# **NOTHING HERE IS CLAIMABLE**: one draw by construction. A\n"
        "# degenerate draw (test side missing a grade) is REPORTED,\n"
        "# never discarded or redrawn. CLUSTER-ONLY throughout --\n"
        "# patient images; the pinned image, per the standing keeper\n"
        "# discipline.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{GATE_NAME}\"\n\n"
    ) + body


DISTRIBUTION_NAME = "p10x_distribution.yaml"

#: N, ruled 2026-08-31 after the gate's measured cost
#: (``phase10_annex.N_RULED``). 500 draws x 5 raters = 2,500 fits.
N_DRAWS = 500

#: One job. 2,500 fits at the gate's measured ~5 s is ~3.5 GPU-hours,
#: which is modest; the shard rule exists in the schema so splitting is
#: a launch decision rather than a rebuild
#: (``DISTRIBUTION_ARM_REGISTERED["compute_shape"]``).
SHIPPED_SHARD = {"count": 1, "index": 0}


def render_distribution() -> str:
    from cleft.data.scoresheet import RATERS
    from cleft.run import p10x_split_seeds

    gate = source(GATE_NAME)
    root_seed = gate["seed"]
    payload = {
        "schema_version": 1,
        "phase": "p10x",
        "tier": "keeper",
        "seed": gate["seed"],
        # CARRIED from the gate's own config -- same three entries,
        # byte for byte, so the arm reads exactly what the gate read.
        "inputs": [dict(entry) for entry in gate["inputs"]],
        "task": {
            "kind": "p10x_distribution",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "scoresheet_artifact": "scoresheet_primary",
            "geometry": gate["task"]["geometry"],
            "label": gate["task"]["label"],
            "raters": list(RATERS),
            "root_seed": root_seed,
            "n_draws": N_DRAWS,
            "split_seeds": p10x_split_seeds(root_seed, N_DRAWS),
            "train_size": gate["task"]["train_size"],
            "test_size": gate["task"]["test_size"],
            "region_count": gate["task"]["region_count"],
            "trainable": gate["task"]["trainable"],
            # The gate's recipe and normalisation, carried rather than
            # restated: the arm runs the fit the gate measured.
            "recipe": dict(gate["task"]["recipe"]),
            "normalisation": {
                key: list(value)
                for key, value in gate["task"]["normalisation"].items()
            },
            "shard": dict(SHIPPED_SHARD),
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 10 ANNEX — THE DISTRIBUTION ARM. 500 DRAWS x 5 RATERS,\n"
        "# 2,500 FITS, THROUGH THE GATE'S OWN FIT PATH.\n"
        "#\n"
        "# The registered question: DOES A SINGLE 153/28 SPLIT IDENTIFY\n"
        "# A MODEL'S PERFORMANCE AT THIS COHORT SIZE? Everything except\n"
        "# the split is fixed to theirs, so what this measures is the\n"
        "# DESIGN (phase10_annex.DISTRIBUTION_ARM_REGISTERED,\n"
        "# EXIT_CRITERIA, locked 2026-08-31).\n"
        "#\n"
        "# GENERATED by scripts/generate_phase10_annex_configs.py from\n"
        f"# {GATE_NAME} -- inputs, recipe and normalisation CARRIED byte\n"
        "# for byte, so the arm reads what the gate read and runs what\n"
        "# the gate measured. FULLY DECLARED; no hash is new here.\n"
        "#\n"
        "# **N = 500, ruled  AFTER the gate's measured cost**\n"
        "# (N_RULED): 2,500 fits at ~5 s = ~3.5 GPU-hours sequential,\n"
        "# an upper bound since a job pays its data load once.\n"
        "#\n"
        "# **THE 500 SEEDS ARE ENUMERATED BELOW, not globbed.** They are\n"
        "# derived from root_seed by the declared rule\n"
        "# (run.P10X_SPLIT_SEED_RULE) and written out so the draw set is\n"
        "# auditable without running anything; the loader RE-DERIVES\n"
        "# them and refuses a list that disagrees with its root.\n"
        "#\n"
        "# **ALL FIVE RATERS, by ruling (a)** -- the across-rater spread\n"
        "# is part of what is characterised. Sheet identities, UNMATCHED\n"
        "# to their A-E (RATER_PANEL_DISCREPANCY_EIGHTH); the caveat\n"
        "# rides on every per-rater figure.\n"
        "#\n"
        "# **Degenerate draws are counted, never discarded**: a test\n"
        "# side missing a grade makes the macro an average over FEWER\n"
        "# classes, so those draws are reported separately as well as\n"
        "# in the all-draws distribution. The gate's own first draw was\n"
        "# degenerate (FIRST_DRAW_DEGENERATE) -- an observation, not the\n"
        "# frequency, which is what these 500 draws measure.\n"
        "#\n"
        "# **ONE JOB as shipped** (shard count 1). The shard rule is\n"
        "# declared rather than improvised: draws where\n"
        "# draw_index %% count == index, so splitting is a launch\n"
        "# decision, not a rebuild. Merging sharded outputs is NOT\n"
        "# BUILT and is needed only if you shard.\n"
        "#\n"
        "# **NOTHING HERE IS CLAIMABLE**: the annex characterises a\n"
        "# DESIGN. No ledger row follows without its own registration.\n"
        "# CLUSTER-ONLY throughout -- patient images; pinned image.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{DISTRIBUTION_NAME}\"\n\n"
    ).replace("%%", "%") + body


CONFIGS = {
    GATE_NAME: render_gate,
    DISTRIBUTION_NAME: render_distribution,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    print(
        f"gate inputs carried from {SOURCE_CONFIG}; the distribution arm "
        f"carries the gate's own, N = {N_DRAWS} (ruled 2026-08-31), "
        f"{N_DRAWS * 5} fits, shipped as one job"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
