"""Emit Phase 27's config from the locked record.

    PYTHONPATH=src python scripts/generate_phase27_configs.py [--check]

Every setting comes from ``cleft.phase27`` or is carried from the probe
config named in ``phase27.THE_SETTINGS_RULED``. Nothing is typed twice,
so the config cannot drift from the lock without ``--check`` saying so.

``--check`` regenerates and compares against what is on disk. It exits
non-zero on any difference and prints the first one, which is how a
hand-edit to a generated config is caught rather than inherited.

**The two rollups this config declares are NOT filled here.** They are
filled from the output of ``scripts/declare_inputs.py`` run on the
cluster, per the standing two-pass rhythm, and the generator refuses to
invent them.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from cleft import phase27  # noqa: E402

CONFIGS = REPO / "configs"
OUT = CONFIGS / "p27_anchor_train.yaml"

#: Carried from the probe, whose task block is the precedent
#: ``phase27.THE_SETTINGS_RULED`` names. Read rather than retyped, so a
#: change to the probe shows up here as drift instead of silence.
PROBE = CONFIGS / "p7_d1_vit_b16_imagenet_g1.yaml"
#: batch_size is deliberately NOT carried: EmbeddingHeadBackbone never
#: reads it, so declaring it would ship a setting with no effect
#: (``phase27.THE_INIT_IS_THE_PROBES``). max_steps is not in the probe's
#: config either, because the probe takes the class default, so it is
#: read from the class rather than from a config that does not carry it.
CARRIED = ("seeds", "learning_rate", "weight_decay", "max_epochs")

#: The anchor artifact, declared at the hash Phase 16 banked. The path is
#: read from the config that already declares it rather than typed.
ANCHOR_SOURCE = CONFIGS / "p16_anchor_loop.yaml"

#: [DERIVED, phase27.THE_LABEL_INCOMPARABILITY_ADDRESSED] The anchor
#: grade mean minus the cohort panel mean. Recomputed here from the
#: banked spread rather than transcribed, so a slip fails loudly.
COHORT_PANEL_MEAN = 2.7544


def _anchor_grade_mean() -> float:
    from cleft import phase16

    grades = [
        grade
        for grade, count in enumerate(phase16.ANCHOR_GRADE_SPREAD, start=1)
        for _ in range(count)
    ]
    if len(grades) != phase27.N_ANCHORS:
        raise SystemExit(
            f"the banked spread gives {len(grades)} anchors, not "
            f"{phase27.N_ANCHORS}"
        )
    return sum(grades) / len(grades)


def _probe_task() -> dict:
    import yaml

    return yaml.safe_load(PROBE.read_text(encoding="utf-8"))["task"]


def _probe_max_steps() -> int:
    """The probe does not set ``max_steps``, so it runs the class default.

    Read from the class rather than typed, so a change there shows up here
    as drift instead of silence. If the probe ever starts declaring it,
    this refuses rather than quietly preferring the class.
    """
    from cleft.train.torch_backbone import EmbeddingHeadBackbone

    if "max_steps" in _probe_task():
        raise SystemExit(
            "the probe config now sets max_steps; carry it from there "
            "instead of reading the class default"
        )
    return int(EmbeddingHeadBackbone.max_steps)


def _declared(config_path: pathlib.Path) -> dict:
    import yaml

    config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    return {entry["name"]: entry for entry in config["inputs"]}


def render() -> str:
    probe = _probe_task()
    missing = [field for field in CARRIED if field not in probe]
    if missing:
        raise SystemExit(f"the probe config no longer carries {missing}")

    anchor = _declared(ANCHOR_SOURCE)["anchor_embeddings"]
    probe_inputs = _declared(PROBE)
    offset = round(_anchor_grade_mean() - COHORT_PANEL_MEAN, 4)

    seeds = "\n".join(f"  - {int(seed)}" for seed in probe["seeds"])
    readouts = "\n".join(f"  - {int(e)}" for e in phase27.READOUT_EPOCHS)

    return (
        "# PHASE 27 -- THE ANCHOR SET AS A TRAINING SET.\n"
        "# phase27.EXIT_CRITERIA, locked 2026-09-06. Fit a linear head\n"
        "# on the 25 anchor GRADES and evaluate on all 237 as pure\n"
        "# test. The first time anything in this record is FIT to the\n"
        "# anchor Score.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase27_configs.py. Every\n"
        "# setting is carried from p7_d1_vit_b16_imagenet_g1.yaml (the\n"
        "# probe) per phase27.THE_SETTINGS_RULED, or comes from the\n"
        "# locked record. Do not hand-edit: --check will fail.\n"
        "#\n"
        "# **THREE FIELDS ARE ABSENT AND THAT IS THE RULING.**\n"
        "# inner_val_frac, monitor and patience are not in this task's\n"
        "# spec at all (phase27.THE_INNER_VALIDATION_RULED): five images\n"
        "# held out of twenty five cannot cover the 3/7/6/6/3 spread,\n"
        "# and a checkpoint selected on five images is close to a\n"
        "# checkpoint selected on noise. So max_epochs is a FIXED\n"
        "# BUDGET, the loop runs all forty, and the phase reads at two\n"
        "# epochs declared in advance.\n"
        "#\n"
        "# **THE TWO SETS ARE DISJOINT AND THE TASK PROVES IT.**\n"
        "# phase27.disjoint_or_raise runs before anything is fitted and\n"
        "# refuses on a shared identifier or a bitwise-identical\n"
        "# feature row (phase27.THE_DISJOINTNESS_GUARD_DESIGNED).\n"
        "#\n"
        "# **RESOLVED.** Every input is CARRIED from a config that\n"
        "# already declares it at a verified hash: the anchor set from\n"
        "# p16_anchor_loop.yaml, the manifest and the embeddings from\n"
        "# the probe. No hash is typed by the generator and none is\n"
        "# new, so this config needs NO new declaration before launch.\n"
        "# To re-verify the three rollups against the cluster anyway:\n"
        "#\n"
        "#   bash -lc \"cd /home/user/codex/cleft-aesthetics && "
        "PYTHONPATH=src \\\\\n"
        "#     python scripts/declare_inputs.py "
        "configs/p27_anchor_train.yaml\"\n"
        "#\n"
        "# and to launch:\n"
        "#\n"
        "#   bash -lc \"cd /home/user/codex/cleft-aesthetics && "
        "PYTHONPATH=src \\\\\n"
        "#     python -m cleft.run --config configs/p27_anchor_train.yaml\"\n"
        "\n"
        "schema_version: 1\n"
        "phase: p27\n"
        "tier: keeper\n"
        "seed: 1337\n"
        "inputs:\n"
        "- name: anchor_embeddings\n"
        f"  path: {anchor['path']}\n"
        f"  rollup_sha256: {anchor['rollup_sha256']}\n"
        "- name: manifest_v1\n"
        f"  path: {probe_inputs['manifest_v1']['path']}\n"
        f"  rollup_sha256: {probe_inputs['manifest_v1']['rollup_sha256']}\n"
        "- name: embeddings\n"
        f"  path: {probe_inputs['embeddings']['path']}\n"
        f"  rollup_sha256: {probe_inputs['embeddings']['rollup_sha256']}\n"
        "task:\n"
        "  kind: p27_anchor_train\n"
        "  arm: p27_anchor_train\n"
        "  anchor_artifact: anchor_embeddings\n"
        "  manifest_artifact: manifest_v1\n"
        "  embeddings_artifact: embeddings\n"
        f"  geometry: {probe['geometry']}\n"
        f"  backbone: {probe['backbone']}\n"
        "  seeds:\n"
        f"{seeds}\n"
        f"  max_epochs: {int(probe['max_epochs'])}\n"
        "  readout_epochs:\n"
        f"{readouts}\n"
        f"  primary_epoch: {int(max(phase27.READOUT_EPOCHS))}\n"
        f"  learning_rate: {probe['learning_rate']}\n"
        f"  weight_decay: {probe['weight_decay']}\n"
        f"  max_steps: {_probe_max_steps()}\n"
        f"  target_offset: {offset}\n"
        f"  expect_anchors: {phase27.N_ANCHORS}\n"
        "  expect_patients: 237\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="compare against what is on disk instead of writing",
    )
    args = parser.parse_args()

    rendered = render()
    if not args.check:
        OUT.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"wrote {OUT.relative_to(REPO).as_posix()}")
        return 0

    if not OUT.is_file():
        print(f"MISSING {OUT.relative_to(REPO).as_posix()}")
        return 1
    on_disk = OUT.read_text(encoding="utf-8")
    if on_disk == rendered:
        print(f"{OUT.relative_to(REPO).as_posix()}: matches the record")
        return 0
    for number, (want, got) in enumerate(
        zip(rendered.split("\n"), on_disk.split("\n")), start=1
    ):
        if want != got:
            print(f"DRIFT at line {number}\n  record: {want!r}\n  disk:   {got!r}")
            return 1
    print("DRIFT: the files differ in length")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
