"""Write Phase 21's two configs from the locked arm list.

    PYTHONPATH=src python scripts/generate_phase21_configs.py [--check]

Two configs, one per arm:

* ``p21_ensemble_probe``     -- Arm A, the ensemble probe
* ``p21_error_consistency``  -- Arm B, error consistency

**The arm list is DERIVED, not written.** ``phase18.locked_arm_entries()``
yields the 68 locked arms; filtering ``n_patients == 237`` yields the 64
that ``phase21.ARM_SET_RULED`` declares, and the four dropped are exactly
the p12 view-ablation group. So the configs cannot drift from the lock,
and **no glob exists anywhere in the arm resolution**.

**NO NEW HASH ENTERS.** Every input is CARRIED VERBATIM -- same name,
path and verified rollup -- from ``p18_metric_space.yaml``, which already
declares all 63 run directories plus the manifest, and from the probe
config for the score sheet. Nothing here computes a hash.

**Every arm contributes the SHARED FIVE SEEDS**, including the thirty
that have ten (``phase21.SEED_BASIS_RULED``). The alternative -- each
arm's own set -- would weight the graph regime twice as heavily in every
average, an unequal weighting nobody chose.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

from cleft import phase18, phase21  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"
P18_CONFIG = "p18_metric_space.yaml"
CEILING_CONFIG = "p13_confound_ceiling.yaml"
PROBE_ARM = "p7_d1_vit_b16_imagenet_g1"

ENSEMBLE_NAME = "p21_ensemble_probe.yaml"
CONSISTENCY_NAME = "p21_error_consistency.yaml"

SHARED_SEEDS = [1337, 2024, 7, 99, 12345]


def source(name: str) -> dict:
    return yaml.safe_load((REPO / "configs" / name).read_text(encoding="utf-8"))


def _ruled_entries() -> list[dict]:
    """The 64 arms phase21.ARM_SET_RULED declares, derived from the lock."""
    entries = phase18.locked_arm_entries()
    keep = [e for e in entries if e["n_patients"] == 237]
    dropped = [e for e in entries if e["n_patients"] != 237]
    if len(entries) != 68 or len(keep) != 64 or len(dropped) != 4:
        raise SystemExit(
            f"the lock yields {len(entries)} arms, {len(keep)} on 237 and "
            f"{len(dropped)} elsewhere; ARM_SET_RULED declares 68/64/4. Fix "
            "the ruling deliberately rather than letting the two drift"
        )
    if {e["group"] for e in dropped} != {"p12_view_ablation"}:
        raise SystemExit(
            f"the dropped arms are {sorted(e['name'] for e in dropped)}, not "
            "the p12 view-ablation group that ARM_SET_RULED names"
        )
    return keep


def _arms_and_inputs():
    """Arm rows on the shared five seeds, and the inputs they need --
    every one carried verbatim from Phase 18's config."""
    p18 = source(P18_CONFIG)
    declared = {entry["name"]: entry for entry in p18["inputs"]}

    entries = _ruled_entries()
    seen: dict[str, str] = {}
    inputs = []
    for entry in entries:
        if entry["run_dir"] in seen:
            continue
        # Phase 18 names its input for the FIRST arm that used the run
        # directory; the p16 run carries two prediction sets and shares
        # one input between them.
        candidates = [
            name for name, declared_entry in declared.items()
            if declared_entry.get("path", "").endswith(entry["run_dir"])
        ]
        if len(candidates) != 1:
            raise SystemExit(
                f"{entry['name']}: {len(candidates)} inputs in {P18_CONFIG} "
                f"match run_dir {entry['run_dir']}; expected exactly one"
            )
        seen[entry["run_dir"]] = candidates[0]
        inputs.append(dict(declared[candidates[0]]))

    arms = [
        {
            "name": entry["name"],
            "input": seen[entry["run_dir"]],
            # THE SHARED FIVE, for every arm without exception.
            "seeds": list(SHARED_SEEDS),
            "csv": entry["csv"],
            "group": entry["group"],
            "n_patients": entry["n_patients"],
        }
        for entry in entries
    ]
    if not all(set(SHARED_SEEDS) <= set(e["seeds"]) for e in entries):
        raise SystemExit(
            "some arm does not carry all five shared seeds; the basis "
            "phase21.SEED_BASIS_RULED declares would not exist for it"
        )
    inputs.append(dict(declared["manifest_v1"]))
    return arms, inputs


def _header(title: str, body: str, config_name: str) -> str:
    return (
        f"# {title}\n#\n"
        "# GENERATED by scripts/generate_phase21_configs.py. Do not\n"
        "# hand-edit: --check re-derives and diffs. The arm list is\n"
        "# DERIVED from phase18.ARM_LIST_LOCKED filtered by\n"
        "# phase21.ARM_SET_RULED, so NO GLOB exists in the arm\n"
        "# resolution and the config cannot drift from the lock.\n"
        "#\n"
        "# Every input is CARRIED VERBATIM from p18_metric_space.yaml --\n"
        "# same name, path and verified rollup. NO NEW HASH ENTERS.\n"
        f"#\n{body}#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{config_name}\"\n\n"
    )


def render_ensemble() -> str:
    arms, inputs = _arms_and_inputs()
    payload = {
        "schema_version": 1, "phase": "p21", "tier": "keeper", "seed": 1337,
        "inputs": inputs,
        "task": {
            "kind": "p21_ensemble_probe",
            "manifest_artifact": "manifest_v1",
            "arms": arms,
            "seeds": list(SHARED_SEEDS),
            "probe_arm": PROBE_ARM,
            "probe_pcc": 0.2520,
            "concat_precedent_delta": 0.0073,
            "n_boot": 10000,
            "expect_patients": 237,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return _header(
        "PHASE 21 -- ARM A: THE ENSEMBLE PROBE.",
        "# Does combining existing arms' PREDICTIONS exceed any of them\n"
        "# individually? phase21.ARM_A_REGISTERED.\n"
        "#\n"
        "# SIMPLE MEAN of per-patient OOF predictions within each seed,\n"
        "# over the 64 arms phase21.ARM_SET_RULED declares. No weights:\n"
        "# a learned weighting fitted on the OOF predictions would be\n"
        "# SELECTION_ON_EVALUATION_DATA_PROHIBITION with extra steps.\n"
        "#\n"
        "# **THE ARM SET, RULED 2026-09-01**: all 64 arms on the 237\n"
        "# cohort. EXACTLY ONE EXCLUSION -- the four p12_view_ablation\n"
        "# arms, on 236 patients -- made on a DATA PROPERTY with no\n"
        "# relation to performance, declared before any averaging.\n"
        "#\n"
        "# **THE ALL-68 VARIANT IS NOT RUN**: it would cross cohort\n"
        "# sizes. Its absence is recorded with the reason, not left as a\n"
        "# missing deliverable (EXIT_CRITERIA criterion 4).\n"
        "#\n"
        "# BOTH ANCHORS are declared: the probe at 0.2520 under PLAN\n"
        "# 4.3's full criterion, and Phase 7B's WITHDRAWN concat result\n"
        "# at +0.0073 -- an ensemble gain quoted without the concat\n"
        "# precedent beside it would read as though combination had\n"
        "# never been tried.\n"
        "#\n"
        "# Cached CSVs only: no backbone, no GPU, no new artifact, NO\n"
        "# GATE -- nothing here touches a cohort pixel.\n",
        ENSEMBLE_NAME,
    ) + body


def render_consistency() -> str:
    arms, inputs = _arms_and_inputs()
    ceiling = source(CEILING_CONFIG)
    sheet = next(
        e for e in ceiling["inputs"] if e["name"] == "scoresheet_primary"
    )
    inputs.append(dict(sheet))
    thresholds = phase21.CONSISTENCY_THRESHOLDS_RULED
    payload = {
        "schema_version": 1, "phase": "p21", "tier": "keeper", "seed": 1337,
        "inputs": inputs,
        "task": {
            "kind": "p21_error_consistency",
            "manifest_artifact": "manifest_v1",
            "scoresheet_artifact": "scoresheet_primary",
            "arms": arms,
            "seeds": list(SHARED_SEEDS),
            "binarisations": ["residual_sign", "worst_quartile"],
            "low_kappa": float(thresholds["low_value"]),
            "high_kappa": float(thresholds["high_value"]),
            "n_permutations": 20000,
            "alpha": 0.05,
            "n_raters": 5,
            "expect_patients": 237,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return _header(
        "PHASE 21 -- ARM B: ERROR CONSISTENCY.",
        "# Do architecturally diverse arms mispredict the SAME patients?\n"
        "# phase21.ARM_B_REGISTERED. Geirhos, Meding & Wichmann (NeurIPS\n"
        "# 2020) error consistency, adapted to regression.\n"
        "#\n"
        "# TWO BINARISATIONS, REPORTED SEPARATELY AND NEVER AVERAGED:\n"
        "# residual sign (error rate ~0.50) and worst-quartile absolute\n"
        "# residual (0.25 by construction). They answer different\n"
        "# questions; collapsing them would be the R2 shape.\n"
        "#\n"
        "# **THRESHOLDS RULED 2026-09-01**, and their ASYMMETRY is part\n"
        "# of the ruling. LOW <= 0.05 is DERIVED: the mean-of-pairs null\n"
        "# at n=237 sits at p99 = +0.022, so 0.05 is conservative in the\n"
        "# direction that makes LOW harder to declare. HIGH >= 0.50 is\n"
        "# CONVENTION -- the midpoint of kappa's normalised scale -- and\n"
        "# does NOT borrow Landis-Koch's authority. No measured HIGH can\n"
        "# exist: it would need a null for 'genuinely shared hard cases',\n"
        "# which cannot be built without assuming the answer.\n"
        "#\n"
        "# THE CROSS-REFERENCE: per-patient hardness against inter-rater\n"
        "# disagreement, by Kendall's tau-b with a PERMUTATION NULL AT\n"
        "# THE OBSERVED TIE STRUCTURE. The disagreement variable admits\n"
        "# only 26 distinct values, so a naive Pearson is inappropriate\n"
        "# and the statistic was declared before the run.\n"
        "#\n"
        "# The score sheet is declared because the derived rater sd is\n"
        "# CROSS-CHECKED against phase10_rater_grades' direct read: the\n"
        "# label join has produced two defects before.\n"
        "#\n"
        "# DESCRIPTIVE, no ledger row. Cached CSVs only, NO GATE.\n",
        CONSISTENCY_NAME,
    ) + body


CONFIGS = {
    ENSEMBLE_NAME: render_ensemble,
    CONSISTENCY_NAME: render_consistency,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    print(
        "64 arms derived from phase18.ARM_LIST_LOCKED (68 locked, 4 on the "
        "236 cohort excluded per phase21.ARM_SET_RULED); every input "
        "carried verbatim -- no new hash entered"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
