"""Write Phase 12's configs from the shipped inputs.

    PYTHONPATH=src python scripts/generate_phase12_configs.py [--check]

Stop 1 ships ONE config: the views-manifest derivation. The arm configs
(stop 3) and the paired scope (stop 4) join this generator when their
stops are reached -- the phase stops after each for review
(``phase12.PHASE_12_REGISTERED``).

The source manifest's hash is CARRIED from a shipped config -- a path's
contents are immutable, so one verified hash serves every config
declaring it, and this derivation needs no cluster round trip.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

from cleft import phase12  # noqa: E402
from cleft.data import views  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"
SOURCE_CONFIG = "p7_d1_vit_b16_imagenet_g1.yaml"
MANIFEST_NAME = "p12_views_manifest.yaml"


def source(name: str) -> dict:
    return yaml.safe_load((REPO / "configs" / name).read_text(encoding="utf-8"))


def render_views_manifest() -> str:
    arm = source(SOURCE_CONFIG)
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    payload = {
        "schema_version": 1,
        "phase": "p12",
        "tier": "keeper",
        "seed": 1337,
        "inputs": [dict(inputs_by_name["manifest_v1"])],
        "task": {
            "kind": "build_views_manifest",
            "manifest_artifact": "manifest_v1",
            "out_version": "cleft_v1_views",
            "expect_patients": views.VIEWS_COHORT["patients"],
            "expect_frontal": views.VIEWS_COHORT["frontal"],
            "expect_basal": views.VIEWS_COHORT["basal"],
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 12 — STOP 1 OF 4: DERIVE cleft_v1_views, THE 236-PATIENT\n"
        "# BOTH-VIEWS COHORT. phase12.STOP_1_MANIFEST.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase12_configs.py. The source\n"
        "# manifest's hash is CARRIED -- nothing new is declared.\n"
        "#\n"
        "# **A DERIVATION, NOT A REBUILD**: cleft_v1 already carries the\n"
        "# view pairing (its frontal came from score-sheet lookup, its\n"
        "# basal is the folder's other image), so the pairing is carried\n"
        "# from the artifact that measured it, never re-derived. Folder\n"
        "# 238 (frontal only) is dropped; every other row -- labels, soft\n"
        "# labels, class3 and the FOLD column -- is carried VERBATIM.\n"
        "#\n"
        "# **FOLDS CARRIED, NOT RE-STRATIFIED**: re-stratifying on 236\n"
        "# would reshuffle every assignment, making arm A on 236 differ\n"
        "# from the ladder's 0.2520 on 237 by a fold reshuffle AND a\n"
        "# patient -- two factors where the design wants one.\n"
        "#\n"
        "# **THE TWO EXCEPTIONS ARE ASSERTED**: folder 143 must pair\n"
        "# 524-frontal / 523-basal (the odd/even rule inverts there), and\n"
        "# folder 238 must be the ONLY single-view patient. A third\n"
        "# single-view patient, a swapped 143, or a source that is not\n"
        "# exactly the 237-row cleft_v1 stops the derivation.\n"
        "#\n"
        "# **NO PIXELS ARE TOUCHED HERE.** This is ID bookkeeping over an\n"
        "# artifact that has carried basal IDs since Phase 1. The ethics\n"
        "# gate (basal_use_acknowledged, confirmation) attaches\n"
        "# at stop 2, the first PIXEL use of the submental view.\n"
        "#\n"
        "# Output: data/manifests/cleft_v1_views -- cleft_v1's columns,\n"
        "# same names and order, so every existing loader reads it\n"
        "# unchanged; basal_id is never empty in this artifact.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{MANIFEST_NAME}\"\n\n"
    ) + body


STAGE_NAME = "p12_stage_basal.yaml"
P1_CONFIG = "p1_build_manifest.yaml"
PLACEHOLDER = "0" * 64
VIEWS_MANIFEST_PATH = f"{CLUSTER_ROOT}/data/manifests/cleft_v1_views"


def _carried_flag(path=None) -> bool:
    """the maintainer's acknowledgement, carried from the shipped config.

    A fresh render writes ``false``; only an existing ``true`` in the
    shipped config survives regeneration -- the same three-state carry as
    a filled hash, so the flag can become true ONLY by a deliberate edit
    edit keeps ``--check`` clean (``phase12.BASAL_USE_GATE``)."""
    path = path or REPO / "configs" / STAGE_NAME
    if not path.is_file():
        return False
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return payload.get("task", {}).get("basal_use_acknowledged") is True


def _carried_views_hash(path=None) -> str:
    """The views manifest's rollup, carried once declare_inputs fills it.

    The artifact was built by stop 1 on the cluster; its hash is not
    derivable on a laptop, so a fresh render writes the documented
    placeholder and the declare pass fills it -- carried thereafter."""
    path = path or REPO / "configs" / STAGE_NAME
    if not path.is_file():
        return PLACEHOLDER
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    for entry in payload.get("inputs") or []:
        if (
            entry.get("name") == "manifest_views"
            and entry.get("path") == VIEWS_MANIFEST_PATH
        ):
            rollup = str(entry.get("rollup_sha256") or "")
            if len(rollup) == 64 and set(rollup) != {"0"}:
                return rollup
    return PLACEHOLDER


def render_stage_basal() -> str:
    p1 = {e["name"]: e for e in source(P1_CONFIG)["inputs"]}
    acknowledged = _carried_flag()
    views_hash = _carried_views_hash()
    payload = {
        "schema_version": 1,
        "phase": "p12",
        "tier": "keeper",
        "seed": 1337,
        "inputs": [
            {
                "name": "manifest_views",
                "path": VIEWS_MANIFEST_PATH,
                "rollup_sha256": views_hash,
            },
            dict(p1["patient_folders"]),
        ],
        "task": {
            "kind": "stage_basal_views",
            "manifest_artifact": "manifest_views",
            "patient_folders": "patient_folders",
            "out_version": "staged_basal_v1",
            "expect_patients": views.VIEWS_COHORT["patients"],
            "basal_use_acknowledged": acknowledged,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    if views_hash == PLACEHOLDER:
        provenance = (
            "# **THE manifest_views HASH IS AN ALL-ZERO PLACEHOLDER.** The\n"
            "# artifact was built by stop 1 on the cluster and its rollup is\n"
            "# not derivable on a laptop. Fill via declare_inputs.py; guard 3\n"
            "# refuses the run until it is real -- the placeholder working,\n"
            "# not a mistake.\n"
        )
    else:
        provenance = (
            "# **RESOLVED.** Both inputs declared at real paths with\n"
            "# verified hashes.\n"
        )
    gate_line = (
        "# **basal_use_acknowledged: true -- A DATED CONFIRMATION,\n"
        "# CARRIED.** Set by a dated edit and carried by the generator; the\n"
        "# task runs.\n"
        if acknowledged else
        "# **basal_use_acknowledged: false -- THE TASK WILL REFUSE.** The\n"
        "# REC approvals' crop conditions were written around the RATED\n"
        "# frontal view; using the captured-but-unrated submental view is\n"
        "# a DIFFERENT USE of the same images. the maintainer confirms by\n"
        "# editing this flag to true; the generator CARRIES that edit, so\n"
        "# --check stays clean and code never sets it here\n"
        "# (phase12.BASAL_USE_GATE).\n"
    )
    return (
        "# PHASE 12 — STOP 2 OF 4: STAGE ALL 236 BASAL VIEWS AT G1 AND\n"
        "# RENDER THE REVIEW SHEETS. phase12.STOP_2_STAGING.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase12_configs.py.\n"
        "#\n"
        + gate_line
        + "#\n"
        "# **THE STAGING DECISION IS MEASURED FROM THE CODE PATH**\n"
        "# (phase12.STOP_2_STAGING_DECISION): at whole-image G1 NO\n"
        "# trapezium parameter is consumed -- stage() is pad-square-white-\n"
        "# centre-resize, and the frontal half-widths are consumed only by\n"
        "# G2's unwarp and the patch generators, which this phase's arms\n"
        "# never use. The frontal parameters do not 'transfer'; they are\n"
        "# NOT EXERCISED. Boundary: whole-image G1 ONLY -- any region or\n"
        "# G2 use of basal images REOPENS the decision. The task writes NO\n"
        "# G2 tensor and NO patch definitions.\n"
        "#\n"
        "# **TWO PIXEL FACTS ARE MEASURED IN THIS RUN, thresholds\n"
        "# registered before any pixel** (geometry/basal.py): corner\n"
        "# whiteness (image FLAGGED below 0.90; cohort MEDIAN below 0.90\n"
        "# REOPENS the white-pad decision before any embedding) and the\n"
        "# aspect-ratio distribution (reported beside the frontal\n"
        "# 0.553-1.099, shown to the eye, never refused by code).\n"
        "#\n"
        "# **THE SHEETS SHOW ALL 236 STAGED CROPS** -- 24 per sheet, six\n"
        "# columns, mid-grey ground, labelled patient/basal-id/AR/white\n"
        "# with FLAG below 0.90, ordered ASCENDING by corner whiteness so\n"
        "# the most suspicious land on sheet 1. Reviewed by eye or not at\n"
        "# all; NO EMBEDDING is extracted before the maintainer's pass.\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{STAGE_NAME}\"\n\n"
    ) + body


EXTRACT_NAME = "p12_extract_basal.yaml"
STAGED_BASAL_PATH = f"{CLUSTER_ROOT}/data/staged/staged_basal_v1"
BASAL_EMBEDDINGS_PATH = (
    f"{CLUSTER_ROOT}/data/embeddings/embeddings_basal_v1/vit_b16__imagenet__g1"
)

ARMS = {
    "p12_arm_a_frontal.yaml": ("a_frontal_only_236", ["frontal"], 769),
    "p12_arm_b_basal.yaml": ("b_basal_only_236", ["basal"], 769),
    "p12_arm_c_concat.yaml": ("c_two_view_concat", ["frontal", "basal"], 1537),
    "p12_arm_d_capacity.yaml": (
        "d_capacity_control", ["frontal", "frontal"], 1537
    ),
}


def _carried_hash(config_name: str, input_name: str, path: str) -> str:
    """A verified hash carried from the named shipped config while its
    path still matches -- the standing two-pass carry."""
    shipped = REPO / "configs" / config_name
    if not shipped.is_file():
        return "0" * 64
    payload = yaml.safe_load(shipped.read_text(encoding="utf-8")) or {}
    for entry in payload.get("inputs") or []:
        if entry.get("name") == input_name and entry.get("path") == path:
            rollup = str(entry.get("rollup_sha256") or "")
            if len(rollup) == 64 and set(rollup) != {"0"}:
                return rollup
    return "0" * 64


def _views_manifest_input() -> dict:
    """The views manifest, verified via the staging config's declare pass."""
    return {
        "name": "manifest_views",
        "path": VIEWS_MANIFEST_PATH,
        "rollup_sha256": _carried_hash(
            STAGE_NAME, "manifest_views", VIEWS_MANIFEST_PATH
        ),
    }


def render_extract_basal() -> str:
    payload = {
        "schema_version": 1,
        "phase": "p12",
        "tier": "keeper",
        "seed": 1337,
        "inputs": [
            _views_manifest_input(),
            {
                "name": "staged_basal",
                "path": STAGED_BASAL_PATH,
                "rollup_sha256": _carried_hash(
                    EXTRACT_NAME, "staged_basal", STAGED_BASAL_PATH
                ),
            },
        ],
        "task": {
            "kind": "extract_basal_embeddings",
            "manifest_artifact": "manifest_views",
            "staged_artifact": "staged_basal",
            "backbone": "vit_b16",
            "init": "imagenet",
            "geometry": "g1",
            "out_version": "embeddings_basal_v1",
            "expect_patients": views.VIEWS_COHORT["patients"],
        },
    }
    unresolved = sum(
        1 for e in payload["inputs"] if set(e["rollup_sha256"]) == {"0"}
    )
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    provenance = (
        f"# **{unresolved} HASH(ES) ARE ALL-ZERO PLACEHOLDERS** -- built on\n"
        "# the cluster, not derivable on a laptop. Fill via\n"
        "# declare_inputs.py; guard 3 refuses the run until real.\n"
        if unresolved else
        "# **RESOLVED.** Every input declared with a verified hash.\n"
    )
    return (
        "# PHASE 12 — STOP 3: EXTRACT THE BASAL EMBEDDING SET, AND THE\n"
        "# REGISTERED CONFOUND REPORT. phase12.STOP_3_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase12_configs.py.\n"
        "#\n"
        "# **EXISTING MACHINERY END TO END**: extract.extract_features\n"
        "# (vit_b16, imagenet, checkpoint None -- deterministic, eval,\n"
        "# no_grad) and embeddings.save with the views manifest ids, so\n"
        "# the row order is checked at write time. No new extraction code.\n"
        "#\n"
        "# **THE PAD DECISION IS TAKEN AND APPLIED** (phase12.PAD_DECISION\n"
        "# _TAKEN): pad white, consistency-not-continuity plus\n"
        "# fewest-fills; staged_basal_v1 stands with the visual check pass\n"
        "# attached. The residual novelty -- horizontal white bands on\n"
        "# AR>1 images, which the frontal cohort never showed the\n"
        "# backbone -- travels beside arm B/C results.\n"
        "#\n"
        "# **THE CONFOUND REPORT RIDES THIS RUN** -- the one place\n"
        "# staged_basal_v1's geometry.csv and the manifest's labels meet\n"
        "# once: corr(corner_white_fraction, mean) and corr(aspect_ratio,\n"
        "# mean) over the 236. READING REGISTERED BEFORE THE NUMBERS:\n"
        "# |r| >= 0.13 (p ~ 0.05 at n = 236) -> the caveat ATTACHES to\n"
        "# arm B and C results; below -> reported as null. REPORT, NEVER\n"
        "# GATE -- both r values are reported whichever way they fall.\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{EXTRACT_NAME}\"\n\n"
    ) + body


def render_arm(name: str) -> str:
    arm_key, channels, head_parameters = ARMS[name]
    source_arm = source(SOURCE_CONFIG)
    arm_task = source_arm["task"]
    ladder_inputs = {e["name"]: e for e in source_arm["inputs"]}

    inputs = [_views_manifest_input()]
    task = {
        "kind": "view_arm",
        "arm": arm_key,
        "views": channels,
        "manifest_artifact": "manifest_views",
    }
    if "frontal" in channels:
        inputs.append(dict(ladder_inputs["embeddings"]))
        task["frontal_embeddings"] = "embeddings"
    if "basal" in channels:
        inputs.append({
            "name": "basal_embeddings",
            "path": BASAL_EMBEDDINGS_PATH,
            "rollup_sha256": _carried_hash(
                name, "basal_embeddings", BASAL_EMBEDDINGS_PATH
            ),
        })
        task["basal_embeddings"] = "basal_embeddings"
    # The RECIPE is copied from the 0.2520 arm's shipped config, so
    # recipe identity is by construction rather than by transcription.
    task.update({
        "label": arm_task["label"],
        "seeds": arm_task["seeds"],
        "inner_val_frac": arm_task["inner_val_frac"],
        "max_epochs": arm_task["max_epochs"],
        "patience": arm_task["patience"],
        "monitor": arm_task["monitor"],
        "learning_rate": arm_task["learning_rate"],
        "weight_decay": arm_task["weight_decay"],
        "expect_patients": views.VIEWS_COHORT["patients"],
        "expect_head_parameters": head_parameters,
    })
    payload = {
        "schema_version": 1,
        "phase": "p12",
        "tier": "keeper",
        "seed": arm_task["seeds"][0],
        "inputs": inputs,
        "task": task,
    }
    unresolved = sum(
        1 for e in inputs if set(e["rollup_sha256"]) == {"0"}
    )
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    role = {
        "a_frontal_only_236": (
            "ARM A — FRONTAL ONLY, RE-RUN ON THE 236. The baseline is\n"
            "# re-measured because the cohort changed; it is NOT reused\n"
            "# from the 237 runs. 769-parameter head."
        ),
        "b_basal_only_236": (
            "ARM B — BASAL ONLY. The view the raters' scores are not\n"
            "# keyed to, alone. 769-parameter head. Reading 4 registered:\n"
            "# B near A would be surprising and gets no story until\n"
            "# measured."
        ),
        "c_two_view_concat": (
            "ARM C — FRONTAL (+) BASAL, 1536-d, 1537-parameter head. The\n"
            "# phase's question lives here, read against A AND D."
        ),
        "d_capacity_control": (
            "ARM D — CAPACITY CONTROL: frontal (+) frontal, the SAME\n"
            "# vector duplicated. C's capacity with A's information.\n"
            "# C > A with C ~ D refutes the view explanation in favour of\n"
            "# capacity; C > D isolates the view."
        ),
    }[arm_key]
    provenance = (
        f"# **{unresolved} HASH(ES) ARE ALL-ZERO PLACEHOLDERS** (the basal\n"
        "# set does not exist until p12_extract_basal runs). Fill via\n"
        "# declare_inputs.py; guard 3 refuses until real.\n"
        if unresolved else
        "# **RESOLVED.** Every input declared with a verified hash.\n"
    )
    return (
        f"# PHASE 12 — {role}\n"
        "# phase12.STOP_3_REGISTERED; readings phase12.PHASE_12_READINGS;\n"
        "# both interpretation sentences pre-written\n"
        "# (phase12.INTERPRETATION_SENTENCES_PREWRITTEN).\n"
        "#\n"
        "# GENERATED by scripts/generate_phase12_configs.py. ONE task\n"
        "# serves all four arms; the `views` channel list is the ONLY\n"
        "# difference between their configs, so every contrast is\n"
        "# one-factor by construction. The recipe block is COPIED from\n"
        f"# {SOURCE_CONFIG} -- the 0.2520 arm's own -- so recipe identity\n"
        "# holds by construction. Folds: cleft_v1_views, carried verbatim\n"
        "# from cleft_v1. Cohort: 236, patient 238 excluded from EVERY\n"
        "# arm including this one.\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{name}\"\n\n"
    ) + body


PAIRED_NAME = "p12_paired.yaml"


def _carried_paired_entries() -> dict:
    """Entries the paired config has already resolved, by name -- the
    three-state carry: a resolved PATH survives regeneration even while
    its hash is still a placeholder, a PENDING path never does."""
    path = REPO / "configs" / PAIRED_NAME
    if not path.is_file():
        return {}
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return {
        e["name"]: e for e in payload.get("inputs") or []
        if "/PENDING_" not in e["path"]
    }


def render_paired() -> str:
    """PLAN 4.3 condition 1 for the three view contrasts. Fits nothing.

    Same task, same BCa, same loader as every other scope -- only the
    pair enumeration differs, and it lives in phase12.paired_claim_pairs.
    """
    from cleft import ladder

    pairs = phase12.paired_claim_pairs("p12")
    vectors = ladder.paired_claim_vectors("p12", pairs=pairs)
    carried = _carried_paired_entries()

    inputs = []
    for stem, seed in vectors:
        name = f"oof_{stem}_seed_{seed}"
        inputs.append(carried.get(name) or {
            "name": name,
            "path": (
                f"{CLUSTER_ROOT}/runs/keeper/p12/PENDING_{stem}/"
                f"seed_{seed}__predictions.csv"
            ),
            "rollup_sha256": "0" * 64,
        })
    unresolved = sum(
        1 for e in inputs if set(e["rollup_sha256"]) == {"0"}
    )
    pending = sum(1 for e in inputs if "/PENDING_" in e["path"])
    stems = ladder.paired_claim_stems("p12", pairs=pairs)

    payload = {
        "schema_version": 1,
        "phase": "p12",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": {"kind": "paired_claims", "scope": "p12", "n_boot": 10000},
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    if pending:
        provenance = (
            f"# **{unresolved} HASHES ARE ALL-ZERO PLACEHOLDERS and "
            f"{pending} paths are\n"
            "# PENDING_<stem>.** A run directory carries a SHA and a job "
            "id,\n"
            "# neither derivable on a laptop. Two passes: paste the four "
            "run\n"
            "# directories from the listing (paths), then declare_inputs.py\n"
            "# (hashes). Guard 3 refuses the run until both are real.\n"
        )
    elif unresolved:
        provenance = (
            "# **PATHS RESOLVED, HASHES PENDING.** Every path is a real "
            "run\n"
            f"# directory; the {unresolved} remaining hashes are all-zero\n"
            "# placeholders until declare_inputs.py verifies the files.\n"
        )
    else:
        provenance = (
            f"# **RESOLVED.** All {len(inputs)} vectors declared at real "
            "paths\n"
            "# with verified hashes.\n"
        )
    recorded = {p["key"]: p["recorded"] for p in pairs}
    return (
        "# PHASE 12 — STOP 4 OF 4: PLAN §4.3 CONDITION 1 FOR THE THREE\n"
        "# VIEW CONTRASTS. phase12.STOP_4_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase12_configs.py from\n"
        "# phase12.paired_claim_pairs('p12').\n"
        "#\n"
        "# **THIS RUN FITS NOTHING.** Every vector was written by a keeper\n"
        "# arm run that already happened.\n"
        "#\n"
        f"# **SCOPE: p12.** Three pairs over {len(stems)} run directories,\n"
        f"# {len(inputs)} vectors, the shared five seeds: B vs A, C vs A,\n"
        "# C vs D. Same task, same BCa, same loader as every other scope\n"
        "# -- only the pair enumeration differs.\n"
        "#\n"
        "# **THE PREDICTION IS ARITHMETIC ON RECORDED FIGURES** (derived\n"
        "# from the arms' own per-seed values, never typed):\n"
        f"#   C vs A  d {recorded['p12__concat_vs_frontal_bar']['delta_of_means']:+.4f}"
        f"  threshold {recorded['p12__concat_vs_frontal_bar']['threshold']:.4f}"
        f"  margin {recorded['p12__concat_vs_frontal_bar']['margin']}x -- FAILS cond 2\n"
        f"#   C vs D  d {recorded['p12__concat_vs_capacity']['delta_of_means']:+.4f}"
        f"  threshold {recorded['p12__concat_vs_capacity']['threshold']:.4f}"
        f"  margin {recorded['p12__concat_vs_capacity']['margin']}x -- FAILS cond 2\n"
        f"#   B vs A  d {recorded['p12__basal_vs_frontal_bar']['delta_of_means']:+.4f}"
        f"  threshold {recorded['p12__basal_vs_frontal_bar']['threshold']:.4f}"
        f"  margin {recorded['p12__basal_vs_frontal_bar']['margin']}x -- under the 2.55x floor\n"
        "# The per-seed signs are already visible (C positive on 3/5\n"
        "# against both A and D), so the reading-2 prior's 'C-vs-A fails\n"
        "# condition 1 at 3/5 with a positive mean delta' is arithmetic,\n"
        "# not foresight. WHAT REMAINS AT RISK: the per-patient BCa\n"
        "# interval widths alone. The honest sentence either way is\n"
        "# pre-written by phase12.PHASE_12_READINGS.\n"
        "#\n"
        "# **THE STAGING-GEOMETRY CAVEAT TRAVELS** on every pair involving\n"
        "# B or C (phase12.BASAL_CONFOUND_OBSERVED: r(AR, mean) +0.1601).\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{PAIRED_NAME}\"\n\n"
    ) + body


CONFIGS = {
    MANIFEST_NAME: render_views_manifest,
    STAGE_NAME: render_stage_basal,
    EXTRACT_NAME: render_extract_basal,
    **{name: (lambda n=name: render_arm(n)) for name in ARMS},
    PAIRED_NAME: render_paired,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    print("manifest hash carried; nothing new declared")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
