"""Phase 16 configs -- the anchor loop (phase16.EXIT_CRITERIA).

Two configs: the once-only anchor extraction, and the loop itself. The
loop's mirrored settings are READ FROM the probe's shipped config
(SETTINGS_PROVENANCE), so 'the same recipe values' is a fact about the
files; tau_scale and lambda_identity are the two declared scientific
settings, and any silent edit to either is DRIFT under --check.

    python scripts/generate_phase16_configs.py           # write
    python scripts/generate_phase16_configs.py --check    # drift only
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[1]
CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"
PLACEHOLDER = "0" * 64

PROBE_CONFIG = "p7_d1_vit_b16_imagenet_g1.yaml"
PASS_ZERO_CONFIG = "p9_prototype_classifier.yaml"
ADDENDUM_CONFIG = "p7_d1_classification_metrics.yaml"

EXTRACT_NAME = "p16_extract_anchor_embeddings.yaml"
LOOP_NAME = "p16_anchor_loop.yaml"

ANCHOR_SET_VERSION = "anchor_deall_v1"

#: The two declared scientific settings
#: (phase16.ANCHOR_LOOP_RULINGS['weight_decay_is_a_scientific_setting'],
#: phase16.TAU_DECLARED). lambda mirrors the probe's weight_decay VALUE
#: (SETTINGS_PROVENANCE names the config); tau_scale has no precedent
#: and is declared. NEVER tuned across runs; movement is a dated
#: amendment with a reason.
TAU_SCALE = 1.0


def source_config(name: str) -> dict:
    return yaml.safe_load(
        (REPO / "configs" / name).read_text(encoding="utf-8")
    )


def _named(payload: dict, name: str) -> dict:
    return dict(
        next(e for e in payload["inputs"] if e["name"] == name)
    )


def _carried(config_name: str, input_name: str, path: str) -> dict:
    """The path-pinned carry (phase 15's ``_carried_named``)."""
    entry = {"name": input_name, "path": path, "rollup_sha256": PLACEHOLDER}
    shipped = REPO / "configs" / config_name
    if not shipped.is_file():
        return entry
    payload = yaml.safe_load(shipped.read_text(encoding="utf-8")) or {}
    for candidate in payload.get("inputs") or []:
        if candidate.get("name") != input_name:
            continue
        if str(candidate.get("path")) != path:
            continue
        rollup = str(candidate.get("rollup_sha256") or "")
        if len(rollup) == 64 and set(rollup) != {"0"}:
            entry["rollup_sha256"] = rollup
    return entry


def _provenance(inputs: list) -> str:
    pending = sum(1 for e in inputs if "/PENDING_" in e["path"])
    unresolved = sum(1 for e in inputs if set(e["rollup_sha256"]) == {"0"})
    if pending:
        return (
            f"# **{pending} PATH(S) PENDING and {unresolved} ALL-ZERO\n"
            "# PLACEHOLDER HASH(ES).** Two passes: paste the run\n"
            "# directory, then declare_inputs.py. Guard 3 refuses until\n"
            "# both are real.\n"
        )
    if unresolved:
        return (
            f"# **{unresolved} ALL-ZERO PLACEHOLDER HASH(ES) REMAIN.**\n"
            "# Every path is real; declare_inputs.py fills the rest and\n"
            "# guard 3 refuses until it does.\n"
        )
    return (
        "# **RESOLVED.** Every input declared at a real path with a\n"
        "# verified hash.\n"
    )


def render_extract() -> str:
    pass_zero = source_config(PASS_ZERO_CONFIG)
    inputs = [
        _named(pass_zero, "deall_set"),
        _named(pass_zero, "manifest_v1"),
        _named(pass_zero, "staged_v1"),
        _named(pass_zero, "embeddings"),
    ]
    payload = {
        "schema_version": 1, "phase": "p16", "tier": "keeper",
        "seed": 1337, "inputs": inputs,
        "task": {
            "kind": "extract_anchor_embeddings",
            "deall_artifact": "deall_set",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "embeddings_artifact": "embeddings",
            "geometry": "g1",
            "backbone": "vit_b16",
            "batch_size": 32,
            "out_version": ANCHOR_SET_VERSION,
            "expect_anchors": 25,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 16 -- THE 25 DEALL ANCHOR EMBEDDINGS, PERSISTED ONCE.\n"
        "# phase16.ANCHOR_ARTIFACT_PERSISTED, three reasons on record:\n"
        "# declared-input purity downstream; ONE drift surface instead\n"
        "# of one per run; CLUSTER-ONLY like all patient-derived\n"
        "# artifacts.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase16_configs.py. Every\n"
        f"# input is CARRIED from {PASS_ZERO_CONFIG} -- the\n"
        "# pass-zero lineage, already declared and verified -- so this\n"
        "# config needs NO new declaration before launch.\n"
        "#\n"
        "# The extraction is pass zero's path line for line (stage ->\n"
        "# FrozenExtractor) with the live-path parity check repeated:\n"
        "# banked reference 1.53e-05, refusal at 1e-2. The writer\n"
        "# refuses anything but 25 anchors at the registered 3/7/6/6/3\n"
        "# grade spread.\n"
        "#\n"
        "# A small GPU task (25 images; CPU fallback exists).\n"
        "#\n"
        + _provenance(inputs)
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{EXTRACT_NAME}\"\n\n"
    ) + body


def render_loop() -> str:
    probe = source_config(PROBE_CONFIG)
    addendum = source_config(ADDENDUM_CONFIG)
    recipe = probe["task"]
    inputs = [
        _carried(
            LOOP_NAME, "anchor_embeddings",
            f"{CLUSTER_ROOT}/data/embeddings/{ANCHOR_SET_VERSION}",
        ),
        _named(addendum, "arm_run") | {"name": "probe_run"},
        _named(probe, "manifest_v1"),
        _named(probe, "embeddings"),
    ]
    payload = {
        "schema_version": 1, "phase": "p16", "tier": "keeper",
        "seed": 1337, "inputs": inputs,
        "task": {
            "kind": "anchor_loop",
            "arm": "p16_anchor_loop",
            "probe_run": "probe_run",
            "anchor_embeddings": "anchor_embeddings",
            "embeddings_artifact": "embeddings",
            "manifest_artifact": "manifest_v1",
            "seeds": list(recipe["seeds"]),
            "max_epochs": recipe["max_epochs"],
            "learning_rate": recipe["learning_rate"],
            "batch_size": recipe["batch_size"],
            "inner_val_frac": recipe["inner_val_frac"],
            "monitor": recipe["monitor"],
            "lambda_identity": recipe["weight_decay"],
            "tau_scale": TAU_SCALE,
            "n_boot": 10000,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 16 -- THE ANCHOR LOOP. phase16.EXIT_CRITERIA, locked\n"
        "# 2026-08-29; registration phase15.ANCHOR_LOOP_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase16_configs.py. The\n"
        f"# mirrored settings are COPIED FROM {PROBE_CONFIG}\n"
        "# (SETTINGS_PROVENANCE, per value): max_epochs, learning_rate,\n"
        "# batch_size, inner_val_frac, monitor, seeds -- and\n"
        "# lambda_identity takes the probe's weight_decay VALUE while\n"
        "# the mechanism decays toward IDENTITY, not zero (the\n"
        "# optimiser's own weight_decay is 0 in code). NO patience key\n"
        "# exists in this schema: writing one is refused, not ignored.\n"
        "#\n"
        "# **THE TWO DECLARED SCIENTIFIC SETTINGS** (never tuned across\n"
        "# runs; movement is a dated amendment with a reason):\n"
        "#   lambda_identity = 0.01  (probe's weight_decay value)\n"
        "#   tau_scale = 1.0         (NO precedent; phase16.TAU_DECLARED\n"
        "#     -- tau = tau_scale x mean squared anchor-anchor distance,\n"
        "#     frozen in the UNCORRECTED space. Degenerate mode\n"
        "#     REGISTERED: large tau flattens to a constant 2.96,\n"
        "#     near-zero PCC, acc3 near the 0.502 majority floor)\n"
        "#\n"
        "# Continuous target ONLY (the 3-class pull loss, diagonal W\n"
        "# and low-rank W are named UNREGISTERED); the no-folds\n"
        "# full-cohort path is structurally absent; identity baseline\n"
        "# rides DESCRIPTIVELY through the same readout; mismatch\n"
        "# records for all 237 regardless of outcome; primary contrast\n"
        "# = paired BCa 10,000 vs the probe, both criterion conditions,\n"
        "# COHORT_CANNOT_RESOLVE predicting unresolved and success\n"
        "# defined as parity-with-explanations.\n"
        "#\n"
        "# CPU-only on cached features once the anchor set exists.\n"
        "#\n"
        + _provenance(inputs)
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{LOOP_NAME}\"\n\n"
    ) + body


CONFIGS = {EXTRACT_NAME: render_extract, LOOP_NAME: render_loop}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
