"""Write the Phase 8 configs from ``cleft.phase8`` and the arms' own configs.

    PYTHONPATH=src python scripts/generate_phase8_configs.py [--check]

**Generated, and the hyperparameters are COPIED from each arm rather than
retyped.** The Grad-CAM run refits arm A's thirty heads and gates on
reproducing 0.2520 (``phase8.REPRODUCE_GATE``); the node-weight run refits arm
B's fifty and gates on reproducing 0.1719
(``phase8.SRGNN_NODE_WEIGHTS_R10_READ``). A mistyped learning rate would fail
either gate on the cluster after the whole refit, for a reason the log would
state but nobody would expect. Reading them from the arms' own configs makes
"same arm" true by construction.

**The pre-registration is not here.** The target layer, the sample rules, the
head-selection rule, the randomisation criterion and the two gate values live
in ``cleft.phase8`` and ``cleft.node_weights`` where the suite checks them. The
layer especially: it is the field most likely to be nudged because a map looked
better.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

from cleft import embedding_plan, node_weights, phase8  # noqa: E402
from cleft.train import pretrain as pretrain_module  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"

#: Arm A. Its inputs and hyperparameters are the ones the refit must match.
SOURCE_CONFIG = "p7_d1_vit_b16_imagenet_g1.yaml"

#: Arm B, the interpretable arm. Same relationship: its config is the source
#: of truth for what the node-weight refit has to reproduce.
ARM_B_CONFIG = "p7_d1_srgnn_imagenet_g1_native.yaml"

#: Copied verbatim from the source arm, never retyped.
COPIED = (
    "geometry", "label", "backbone", "seeds", "inner_val_frac",
    "max_epochs", "patience", "monitor", "learning_rate", "weight_decay",
    "batch_size",
)

#: Arm B's extra axes -- the graph regime names its init, scheme and policy,
#: and the artifact pairing check compares against exactly these.
ARM_B_COPIED = COPIED + ("init", "region_scheme", "trainable")


def source(name: str = SOURCE_CONFIG) -> dict:
    return yaml.safe_load((REPO / "configs" / name).read_text(encoding="utf-8"))


def render() -> str:
    arm = source()
    task = {"kind": "grad_cam"}
    for name in ("manifest_artifact", "staged_artifact", "embeddings_artifact"):
        task[name] = arm["task"][name]
    missing = [name for name in COPIED if name not in arm["task"]]
    if missing:
        raise SystemExit(f"{SOURCE_CONFIG} no longer carries {missing}")
    task.update({name: arm["task"][name] for name in COPIED})

    payload = {
        "schema_version": 1,
        "phase": "p8",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        "inputs": [dict(entry) for entry in arm["inputs"]],
        "task": task,
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    target = phase8.GRAD_CAM_TARGET
    sample = phase8.STRATIFIED_SAMPLE
    return (
        "# PHASE 8 — GRAD-CAM FOR ARM A, GATED TWICE\n"
        "#\n"
        f"# GENERATED by scripts/generate_phase8_configs.py from cleft.phase8\n"
        f"# and {SOURCE_CONFIG}. The hyperparameters are COPIED from arm A, not\n"
        "# retyped: this run refits arm A's thirty heads and gates on\n"
        "# reproducing 0.2520, and a mistyped learning rate would fail that\n"
        "# gate after loading every embedding.\n"
        "#\n"
        "# **GATE 1 — the refit must BE arm A.** If the refitted heads do not\n"
        f"# give back {phase8.REPRODUCE_GATE['expected_pcc']} within\n"
        f"# {phase8.REPRODUCE_GATE['tolerance']}, they are not arm A's heads and\n"
        "# any map would explain a different model. Nothing is computed.\n"
        "#\n"
        "# **GATE 2 — the randomisation test.** Every map must degrade under\n"
        "# model-parameter randomisation, judged against the between-patient\n"
        "# baseline measured on the same sample. The verdict is PER PATIENT:\n"
        "# one survivor of fifteen is a failure, not a 93% pass. If it fails,\n"
        "# metrics.json is written and NO MAPS ARE.\n"
        "#\n"
        f"# TARGET LAYER: {target['layer']}.\n"
        "# **[MEASURED] Not the final block, and this is the phase's sharpest\n"
        "# finding so far.** The head reads x[:, 0] after a per-token\n"
        "# LayerNorm, so at block 12's output the patch tokens feed nothing --\n"
        "# their gradient is exactly 0.000e+00. A zero map does not come out\n"
        "# blank: Grad-CAM divides by the maximum, so float noise becomes a\n"
        "# full-range picture that passes every visual check. gradcam.cam\n"
        "# refuses it. The layer is pre-registered in cleft.phase8 and is NOT\n"
        "# a config field.\n"
        "#\n"
        f"# RESOLUTION FLOOR: {phase8.RESOLUTION_FLOOR['floor_px']}px. The 14x14\n"
        "# grid upsampled to 224 is a 16x interpolation, so no localisation\n"
        "# finer than a 16-pixel block is real. A map read as pointing at the\n"
        "# philtral column is reading the interpolation kernel.\n"
        "#\n"
        f"# SAMPLE: {sample['per_stratum']} patients from each of\n"
        f"# {sample['n_strata']} grade strata, seed {sample['seed']}, and NO\n"
        "# SUBSTITUTION -- a patient whose map fails to render is reported,\n"
        "# never replaced. Replacement-on-rejection is cherry-picking with an\n"
        "# audit trail that looks principled.\n"
        "#\n"
        "# Each patient is explained by the fold-model that HELD THEM OUT, at\n"
        "# all five seeds, with the map's stability reported as a number\n"
        "# rather than averaged away. phase8.HEAD_SELECTION.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p8_grad_cam.yaml\"\n\n"
    ) + body


def render_softmax_variant() -> str:
    """Phase 8b: the variant's config -- arm A's inputs and hyperparameters
    CARRIED from the original grad_cam config's verified entries, because
    the variant explains the same model through the same refit gate. No
    placeholders: nothing about this run is new but the aggregation."""
    arm = source()
    task = {"kind": "grad_cam_softmax"}
    for name in ("manifest_artifact", "staged_artifact", "embeddings_artifact"):
        task[name] = arm["task"][name]
    missing = [name for name in COPIED if name not in arm["task"]]
    if missing:
        raise SystemExit(f"{SOURCE_CONFIG} no longer carries {missing}")
    task.update({name: arm["task"][name] for name in COPIED})

    payload = {
        "schema_version": 1,
        "phase": "p8",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        "inputs": [dict(entry) for entry in arm["inputs"]],
        "task": task,
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    registered = phase8.GRAD_CAM_SOFTMAX_REGISTERED
    return (
        "# PHASE 8b — THE GRAD-CAM VARIANT: SOFTMAX WEIGHTING, NEGATIVES\n"
        "# DROPPED. A SECOND METHOD beside grad_cam, never a modification.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase8_configs.py from cleft.phase8\n"
        f"# and {SOURCE_CONFIG}. Inputs and hyperparameters are the ORIGINAL\n"
        "# grad_cam config's verified entries, carried -- the variant\n"
        "# explains the same model, so the same refit gate (0.2520 within\n"
        "# 0.002) guards it.\n"
        "#\n"
        "# **WHY A SECOND METHOD (verbatim from the registration)**: the\n"
        "# existing Grad-CAM's problem was never the weighting -- it was\n"
        "# gate estimability at n=15, and that verdict stands; changing the\n"
        "# statistic after a failed gate is the move this project has\n"
        "# corrected twice, which is why this is a second method with its\n"
        "# own gate, both reported.\n"
        "#\n"
        "# THE TWO DELTAS, and nothing else: negatives dropped before\n"
        "# aggregation; softmax over the surviving channel importances.\n"
        "# Same backbone, arm, block-11 target, heads, patients, seeds,\n"
        "# final ReLU, zero-gradient guard, floor, caveat.\n"
        "#\n"
        "# **ITS OWN GATE, form fixed by RANDOMISATION_CRITERION_ADOPTED**:\n"
        "# phase-level separability of the VARIANT'S maps against the\n"
        "# VARIANT'S OWN in-run between-patient baseline (never inherited);\n"
        "# 95% CI over patients excludes zero; per-patient figures are\n"
        "# PERCENTILES, never pass/fail. Unresolved -> nothing published,\n"
        "# not rescued by switching statistic.\n"
        "#\n"
        "# CONCENTRATION readings committed BOTH ways before any number\n"
        "# (top-10 token share, paired variant-minus-original):\n"
        "# concentrates -> the account changes, says nothing about accuracy;\n"
        "# diffuse -> corroborates that the weighting was never the problem.\n"
        "#\n"
        "# ARTIFACTS: grad_cam_methods.npz ALWAYS (the 8c side-by-side\n"
        "# surface, both verdict stamps, caveat AND refusal counts inside);\n"
        "# grad_cam_softmax_maps.npz only on a pass. The original's failed\n"
        "# verdict is untouched and stamped, never revised.\n"
        "#\n"
        "# **[2026-08-15, after the pod probe] PER-CELL REFUSAL HANDLING**\n"
        "# (phase8.GRAD_CAM_SOFTMAX_REFUSAL_HANDLING): a cell whose variant\n"
        "# map is all-zero after the ReLU is recorded as a DATUM and the\n"
        "# walk continues -- the pod probe measured 19 of 75 cells refusing\n"
        "# with every patient keeping a map, so gate 2 runs at full n=15\n"
        "# with the count stamped. Refusal count and survivor concentration\n"
        "# are ONE mechanism, never reported apart. The two deltas stay\n"
        "# exactly two; the registered softmax's flatness is a recorded\n"
        "# finding (phase8.SOFTMAX_FLATTENS_THE_WEIGHTING), and any\n"
        "# tempered variant is a NEW method, not a fix to this one.\n"
        "#\n"
        "# RUNS FRESH: no stored activations/gradients exist. Job shape =\n"
        "# the original p8_grad_cam run (15 patients x 5 seeds + the\n"
        "# 12-stage walk), one forward-backward serving both methods.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p8_grad_cam_softmax.yaml\"\n\n"
    ) + body


PLACEHOLDER = "0" * 64


def _carried(config_name: str, input_name: str, expected_path: str) -> str:
    """A resolved hash CARRIED from the shipped config while the path still
    matches -- the generate_phase7d_configs rule, needed here once 8c's
    inputs started resolving in passes."""
    path = REPO / "configs" / config_name
    if not path.is_file():
        return PLACEHOLDER
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    for entry in payload.get("inputs") or []:
        if entry.get("name") != input_name:
            continue
        rollup = str(entry.get("rollup_sha256") or "")
        if (
            entry.get("path") == expected_path
            and len(rollup) == 64
            and set(rollup) <= set("0123456789abcdef")
            and set(rollup) != {"0"}
        ):
            return rollup
    return PLACEHOLDER


#: The run directories 8c reads. Both are REAL: the methods npz's from the
#: completed softmax rerun; node-weights' supplied from the run listing
#: 2026-08-15 and passed through run_names.check_run_dir before filling.
METHODS_NPZ_DIR = (
    "runs/keeper/p8/p8_grad_cam_softmax__2cce9625__p8-grad-cam-softmax-3"
)
NODE_WEIGHTS_DIR = "runs/keeper/p8/p8_node_weights__7be67a24__p8-node-weights"
VIT_RUN_DIR = "runs/keeper/p7/p7_d1_vit_b16_imagenet_g1__3f71a6a9__p7-d1-vit-imagenet"
SEED_LIST = (7, 99, 1337, 2024, 12345)


def _known_hashes_by_path() -> dict:
    """Every verified hash any shipped config already declares, by path --
    the paired generator's reuse rule: one path, one hash, no second
    cluster round trip for a file already declared."""
    known: dict[str, str] = {}
    for path in sorted((REPO / "configs").glob("*.yaml")):
        payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        for entry in payload.get("inputs") or []:
            rollup = entry.get("rollup_sha256")
            if rollup and set(str(rollup)) != {"0"} and "*" not in entry["path"]:
                known.setdefault(entry["path"], str(rollup))
    return known


def render_phase8c_sheet() -> str:
    arm = source()
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    known = _known_hashes_by_path()
    config_name = "p8c_sheet.yaml"

    def entry(name, path):
        return {
            "name": name,
            "path": path,
            "rollup_sha256": known.get(
                path, _carried(config_name, name, path)
            ),
        }

    methods_path = f"{CLUSTER_ROOT}/{METHODS_NPZ_DIR}/grad_cam_methods.npz"
    node_path = f"{CLUSTER_ROOT}/{NODE_WEIGHTS_DIR}/node_weights.npz"
    prediction_inputs = [
        entry(f"oof_seed_{s}",
              f"{CLUSTER_ROOT}/{VIT_RUN_DIR}/seed_{s}__predictions.csv")
        for s in SEED_LIST
    ]
    curve_inputs = [
        entry(f"curves_seed_{s}",
              f"{CLUSTER_ROOT}/{VIT_RUN_DIR}/seed_{s}__curves.csv")
        for s in SEED_LIST
    ]
    # [2026-08-15, the clinical rebuild] The animation run's directory is
    # an INPUT: the pages embed its APNGs. Filled from the run listing
    # (p8c-animation-2, passed run_names.check_run_dir); the hash follows
    # by declare pass.
    animation_path = (
        f"{CLUSTER_ROOT}/runs/keeper/p8c/"
        "p8c_animation__8d8fe58f__p8c-animation-2"
    )
    payload = {
        "schema_version": 1,
        "phase": "p8c",
        "tier": "keeper",
        "seed": 1337,
        "inputs": [
            dict(inputs_by_name["manifest_v1"]),
            dict(inputs_by_name["staged_v1"]),
            entry("grad_cam_methods", methods_path),
            entry("node_weights", node_path),
            entry("animation_run", animation_path),
            *prediction_inputs,
            *curve_inputs,
        ],
        "task": {
            "kind": "phase8c_sheet",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "methods_artifact": "grad_cam_methods",
            "node_weights_artifact": "node_weights",
            "animation_artifact": "animation_run",
            "geometry": arm["task"]["geometry"],
            "label": arm["task"]["label"],
            "prediction_inputs": [e["name"] for e in prediction_inputs],
            "curve_inputs": [e["name"] for e in curve_inputs],
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    unresolved = sum(
        1 for e in payload["inputs"] if set(e["rollup_sha256"]) == {"0"}
    )
    return (
        "# PHASE 8c — THE CLINICAL DELIVERY. A RENDERING; NOTHING IS\n"
        "# MEASURED. [REBUILT 2026-08-15 after the eye review:\n"
        "# phase8c.CLINICAL_DELIVERY_REBUILT: HTML pages, heat ON the\n"
        "# face, plain language; stamps and the verbatim caveat on the\n"
        "# linked appendix.]\n"
        "#\n"
        "# The animation run is a DECLARED INPUT (its APNGs are embedded\n"
        "# in the pages): p8c-animation-2, filled from the run listing and\n"
        "# guard-checked; its hash follows by declare pass. Cluster-side\n"
        "# input dependence confirmed on its frames (p55 vs p120 same-step\n"
        "# frames differ, cmp at byte 36).\n"
        "#\n"
        "# GENERATED by scripts/generate_phase8_configs.py from cleft.phase8c.\n"
        "#\n"
        "# Fifteen per-patient pages + one cohort page, CLUSTER-ONLY. The\n"
        "# scope line of 2026-08-13 governs: cohort patients, never live\n"
        "# inference on an arbitrary face. Panel 1 shows the 22\n"
        "# cleft-anatomy regions (of the 27-patch frozen scheme) --\n"
        "# phase8c.PANEL_1_NAMING records the naming resolution. Every map\n"
        "# panel: 16-px nearest blocks, the caveat verbatim from its\n"
        "# artifact, both verdict stamps, and 'no map on this sheet is a\n"
        "# published claim' in every banner. The both_numbers_sentence is\n"
        "# READ from grad_cam_methods.npz, never recomposed.\n"
        "#\n"
        + (
            (
                f"# {unresolved} hash(es) below are all-zeros PLACEHOLDERS "
                "pending\n"
                "# the declare pass for the input(s) named above as pending.\n"
                "# Every other entry is the declare pass's own figure,\n"
                "# carried.\n"
            )
            if unresolved
            else (
                "# FULLY DECLARED [2026-08-15]: every hash below is the\n"
                "# declare pass's own figure, CARRIED by this generator,\n"
                "# never typed. The node_weights run directory passed\n"
                "# run_names.check_run_dir before its path was filled.\n"
            )
        )
        + "# Predictions hashes are carried from the paired configs' "
        "verified\n"
        "# entries.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p8c_sheet.yaml\"\n\n"
    ) + body


def render_phase8c_animation() -> str:
    arm = source()
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    known = _known_hashes_by_path()
    config_name = "p8c_animation.yaml"
    methods_path = f"{CLUSTER_ROOT}/{METHODS_NPZ_DIR}/grad_cam_methods.npz"
    task = {
        "kind": "phase8c_animation",
        "manifest_artifact": "manifest_v1",
        "staged_artifact": "staged_v1",
        "embeddings_artifact": "embeddings",
        "methods_artifact": "grad_cam_methods",
    }
    task.update({name: arm["task"][name] for name in COPIED})
    payload = {
        "schema_version": 1,
        "phase": "p8c",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        "inputs": [
            dict(entry) for entry in arm["inputs"]
        ] + [{
            "name": "grad_cam_methods",
            "path": methods_path,
            "rollup_sha256": known.get(
                methods_path,
                _carried(config_name, "grad_cam_methods", methods_path),
            ),
        }],
        "task": task,
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 8c — THE ANIMATION: HEAT OVER THREE REAL AXES, MEASURED\n"
        "# FRAMES ONLY. phase8c.ANIMATION_REGISTERED is the registration.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase8_configs.py from cleft.phase8c\n"
        f"# and {SOURCE_CONFIG} (the refit block copied -- same arm, same\n"
        "# 0.2520 gate).\n"
        "#\n"
        "# (a) training trajectory: init (annotated no-map frame -- zero\n"
        "# head, no gradient direction); steps 1,2,3,5,10,20,50 of epoch 1;\n"
        "# epoch ends to early stop. Head = held-out fold head at seeds[0];\n"
        "# per-seed-mean interior frames are BARRED.\n"
        "# (b) randomisation walk: 13 frames, ORIGINAL method, failed-gate\n"
        "# stamp on every frame, clean snapshot restored per patient.\n"
        "# (d) depth: blocks 0..10, ending ON the registered layer; no\n"
        "# frame may be quoted as an alternative 'better' map.\n"
        "# (c) seeds: a STATIC strip, labelled unordered -- computed here\n"
        "# because the sheet task computes no maps.\n"
        "#\n"
        "# Every animation's FINAL frame is READ from grad_cam_methods.npz\n"
        "# (byte-identical to the sheet's map by construction) and labelled\n"
        "# as the 5-seed-mean endpoint -- the recorded endpoint resolution.\n"
        "# No interpolated frames anywhere; 16-px nearest blocks; caveat +\n"
        "# stamp + axis value burned into every frame. APNG + PNG frames\n"
        "# beside; GIF only on viewer refusal.\n"
        "#\n"
        "# FULLY DECLARED [2026-08-15]: the methods-npz hash is the declare\n"
        "# pass's own figure, carried; every other input is the original\n"
        "# grad_cam config's verified entry.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p8c_animation.yaml\"\n\n"
    ) + body


#: The control set's artifact version and the input name the node-weight run
#: declares it under. One place, so the extraction and its consumer cannot
#: name different directories.
CONTROL_VERSION = "embeddings_g1_randomised_v1"
CONTROL_INPUT = "randomised_embeddings"


def control_set_name() -> str:
    """The control's directory name, DERIVED rather than typed."""
    arm = source(ARM_B_CONFIG)["task"]
    return embedding_plan.set_name({
        "backbone": arm["backbone"], "init": arm["init"],
        "geometry": arm["geometry"], "pretrain_scheme": None,
        "randomise": True,
    })


def control_path() -> str:
    return (
        f"{CLUSTER_ROOT}/data/embeddings/{CONTROL_VERSION}/{control_set_name()}"
    )


def carried_control_rollup() -> str | None:
    """The control's VERIFIED hash, carried from the shipped config.

    Hashes come only from declare_inputs.py against the built artifact
    (guard 3 re-verifies before any run starts), so this generator cannot
    produce one -- it can only CARRY what the declare pass filled in, and
    only while the path it was declared against is still the path derived
    here. A rename invalidates the carry and the entry reverts to the
    placeholder, exactly as generate_roadb_configs' existing_entries()
    decided after a stale path rode through a rename once.
    """
    path = REPO / "configs" / "p8_node_weights.yaml"
    if not path.is_file():
        return None
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    for entry in payload.get("inputs") or []:
        if entry.get("name") != CONTROL_INPUT:
            continue
        rollup = str(entry.get("rollup_sha256") or "")
        if (
            entry.get("path") == control_path()
            and len(rollup) == 64
            and set(rollup) <= set("0123456789abcdef")
            and set(rollup) != {"0"}
        ):
            return rollup
    return None


def render_randomised_extraction() -> str:
    arm = source(ARM_B_CONFIG)
    task = {
        "kind": "extract_embeddings",
        "manifest_artifact": arm["task"]["manifest_artifact"],
        "staged_artifact": arm["task"]["staged_artifact"],
        "out_version": CONTROL_VERSION,
        "batch_size": 32,
        "sets": [{
            "backbone": arm["task"]["backbone"],
            "init": arm["task"]["init"],
            "geometry": arm["task"]["geometry"],
            "randomise": True,
        }],
    }
    payload = {
        "schema_version": 1,
        "phase": "p8",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        # The manifest and staged sets only -- no checkpoint, because arm B
        # is an imagenet init, and no embeddings input, because this run
        # PRODUCES one.
        "inputs": [
            dict(entry) for entry in arm["inputs"]
            if entry["name"] != "embeddings"
        ],
        "task": task,
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    control = phase8.COMPONENT_ROLE_CONTROL_IS_A_REEXTRACTION
    collapse = phase8.THE_RANDOMISED_BACKBONE_COLLAPSES
    return (
        "# PHASE 8 — ARM B'S COMPONENT-ROLE CONTROL: THE RANDOMISED BACKBONE\n"
        "#\n"
        "# GENERATED by scripts/generate_phase8_configs.py from cleft.phase8\n"
        f"# and {ARM_B_CONFIG}.\n"
        "#\n"
        "# **WHY THIS IS AN EXTRACTION AND NOT AN ARM.** Arm A randomises a\n"
        "# backbone it runs live, so its map is recomputed on the same pass.\n"
        "# Arm B's map arrives precomputed, so randomising those parameters at\n"
        f"# cleft time changes NOTHING -- measured, bitwise, over all\n"
        f"# {phase8.COMPONENT_ROLE_IS_A_NO_OP['backbone_parameters']:,}\n"
        "# of them. The only place the same intervention exists for arm B is\n"
        "# extraction, which is where its representation is computed. Same\n"
        "# shape as the per-fold BN re-extraction: what is baked into an\n"
        "# artifact is not reachable from the arm that consumes it.\n"
        "#\n"
        "# **PARAMETERS, NOT BUFFERS**, matching arm A exactly. BatchNorm\n"
        "# running statistics are buffers and stay as they are; touching them\n"
        "# would be a second difference between the arms, and the comparison\n"
        "# exists to have one.\n"
        "#\n"
        "# **NO pretrained_init INPUT, DELIBERATELY.** The noise is matched to\n"
        "# each parameter's OWN spread, so the pretrained weights set the noise\n"
        "# scale and the route to them is not incidental. The real set this\n"
        "# controls for (p7_extract_g1_ladder.yaml, embeddings_g1_ladder_v1)\n"
        "# predates the declared-init mechanism and downloaded its weights at\n"
        "# run time. Declaring a snapshot here would make the control differ\n"
        "# from the real set in TWO things -- the randomisation and the weight\n"
        "# source -- and the comparison exists to have one. The run record says\n"
        "# pretrained_init.declared: false, which is the accurate statement.\n"
        "#\n"
        "# **THE ENDPOINT ONLY.** The adopted criterion reads the final stage,\n"
        "# so one artifact answers it. A cumulative curve would be one\n"
        "# extraction per stage, for a curve arm A's own run does not have\n"
        "# (phase8.ARM_A_RANDOMISATION_RESTARTS_DIRTY).\n"
        "#\n"
        "# **[MEASURED] WHAT THIS SET WILL LOOK LIKE, WRITTEN DOWN FIRST.**\n"
        "# The randomised Xception ignores its input: four deliberately\n"
        "# dissimilar probe images gave maps differing by\n"
        f"# {collapse['srgnn']['randomised_between_patient_max_difference']:.2e}\n"
        f"# against a real "
        f"{collapse['srgnn']['real_between_patient_max_difference']:.3f} --\n"
        "# eight orders of magnitude, still finite. The SAME walk on ViT does\n"
        "# NOT collapse, so this is the architecture rather than the\n"
        "# intervention. Expect near-identical rows; that is the control\n"
        "# working, not a broken extraction.\n"
        "# phase8.THE_RANDOMISED_BACKBONE_COLLAPSES.\n"
        "#\n"
        "# **THIS SET IS A CONTROL AND MUST NEVER TRAIN AN ARM.** It is named\n"
        f"# {control_set_name()},\n"
        "# marked in its own metadata, and embeddings.check_pairing refuses it\n"
        "# for any consumer that did not ask for one -- and refuses a real set\n"
        "# for one that did. Both directions, because both are silent.\n"
        "#\n"
        f"# CONSUMED BY: configs/p8_node_weights.yaml, as {CONTROL_INPUT!r},\n"
        "# where its rollup is an all-zeros PLACEHOLDER until this run has\n"
        "# built the set and declare_inputs.py has hashed it.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p8_randomised_extract.yaml\"\n\n"
    ) + body


def render_node_weights() -> str:
    arm = source(ARM_B_CONFIG)
    task = {"kind": "node_weights"}
    for name in ("manifest_artifact", "staged_artifact", "embeddings_artifact"):
        task[name] = arm["task"][name]
    task["randomised_embeddings_artifact"] = CONTROL_INPUT
    missing = [name for name in ARM_B_COPIED if name not in arm["task"]]
    if missing:
        raise SystemExit(f"{ARM_B_CONFIG} no longer carries {missing}")
    task.update({name: arm["task"][name] for name in ARM_B_COPIED})
    if arm["task"].get("checkpoint"):
        task["checkpoint"] = arm["task"]["checkpoint"]
    if arm["task"].get("deterministic") is not None:
        task["deterministic"] = arm["task"]["deterministic"]

    # The control set's hash is CARRIED from the declare pass when it is
    # filled, and an all-zero placeholder until then. Guard 3 refuses the
    # placeholder, which is the intended behaviour -- the node-weight run
    # cannot start before its control is built and declared.
    control_rollup = carried_control_rollup()
    inputs = [dict(entry) for entry in arm["inputs"]] + [{
        "name": CONTROL_INPUT,
        "path": control_path(),
        "rollup_sha256": control_rollup or "0" * 64,
    }]
    payload = {
        "schema_version": 1,
        "phase": "p8",
        "tier": "keeper",
        "seed": arm["task"]["seeds"][0],
        "inputs": inputs,
        "task": task,
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    gate = phase8.SRGNN_NODE_WEIGHTS_R10_READ["refit_gate"]
    count = phase8.SRGNN_NODE_WEIGHTS_R10_READ["the_count_is_26_plus_the_whole_image"]
    sample = phase8.ARM_B_SAMPLE_DECIDED
    return (
        "# PHASE 8 — ARM B'S NODE WEIGHTS, GATED TWICE\n"
        "#\n"
        "# GENERATED by scripts/generate_phase8_configs.py from cleft.phase8\n"
        f"# and {ARM_B_CONFIG}. The hyperparameters are COPIED from arm B,\n"
        "# not retyped: this run refits arm B's fifty models and gates on\n"
        f"# reproducing {gate['expected_pcc']}, and a mistyped learning rate\n"
        "# would fail that gate after ten seeds of fitting.\n"
        "#\n"
        "# **GATE 1 — the refit must BE arm B.** Pooled mean over\n"
        f"# {gate['seeds']} seeds within {gate['tolerance']} of\n"
        f"# {gate['expected_pcc']}, or these are not arm B's models and every\n"
        "# weight would describe a different one. Nothing is read.\n"
        "#\n"
        "# **GATE 2 — the randomisation test.** Node weights are an\n"
        "# EXPLANATION, so Adebayo's sanity check applies to them: an ungated\n"
        "# graph explanation beside a gated transformer one is the asymmetry\n"
        "# the both-families comparison exists to avoid. The criterion is the\n"
        "# phase-level separability interval; per-patient figures are\n"
        "# PERCENTILES and decide nothing (phase8.RANDOMISATION_CRITERION_ADOPTED).\n"
        "#\n"
        "# **TWO MODES, RANDOMISED BY TWO DIFFERENT ROUTES.**\n"
        "# explanation_source walks the trained graph layers at cleft time --\n"
        "# the parameters that actually produce region_w.\n"
        f"# {node_weights.COMPARISON_MODE} CANNOT be a parameter walk here:\n"
        f"# randomising all "
        f"{phase8.COMPONENT_ROLE_IS_A_NO_OP['backbone_parameters']:,} backbone\n"
        "# parameters at cleft time leaves region_w BITWISE identical, because\n"
        "# the artifact-fed path enters below the backbone and the frozen\n"
        "# representation is an INPUT here rather than a computation. It would\n"
        "# have reported similarity 1.0 and the gate would have read that as\n"
        "# the explanation SURVIVING randomisation -- the worst verdict, from a\n"
        "# test that changed nothing. So it runs off the CONTROL SET instead:\n"
        f"# {CONTROL_INPUT!r}, the same map re-extracted from a randomised\n"
        "# backbone (configs/p8_randomised_extract.yaml). Without that input\n"
        "# declared the mode does not run and the A<->B comparison is reported\n"
        "# UNAVAILABLE -- which is not the same as unresolved.\n"
        "# phase8.COMPONENT_ROLE_IS_A_NO_OP,\n"
        "# phase8.COMPONENT_ROLE_CONTROL_IS_A_REEXTRACTION.\n"
        "#\n"
        "# **[MEASURED] THE CONTROL MAY COLLAPSE, AND THE READING IS ALREADY\n"
        "# REGISTERED.** The randomised backbone ignores its input (maps differ\n"
        "# between patients by 5.96e-08 against a real 4.96), and with an\n"
        "# UNTRAINED head that drives the 26 region weights to exactly uniform.\n"
        "# gradcam.similarity returns 0.0 for a vector with no rank structure,\n"
        "# so a collapse would read as 0.0 for all 237 -- below any baseline,\n"
        "# gate resolves, spectacular pass, measuring nothing. Whether arm B's\n"
        "# TRAINED attention keeps rank structure cannot be known before this\n"
        "# runs. node_weights.degeneracy checks it, all three readings are\n"
        "# registered in advance, and the verdict travels inside the gate.\n"
        "#\n"
        f"# {count['n_regions']} NODES, {count['n_rois']} RANKED. The whole\n"
        "# feature map is appended as the last node before attention, so one\n"
        "# entry is not a region at all. It is split off and reported\n"
        "# separately: a shared near-constant element inflates the\n"
        "# between-patient baseline, and that baseline is the bar a randomised\n"
        "# vector must fall BELOW.\n"
        "#\n"
        f"# TWO SAMPLES, TWO QUESTIONS: the arm's own gate on all\n"
        f"# {sample['own_gate']['n']} patients "
        f"({sample['own_gate']['baseline_pairs']:,} baseline pairs), the\n"
        f"# A<->B-scoped figures on the shared "
        f"{sample['a_vs_b_comparison']['n']}. If the interval does not resolve\n"
        "# it is reported UNRESOLVED, not rescued by quoting the other sample\n"
        "# or by switching statistic afterwards.\n"
        "#\n"
        "# Each patient is explained by the fold-model that HELD THEM OUT, at\n"
        "# every seed, with per-seed agreement reported rather than averaged\n"
        "# away. phase8.SRGNN_NODE_WEIGHTS_R10_READ.\n"
        "#\n"
        + (
            (
                f"# **{CONTROL_INPUT}'s rollup is the declare pass's own "
                "figure** --\n"
                "# filled 2026-08-14 after configs/p8_randomised_extract.yaml\n"
                "# built the set, and CARRIED by this generator, never typed.\n"
                "# If the control is ever rebuilt, re-run declare_inputs.py;\n"
                "# guard 3 refuses a stale hash.\n"
            )
            if carried_control_rollup() is not None
            else (
                f"# **{CONTROL_INPUT}'s rollup is an all-zeros PLACEHOLDER.** "
                "The\n"
                "# control set does not exist until "
                "configs/p8_randomised_extract.yaml\n"
                "# has run; hashes come only from declare_inputs.py against a "
                "built\n"
                "# artifact, never typed. Guard 3 will refuse this run until "
                "it is\n"
                "# filled, which is the placeholder working: the node-weight "
                "run must\n"
                "# not start before its control exists.\n"
            )
        )
        + "#\n"
        "# ORDER: p8_randomised_extract.yaml, then declare_inputs.py, then\n"
        "# this.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p8_node_weights.yaml\"\n\n"
    ) + body



#: The two Phase 6 cells the SCUT animation reruns (the maintainer's
#: comparability prior), and the SHIPPED deliverables the reruns are
#: compared against. The pretrained.npz FILE paths are the ones
#: p6_extract_embeddings.yaml already declares, so their verified hashes
#: CARRY (one path, one hash, no second cluster round trip).
P6_CELL_CONFIGS = {
    "original": "p6_pretrain_vit_b16_original.yaml",
    "masked_g1": "p6_pretrain_vit_b16_masked_g1.yaml",
}
SHIPPED_P6_PRETRAINED = {
    "original": (
        f"{CLUSTER_ROOT}/runs/keeper/p6/"
        "p6_pretrain_vit_b16_original__5e927402__p6-pt-vit-original-v2/"
        "pretrained.npz"
    ),
    "masked_g1": (
        f"{CLUSTER_ROOT}/runs/keeper/p6/"
        "p6_pretrain_vit_b16_masked_g1__5e927402__p6-pt-vit-g1-v2/"
        "pretrained.npz"
    ),
}
INIT_VIT_B16_PATH = f"{CLUSTER_ROOT}/data/inits/init_vit_b16_v1"

#: Copied from each cell's own config, never retyped: the rerun IS the
#: cell, and a mistyped epoch count would fail the fingerprint gate after
#: thirty epochs for a reason nobody would expect.
COPIED_P6 = (
    "backbone", "source", "region_scheme", "expect_train", "expect_test",
    "epochs", "inner_val_frac", "monitor", "deterministic",
    "learning_rate", "weight_decay", "batch_size", "checkpoint_every",
)


def render_tsne() -> str:
    arm = source()
    inputs_by_name = {e["name"]: e for e in arm["inputs"]}
    spec = phase8.TSNE_COMPANION
    payload = {
        "schema_version": 1,
        "phase": "p8",
        "tier": "keeper",
        "seed": phase8.TSNE["seed"],
        "inputs": [
            dict(inputs_by_name["manifest_v1"]),
            dict(inputs_by_name["embeddings"]),
        ],
        "task": {
            "kind": "tsne",
            "manifest_artifact": "manifest_v1",
            "embeddings_artifact": "embeddings",
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 8 — THE t-SNE WITH ITS COMPANION. A FIGURE, NEVER\n"
        "# EVIDENCE.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase8_configs.py from cleft.phase8\n"
        f"# and {SOURCE_CONFIG} (the subject set's verified entries,\n"
        "# carried). LAUNCH-READY: both inputs are already-declared paths.\n"
        "#\n"
        "# **THE REGISTRATION IS NOT HERE.** Perplexities (5, 30), seed\n"
        "# 1337, never tuned on the result, and the companion's full spec\n"
        "# live in phase8.TSNE and phase8.TSNE_COMPANION (resolved\n"
        "# 2026-08-15 by the maintainer after the build stopped on the two\n"
        "# unfixed choices -- phase8.TSNE_BUILD_BLOCKED_ON_TWO_CHOICES).\n"
        "#\n"
        f"# SUBJECT: {spec['embeddings']}\n"
        "# (arm A's pooled set; the task REFUSES any other directory).\n"
        f"# COMPANION: leave-one-out k-NN, k={spec['k']} committed blind,\n"
        f"# on {spec['classes']} "
        f"(counts {spec['expected_class_counts']}, asserted); patient\n"
        f"# bootstrap {spec['n_boot']:,} draws, seed "
        f"{spec['bootstrap_seed']}; chance AND majority-class\n"
        "# baselines printed beside the accuracy -- the number is\n"
        "# unreadable without that bar.\n"
        "#\n"
        "# **THE DISPLAY RULE IS STRUCTURAL**: the figure function refuses\n"
        "# a missing companion, so a separation figure without its number\n"
        "# beside it cannot exist.\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        "#     python -m cleft.run --config configs/p8_tsne.yaml\"\n\n"
    ) + body


def render_scut_animation(variant: str) -> str:
    cell = source(P6_CELL_CONFIGS[variant])
    known = _known_hashes_by_path()
    config_name = f"p8_scut_anim_{variant}.yaml"
    cell_inputs = {e["name"]: e for e in cell["inputs"]}

    def entry(name, path):
        return {
            "name": name,
            "path": path,
            "rollup_sha256": known.get(
                path, _carried(config_name, name, path)
            ),
        }

    shipped_path = SHIPPED_P6_PRETRAINED[variant]
    inputs = [dict(cell_inputs["scut_root"])]
    if variant != "original":
        inputs.append(dict(cell_inputs[pretrain_module.MASKED_INPUT_NAME]))
    inputs.append(entry(pretrain_module.INIT_INPUT_NAME, INIT_VIT_B16_PATH))
    inputs.append(entry("shipped_pretrained", shipped_path))

    task = {
        "kind": "scut_animation",
        "scut_root": "scut_root",
        "shipped_artifact": "shipped_pretrained",
    }
    missing = [name for name in COPIED_P6 if name not in cell["task"]]
    if missing:
        raise SystemExit(
            f"{P6_CELL_CONFIGS[variant]} no longer carries {missing}"
        )
    task.update({name: cell["task"][name] for name in COPIED_P6})

    payload = {
        "schema_version": 1,
        "phase": "p8",
        "tier": "keeper",
        "seed": cell["seed"],
        "inputs": inputs,
        "task": task,
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    built = phase8.SCUT_ANIMATION_BUILT
    faces = phase8.SCUT_ANIMATION_FACES
    unresolved = sum(
        1 for e in payload["inputs"] if set(e["rollup_sha256"]) == {"0"}
    )
    return (
        f"# PHASE 8 — THE SCUT TRAINING ANIMATION, {variant.upper()}\n"
        "# VARIANT: Grad-CAM evolving as the backbone itself learns\n"
        "# beauty. phase8.SCUT_ANIMATION_BUILT is the registration.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase8_configs.py from\n"
        f"# cleft.phase8 and {P6_CELL_CONFIGS[variant]} -- the training\n"
        "# block is COPIED from the cell's own config, never retyped: this\n"
        "# run IS a rerun of that cell, through run_pretraining's\n"
        "# epoch-end observation hook, frames rendered in-run.\n"
        "#\n"
        "# **THE SELF-GATE IS THE CORRECTED ONE.** Byte reproduction of a\n"
        "# ViT pretraining run DOES NOT EXIST: the masked-G1 cell itself\n"
        "# ran three times at identical config and gave test PCC\n"
        "# 0.7893/0.8120/0.8194 (roadb.VIT_PRETRAINING_IS_NONDETERMINISTIC),\n"
        "# and today's builder trains ViT unfused, a procedure the shipped\n"
        "# fused cells never ran. So: fingerprint mismatch REFUSES (before\n"
        f"# thirty epochs, not after); |rerun - shipped| test PCC beyond\n"
        f"# {built['self_gate']['band']} (twice the recorded spread, fixed"
        " blind) raises LAST\n"
        "# after every artifact is written; per-array byte identity is\n"
        "# REPORTED, expected False, never gated on. The rerun is the\n"
        "# CURRENT procedure's own draw of the cell.\n"
        "#\n"
        f"# FACES BY RULE ({faces['n_strata']} strata x "
        f"{faces['per_stratum']}, seed {faces['seed']}, test split):\n"
        "# the SAME source faces in both variants by construction -- the\n"
        "# split files are shared and the rule reads only (stems, scores,\n"
        "# seed). phase8.SCUT_ANIMATION_FACES.\n"
        "#\n"
        "# FRAMES per face: epoch 0 = the PHOTOGRAPH (the head is\n"
        "# zero-initialised -- identically-zero gradient, no map: the 8c\n"
        "# zero-init precedent), epochs 1..30 composited heat, plus the\n"
        "# SHIPPED cell's selected weights as the labelled endpoint frame.\n"
        "# APNG assembled from the on-disk frames, so a resumed run keeps\n"
        "# what it already rendered.\n"
        "#\n"
        "# **REFUSALS ARE DATA (registered 2026-08-16, after the first\n"
        "# launch crashed on one)**: near-zero gradients in EARLY epochs\n"
        "# can leave a face's whole map at zero -- the method's own\n"
        "# refusal fires, the cell is recorded all_zero in the metrics\n"
        "# ledger (8b's shape), the frame is the photograph with the\n"
        "# measured-refusal caption, and the run continues. A refusal at\n"
        "# the final epoch or on the shipped weights is OUT of mechanism:\n"
        "# everything writes, then the run raises LAST.\n"
        "# phase8.SCUT_ANIMATION_REFUSAL_HANDLING.\n"
        "#\n"
        "# SHAREABLE THROUGHOUT: SCUT is public, and the masked artifact\n"
        "# derives from aggregate cohort aspect-ratio statistics -- no\n"
        "# patient image or identity. NOT cluster-bound.\n"
        "#\n"
        "# **CAPTION RULE (registered 2026-08-15, before launch --\n"
        "# phase8.SCUT_ANIMATION_CAPTION_RULE)**: the recipe sentence is\n"
        "# burned beneath every animation frame (a training run of the\n"
        "# same recipe, NOT the run that produced the shipped weights);\n"
        "# a static panel per face puts the trajectory's own final frame\n"
        "# BESIDE the shipped-weights endpoint, and any visible\n"
        "# difference is captioned as the recorded nondeterminism made\n"
        "# visual, with the face's measured largest per-cell map\n"
        "# difference beneath -- never smoothed or hidden.\n"
        "#\n"
        + (
            (
                f"# {unresolved} hash(es) below are all-zeros PLACEHOLDERS "
                "pending a\n"
                "# declare pass. Every other entry is a verified figure,\n"
                "# carried.\n"
            )
            if unresolved
            else (
                "# FULLY DECLARED: every hash below is a declare pass's own\n"
                "# figure, CARRIED from the shipped configs that already\n"
                "# declare these paths (p6 cells, p6_extract_embeddings,\n"
                "# the roadb init snapshot) -- never typed.\n"
            )
        )
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{config_name}\"\n\n"
    ) + body


#: Every Phase 8 config, and the function that derives it.
CONFIGS = {
    "p8_grad_cam.yaml": render,
    "p8_grad_cam_softmax.yaml": render_softmax_variant,
    # The control BEFORE its consumer, which is also the order they run in.
    "p8_randomised_extract.yaml": render_randomised_extraction,
    "p8_node_weights.yaml": render_node_weights,
    "p8c_sheet.yaml": render_phase8c_sheet,
    "p8c_animation.yaml": render_phase8c_animation,
    "p8_tsne.yaml": render_tsne,
    "p8_scut_anim_original.yaml": lambda: render_scut_animation("original"),
    "p8_scut_anim_masked_g1.yaml": lambda: render_scut_animation("masked_g1"),
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    print(
        f"arm A's hyperparameters copied from {SOURCE_CONFIG} "
        f"({phase8.STRATIFIED_SAMPLE['n_total']} patients); arm B's from "
        f"{ARM_B_CONFIG} (gate "
        f"{phase8.SRGNN_NODE_WEIGHTS_R10_READ['refit_gate']['expected_pcc']}, "
        f"walk {list(node_weights.PARAMETER_WALK_MODES)}, control "
        f"{list(node_weights.CONTROL_SET_MODES)})"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
