"""Write Phase 13's stop-1 configs from the shipped inputs.

    PYTHONPATH=src python scripts/generate_phase13_configs.py [--check]

Two configs: the SCUT embedding extraction and the decoder shakedown.
The masked-SCUT and scut-root entries are CARRIED VERBATIM from the
shipped pretraining config, so their hashes need no round trip. The
decoder config's embedding-artifact hash is a documented placeholder
until the extraction runs -- the standing two-pass flow.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

from cleft import phase13  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"
PLACEHOLDER = "0" * 64
PRETRAIN_CONFIG = "p6_pretrain_vit_b16_masked_g1.yaml"
LADDER_CONFIG = "p7_d1_vit_b16_imagenet_g1.yaml"
EXTRACT_NAME = "p13_extract_scut.yaml"
DECODER_NAME = "p13_scut_decoder.yaml"
COHORT_NAME = "p13_cohort_reconstruct.yaml"
SCUT_EMBEDDINGS_PATH = (
    f"{CLUSTER_ROOT}/data/embeddings/scut_masked_decoder_v1"
)
DECODER_RUN_PENDING = (
    f"{CLUSTER_ROOT}/runs/keeper/p13/PENDING_p13_scut_decoder"
)


def source(name: str) -> dict:
    return yaml.safe_load((REPO / "configs" / name).read_text(encoding="utf-8"))


def _carried_hash(config_name: str, input_name: str, path: str) -> str:
    shipped = REPO / "configs" / config_name
    if not shipped.is_file():
        return PLACEHOLDER
    payload = yaml.safe_load(shipped.read_text(encoding="utf-8")) or {}
    for entry in payload.get("inputs") or []:
        if entry.get("name") == input_name and entry.get("path") == path:
            rollup = str(entry.get("rollup_sha256") or "")
            if len(rollup) == 64 and set(rollup) != {"0"}:
                return rollup
    return PLACEHOLDER


def _scut_inputs() -> list[dict]:
    """masked_scut and scut_root, carried verbatim from the pretraining
    config -- same paths, same verified hashes."""
    pretrain = {e["name"]: e for e in source(PRETRAIN_CONFIG)["inputs"]}
    return [dict(pretrain["masked_scut"]), dict(pretrain["scut_root"])]


def render_extract() -> str:
    payload = {
        "schema_version": 1,
        "phase": "p13",
        "tier": "keeper",
        "seed": 1337,
        "inputs": _scut_inputs(),
        "task": {
            "kind": "extract_scut_embeddings",
            "masked_scut": "masked_scut",
            "scut_root": "scut_root",
            "backbone": "vit_b16",
            "init": "imagenet",
            "geometry": "g1",
            "out_version": "scut_masked_decoder_v1",
            "expect_train": 3300,
            "expect_test": 2199,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 13 — STOP 1: FROZEN imagenet ViT-B/16 EMBEDDINGS OVER\n"
        "# THE MASKED SCUT ARTIFACT, G1 224. phase13.SCUT_SHAKEDOWN_PLAN.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase13_configs.py. Both inputs\n"
        "# carried verbatim from the shipped pretraining config.\n"
        "#\n"
        "# **SHAREABLE THROUGHOUT** -- SCUT is public (phase8's governance\n"
        "# confirmation). The artifact is decoder.save_scut_embeddings'\n"
        "# own values+stems format, deliberately NOT the cleft\n"
        "# embeddings-set format, whose loaders enforce cleft-manifest\n"
        "# semantics. The save layer owns existence and creation -- the\n"
        "# guard-after-mkdir lesson, applied at build time.\n"
        "#\n"
        "# Split counts asserted: 3,300 train / 2,199 test (the official\n"
        "# split, CM152 excluded -- the criteria's '3300/2200' names the\n"
        "# split; 2,199 is the count that runs).\n"
        "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{EXTRACT_NAME}\"\n\n"
    ) + body


def render_decoder() -> str:
    ladder = {e["name"]: e for e in source(LADDER_CONFIG)["inputs"]}
    inputs = _scut_inputs() + [
        {
            "name": "scut_embeddings",
            "path": SCUT_EMBEDDINGS_PATH,
            "rollup_sha256": _carried_hash(
                DECODER_NAME, "scut_embeddings", SCUT_EMBEDDINGS_PATH
            ),
        },
        dict(ladder["staged_v1"]),
    ]
    payload = {
        "schema_version": 1,
        "phase": "p13",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": {
            "kind": "train_scut_decoder",
            "scut_embeddings": "scut_embeddings",
            "masked_scut": "masked_scut",
            "scut_root": "scut_root",
            "cleft_staged": "staged_v1",
            "geometry": "g1",
            "epochs": 30,
            "batch_size": 64,
            "learning_rate": 0.001,
            "inner_val_frac": 0.1,
            "ssim_inner_sample": 64,
            "sheet_worst": 24,
            "sheet_sample": 96,
            "expect_train": 3300,
            "expect_test": 2199,
        },
    }
    unresolved = sum(
        1 for e in payload["inputs"] if set(e["rollup_sha256"]) == {"0"}
    )
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    provenance = (
        f"# **{unresolved} HASH(ES) ARE ALL-ZERO PLACEHOLDERS** (the SCUT\n"
        "# embedding set exists only after p13_extract_scut runs). Fill\n"
        "# via declare_inputs.py; guard 3 refuses until real.\n"
        if unresolved else
        "# **RESOLVED.** Every input declared with a verified hash.\n"
    )
    return (
        "# PHASE 13 — STOP 1: THE DECODER SHAKEDOWN. TRAIN ON THE 3,300\n"
        "# FIT SIDE, RECONSTRUCT THE 2,199 HELD-OUT, WRITE THE BAND\n"
        "# BASELINE AND THE COMPARABILITY TABLE, RENDER THE SHEETS.\n"
        "# phase13.STOP_1_BUILT; phase13.DOUBLE_DIFFERENCE_RULE.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase13_configs.py.\n"
        "#\n"
        "# **NO COHORT PIXEL IS GENERATED HERE.** staged_v1 is read ONLY\n"
        "# for the comparability table's content statistics (band\n"
        "# content-pixel fraction and variance); no cleft embedding\n"
        "# passes through the decoder in this run. The cohort arm is\n"
        "# stop 2, behind the cleft_reconstruction_acknowledged gate.\n"
        "#\n"
        "# **THE PRETRAINING DISCIPLINE**: fixed 30-epoch budget, best\n"
        "# checkpoint by inner L2, NO early stopping; every epoch's\n"
        "# checkpoint and curve row written (criterion 7). L2 trains;\n"
        "# SSIM is REPORTED, never optimised -- optimising a perceptual\n"
        "# metric would bake 'looks face-like' into the objective, the\n"
        "# registered failure mode by construction.\n"
        "#\n"
        "# **THE SHEETS**: held-out reconstructions, original beside\n"
        "# reconstruction, WORST 24 by L2 first, then a seeded sample of\n"
        "# 96 -- ten sheets, SHAREABLE (SCUT is public), for the maintainer's\n"
        "# eye BEFORE any cohort pixel exists (exit criterion 1).\n"
        "# Metrics are computed over ALL 2,199, not the sheet sample.\n"
        "#\n"
        "# **THE DOUBLE DIFFERENCE'S DENOMINATOR is written by this run**\n"
        "# (scut_band_baseline.json): per-band mean MSE over CONTENT\n"
        "# pixels (white >= 250/channel excluded, BOTH families -- the\n"
        "# registered mitigation for the baked-white baseline defect).\n"
        "# The comparability table reports per-band content variance for\n"
        "# both families; any band whose ratio exceeds 2x gets a caveat\n"
        "# ATTACHED to the double difference -- report, never gate.\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{DECODER_NAME}\"\n\n"
    ) + body


def _carried_cohort_flag(path=None) -> bool:
    """the maintainer's acknowledgement, carried from the shipped config.

    A fresh render writes ``false``; only an existing ``true`` in the
    shipped config survives regeneration -- the basal three-state carry,
    so the flag can become true ONLY by a deliberate edit, which keeps
    ``--check`` clean (phase13.CLEFT_RECONSTRUCTION_GATE)."""
    path = path or REPO / "configs" / COHORT_NAME
    if not path.is_file():
        return False
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return (
        payload.get("task", {}).get("cleft_reconstruction_acknowledged")
        is True
    )


def _carried_decoder_run(path=None) -> dict:
    """The shakedown run-dir input, three-state: a fresh render writes
    the PENDING path with a placeholder hash; a pasted real path
    survives regeneration even while its hash is still a placeholder;
    a declared hash rides with it thereafter."""
    path = path or REPO / "configs" / COHORT_NAME
    pending = {
        "name": "decoder_run",
        "path": DECODER_RUN_PENDING,
        "rollup_sha256": PLACEHOLDER,
    }
    if not path.is_file():
        return pending
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    for entry in payload.get("inputs") or []:
        if entry.get("name") == "decoder_run" and (
            "/PENDING_" not in str(entry.get("path", ""))
        ):
            return dict(entry)
    return pending


def render_cohort() -> str:
    ladder = {e["name"]: e for e in source(LADDER_CONFIG)["inputs"]}
    acknowledged = _carried_cohort_flag()
    decoder_run = _carried_decoder_run()
    inputs = [
        decoder_run,
        dict(ladder["embeddings"]),
        dict(ladder["manifest_v1"]),
        dict(ladder["staged_v1"]),
    ]
    payload = {
        "schema_version": 1,
        "phase": "p13",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": {
            "kind": "reconstruct_cohort",
            "decoder_run": "decoder_run",
            "checkpoint_epoch": 20,
            "cleft_embeddings": "embeddings",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "geometry": "g1",
            "cleft_reconstruction_acknowledged": acknowledged,
            "expect_patients": 237,
            "batch_size": 32,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    pending = "/PENDING_" in decoder_run["path"]
    unresolved = set(decoder_run["rollup_sha256"]) == {"0"}
    if pending:
        provenance = (
            "# **THE decoder_run PATH IS PENDING and its hash an ALL-ZERO\n"
            "# PLACEHOLDER.** A run directory carries a SHA and a job id,\n"
            "# neither derivable on a laptop. Two passes: paste the\n"
            "# shakedown run directory (path), then declare_inputs.py\n"
            "# (hash). Guard 3 refuses the run until both are real.\n"
        )
    elif unresolved:
        provenance = (
            "# **PATH RESOLVED, HASH PENDING.** The decoder_run path is a\n"
            "# real run directory; its hash is an all-zero placeholder\n"
            "# until declare_inputs.py verifies the files.\n"
        )
    else:
        provenance = (
            "# **RESOLVED.** Every input declared at a real path with a\n"
            "# verified hash.\n"
        )
    gate_line = (
        "# **cleft_reconstruction_acknowledged: true -- A DATED\n"
        "# CONFIRMATION, CARRIED.** Set by a dated edit, carried by the\n"
        "# generator; the task runs.\n"
        if acknowledged else
        "# **cleft_reconstruction_acknowledged: false -- THE TASK WILL\n"
        "# REFUSE.** A reconstructed cleft face is a GENERATED\n"
        "# PATIENT-DERIVED image, a new kind of output the REC approvals'\n"
        "# crop conditions never contemplated. the maintainer confirms by\n"
        "# editing this flag to true; the generator CARRIES that edit, so\n"
        "# --check stays clean and code never sets it here\n"
        "# (phase13.CLEFT_RECONSTRUCTION_GATE).\n"
    )
    return (
        "# PHASE 13 — STOP 2: THE COHORT RECONSTRUCTIONS. ALL 237\n"
        "# PATIENTS THROUGH THE SHAKEDOWN DECODER'S EPOCH-20 CHECKPOINT\n"
        "# (AS PICKED, phase13.STOP_1_REVIEWED), CLUSTER-ONLY\n"
        "# SHEETS FOR REVIEW ON THE CLUSTER. phase13.STOP_2_BUILT.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase13_configs.py.\n"
        "#\n"
        "# **EVERY RECONSTRUCTION IS CLUSTER-ONLY WITHOUT EXCEPTION.**\n"
        "# The raw reconstruction tensor is deliberately not persisted:\n"
        "# generated cohort pixels exist in the sheets alone. The\n"
        "# per-patient band figures (cleft_band_errors.json) are numbers,\n"
        "# banked as the double difference's numerator side; NO double\n"
        "# difference is computed here -- that is stop 3's, with the\n"
        "# bound readings applied where they fire and\n"
        "# phase13.SCUT_NORMAL_PRIOR travelling by name.\n"
        "#\n"
        + gate_line
        + "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{COHORT_NAME}\"\n\n"
    ) + body


REGIONAL_NAME = "p13_regional.yaml"
ASYMMETRY_NAME = "p13_asymmetry.yaml"
RECON_EXTRACT_NAME = "p13_extract_recon.yaml"
PROBE_NAME = "p13_probe_recon.yaml"
COHORT_RUN_PENDING = (
    f"{CLUSTER_ROOT}/runs/keeper/p13/PENDING_p13_cohort_reconstruct"
)
RECON_EMBEDDINGS_PATH = (
    f"{CLUSTER_ROOT}/data/embeddings/embeddings_recon_v1"
)
IEM_CONFIG = "p11_iem_arm.yaml"


def _cohort_entry(name: str) -> dict:
    """One input carried VERBATIM from the shipped cohort config -- same
    path, same verified hash. The stop-2 config already resolved the
    shakedown run directory and the ladder inputs, so stop 3 inherits
    them rather than re-declaring a second copy to drift."""
    shipped = REPO / "configs" / COHORT_NAME
    if shipped.is_file():
        payload = yaml.safe_load(shipped.read_text(encoding="utf-8")) or {}
        for entry in payload.get("inputs") or []:
            if entry.get("name") == name:
                return dict(entry)
    return {"name": name, "path": f"PENDING_{name}", "rollup_sha256": PLACEHOLDER}


def _cohort_flag() -> bool:
    """the maintainer's acknowledgement, carried from the shipped cohort config.

    Stop 3's regenerating tasks inherit the SAME decision rather than
    asking for a second edit of the same judgement: generating cohort
    reconstructions was acknowledged, and regenerating them in memory is
    that act (phase13.CLEFT_RECONSTRUCTION_GATE)."""
    return _carried_cohort_flag()


def _scoresheet_entry() -> dict:
    """The primary score sheet, carried verbatim from the shipped IEM
    config -- the same sheet whose Median column Phase 11 trained on."""
    for entry in source(IEM_CONFIG)["inputs"]:
        if entry["name"] == "scoresheet_primary":
            return dict(entry)
    raise SystemExit("p11_iem_arm.yaml declares no scoresheet_primary")


def _carried_named_entry(config_name: str, input_name: str) -> dict | None:
    """An entry the shipped config has already resolved, by name -- the
    three-state carry: a resolved PATH survives regeneration even while
    its hash is a placeholder, a PENDING path never does."""
    path = REPO / "configs" / config_name
    if not path.is_file():
        return None
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    for entry in payload.get("inputs") or []:
        if entry.get("name") == input_name and (
            "/PENDING_" not in str(entry.get("path", ""))
        ):
            return dict(entry)
    return None


def _cohort_run_entry(config_name: str) -> dict:
    return _carried_named_entry(config_name, "cohort_run") or {
        "name": "cohort_run",
        "path": COHORT_RUN_PENDING,
        "rollup_sha256": PLACEHOLDER,
    }


def _provenance(inputs: list) -> str:
    pending = sum(1 for e in inputs if "/PENDING_" in e["path"])
    unresolved = sum(
        1 for e in inputs if set(e["rollup_sha256"]) == {"0"}
    )
    if pending:
        return (
            f"# **{pending} PATH(S) PENDING and {unresolved} ALL-ZERO\n"
            "# PLACEHOLDER HASH(ES).** A run directory carries a SHA and\n"
            "# a job id, neither derivable on a laptop. Two passes: paste\n"
            "# the run directory (path), then declare_inputs.py (hash).\n"
            "# Guard 3 refuses until both are real -- the PLACEHOLDER\n"
            "# working, not a mistake.\n"
        )
    if unresolved:
        return (
            f"# **PATHS RESOLVED, {unresolved} ALL-ZERO PLACEHOLDER\n"
            "# HASH(ES) REMAIN.** Every path is real; declare_inputs.py\n"
            "# fills the rest and guard 3 refuses until it does.\n"
        )
    return (
        "# **RESOLVED.** Every input declared at a real path with a\n"
        "# verified hash.\n"
    )


def render_regional() -> str:
    inputs = [
        _cohort_run_entry(REGIONAL_NAME),
        _cohort_entry("decoder_run"),
        _cohort_entry("manifest_v1"),
        _scoresheet_entry(),
    ]
    payload = {
        "schema_version": 1,
        "phase": "p13",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": {
            "kind": "regional_comparison",
            "cohort_run": "cohort_run",
            "decoder_run": "decoder_run",
            "checkpoint_epoch": 20,
            "scoresheet_artifact": "scoresheet_primary",
            "manifest_artifact": "manifest_v1",
            "expect_patients": 237,
            "n_boot": 10000,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 13 — STOP 3, CHECKS (a) AND (b): THE DOUBLE DIFFERENCE\n"
        "# AND BAND ERROR vs GRADE. phase13.STOP_3_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase13_configs.py.\n"
        "#\n"
        "# **PURE ARITHMETIC ON BANKED ARTIFACTS.** Two JSON files\n"
        "# written by runs that already happened, plus the score sheet:\n"
        "# no pixels, no model, no reconstruction. This task CANNOT\n"
        "# regenerate a cohort image and therefore carries NO GATE --\n"
        "# the gate attaches to generated pixels, and there are none.\n"
        "# Pod arithmetic, not a GPU job.\n"
        "#\n"
        "# **BOTH READINGS ARE ALREADY COMMITTED**\n"
        "# (REGIONAL_COMPARISON_READINGS), and the SCUT-normal prior's\n"
        "# sentence is applied BY NAME whichever way it lands.\n"
        "# (b) is DESCRIPTIVE, report-never-gate, and its registered\n"
        "# limit -- necessary, not sufficient -- rides in the output.\n"
        "#\n"
        + _provenance(inputs)
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{REGIONAL_NAME}\"\n\n"
    ) + body


def render_asymmetry() -> str:
    acknowledged = _cohort_flag()
    inputs = [
        _cohort_entry("decoder_run"),
        _cohort_entry("embeddings"),
        _cohort_entry("manifest_v1"),
        _cohort_entry("staged_v1"),
        _scoresheet_entry(),
    ] + _scut_inputs() + [
        {
            "name": "scut_embeddings",
            "path": SCUT_EMBEDDINGS_PATH,
            "rollup_sha256": _carried_hash(
                DECODER_NAME, "scut_embeddings", SCUT_EMBEDDINGS_PATH
            ),
        },
    ]
    payload = {
        "schema_version": 1,
        "phase": "p13",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": {
            "kind": "asymmetry_retention",
            "decoder_run": "decoder_run",
            "checkpoint_epoch": 20,
            "cleft_embeddings": "embeddings",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "scoresheet_artifact": "scoresheet_primary",
            "masked_scut": "masked_scut",
            "scut_root": "scut_root",
            "scut_embeddings": "scut_embeddings",
            # The WHOLE held-out SCUT side. [2026-08-24] This was 237 --
            # the cohort's count, crossed into a SCUT field, which sized
            # the floor to an alphabetical 237-face prefix
            # (phase13.STOP_3_DEFECTS). It is now asserted, not chosen.
            "expect_scut_test": 2199,
            "geometry": "g1",
            "cleft_reconstruction_acknowledged": acknowledged,
            "expect_patients": 237,
            "batch_size": 32,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 13 — STOP 3, CHECK (c): ASYMMETRY RETENTION, THE DIRECT\n"
        "# TEST OF THE EYE'S CLAIM. phase13.STOP_3_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase13_configs.py.\n"
        "#\n"
        "# **REGENERATES COHORT RECONSTRUCTIONS IN MEMORY** from the\n"
        "# epoch-20 checkpoint and the frozen embeddings -- NOTHING is\n"
        "# written to disk, the no-persist boundary holding, and the\n"
        "# acknowledged gate rides with the regeneration (the SAME\n"
        "# decision the maintainer already made for stop 2, carried from that\n"
        "# config rather than asked again). A GPU job.\n"
        "#\n"
        "# **THE BLUR CAVEAT IS ANSWERED BY DESIGN**: smoothing shrinks\n"
        "# |left-right| everywhere, so raw retention sits below 1 for\n"
        "# all and only the RELATIVE comparison survives -- severe vs\n"
        "# mild, and both against the SCUT held-out reconstructions'\n"
        "# own floor, computed by the SAME function with the SAME mask\n"
        "# rule. Phase 4's anchor (r~0.158) is reported beside the\n"
        "# retention figures so nobody over-reads them.\n"
        "#\n"
        + _provenance(inputs)
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{ASYMMETRY_NAME}\"\n\n"
    ) + body


def render_recon_extract() -> str:
    acknowledged = _cohort_flag()
    inputs = [
        _cohort_entry("decoder_run"),
        _cohort_entry("embeddings"),
        _cohort_entry("manifest_v1"),
        _cohort_entry("staged_v1"),
    ]
    payload = {
        "schema_version": 1,
        "phase": "p13",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": {
            "kind": "extract_reconstruction_embeddings",
            "decoder_run": "decoder_run",
            "checkpoint_epoch": 20,
            "cleft_embeddings": "embeddings",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "backbone": "vit_b16",
            "init": "imagenet",
            "geometry": "g1",
            "out_version": "embeddings_recon_v1",
            "cleft_reconstruction_acknowledged": acknowledged,
            "expect_patients": 237,
            "batch_size": 32,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 13 — STOP 3, CHECK (d) PART 1: RE-EMBED THE 237\n"
        "# RECONSTRUCTIONS THROUGH THE SAME FROZEN ViT-B/16.\n"
        "# phase13.STOP_3_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase13_configs.py.\n"
        "#\n"
        "# **THE SET IS PATIENT-DERIVED AND CLUSTER-ONLY** -- embeddings\n"
        "# of generated patient images are patient data. The gate rides\n"
        "# with the regeneration: this task rebuilds cohort pixels in\n"
        "# memory (never on disk), so it carries the same acknowledged\n"
        "# check as the run that first wrote them. A GPU job.\n"
        "#\n"
        "# **THE PROBE IS A SEPARATE RUN** on the set this writes\n"
        f"# ({PROBE_NAME}), the 0.2520 arm's recipe BYTE-IDENTICAL.\n"
        "#\n"
        + _provenance(inputs)
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{RECON_EXTRACT_NAME}\"\n\n"
    ) + body


def render_probe() -> str:
    """(d) part 2: the ladder arm's task block, byte-identical, over the
    reconstruction set. Derived from the shipped p7 config so 'identical
    recipe' is a fact about the file rather than a claim in a comment."""
    ladder_payload = source(LADDER_CONFIG)
    ladder_inputs = {e["name"]: e for e in ladder_payload["inputs"]}
    carried = _carried_named_entry(PROBE_NAME, "embeddings_recon")
    recon_entry = carried or {
        "name": "embeddings_recon",
        "path": RECON_EMBEDDINGS_PATH,
        "rollup_sha256": PLACEHOLDER,
    }
    inputs = [
        dict(ladder_inputs["manifest_v1"]),
        dict(ladder_inputs["staged_v1"]),
        recon_entry,
    ]
    task = dict(ladder_payload["task"])
    # The ONE substitution: the arm reads the reconstruction set instead
    # of the original one. Every other key is the shipped arm's own.
    task["embeddings_artifact"] = "embeddings_recon"
    payload = {
        "schema_version": 1,
        "phase": "p13",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": task,
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    unresolved = set(recon_entry["rollup_sha256"]) == {"0"}
    provenance = (
        "# **THE embeddings_recon HASH IS AN ALL-ZERO PLACEHOLDER** (the\n"
        "# set exists only after p13_extract_recon runs). Fill via\n"
        "# declare_inputs.py; guard 3 refuses until it is real.\n"
        if unresolved else
        "# **RESOLVED.** Every input declared with a verified hash.\n"
    )
    return (
        "# PHASE 13 — STOP 3, CHECK (d) PART 2: THE STANDARD LINEAR\n"
        "# PROBE ON THE RECONSTRUCTION EMBEDDINGS.\n"
        "# phase13.STOP_3_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase13_configs.py, whose task\n"
        f"# block is COPIED FROM {LADDER_CONFIG} with exactly ONE\n"
        "# substitution: embeddings_artifact -> the reconstruction set.\n"
        "# 'The 0.2520 arm's recipe byte-identical' is therefore a fact\n"
        "# about this file, checked by --check, not a claim in a comment.\n"
        "#\n"
        "# **DESCRIPTIVE: no ladder entry, NO PAIRED CLAIM.** A's 0.2505\n"
        "# is stated as CONTEXT, not contested; no PLAN 4.3 machinery is\n"
        "# invoked and this arm enters no results-ledger row.\n"
        "#\n"
        "# **CLUSTER-ONLY**: the input set is patient-derived.\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{PROBE_NAME}\"\n\n"
    ) + body


CONFOUND_NAME = "p13_confound_ceiling.yaml"
#: P2's three arms. ONE kind, three configs: the band is the only key
#: that differs, which is what keeps them one-factor by construction.
OCCLUSION_BANDS = ("eyes", "nose", "lips")


def _occlusion_names(band: str) -> tuple[str, str, str]:
    """(extract config, probe config, artifact version) for one band."""
    return (
        f"p13_occlude_{band}.yaml",
        f"p13_probe_occluded_{band}.yaml",
        f"embeddings_occluded_{band}_v1",
    )


def render_confound() -> str:
    """P1: pod arithmetic over five non-anatomical statistics."""
    inputs = [
        _cohort_entry("manifest_v1"),
        _cohort_entry("staged_v1"),
        _scoresheet_entry(),
    ]
    payload = {
        "schema_version": 1,
        "phase": "p13",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": {
            "kind": "confound_ceiling",
            "manifest_artifact": "manifest_v1",
            "staged_artifact": "staged_v1",
            "scoresheet_artifact": "scoresheet_primary",
            # A's own five seeds, so the spread is comparable in shape.
            "seeds": [1337, 2024, 7, 99, 12345],
            "inner_val_frac": 0.2,
            "alpha": 1.0,
            "substantial_pcc": 0.10,
            "expect_patients": 237,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 13 ADDENDUM P1: THE CONFOUND CEILING -- HOW MUCH OF THE\n"
        "# GRADE IS PREDICTABLE FROM NON-ANATOMICAL GLOBAL IMAGE\n"
        "# STATISTICS ALONE. phase13.CLOSING_ADDENDUM_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase13_configs.py.\n"
        "#\n"
        "# **POD ARITHMETIC.** Five scalars per patient (aspect ratio,\n"
        "# brightness mean, contrast sd, content fraction, corner white)\n"
        "# and a closed-form ridge over cleft_v1's own folds. No\n"
        "# backbone, no GPU, no reconstruction -- and NO GATE, because\n"
        "# nothing here generates or modifies a cohort pixel.\n"
        "#\n"
        "# **BOTH READINGS ARE COMMITTED IN THE RECORD** before any\n"
        "# number exists, and `substantial_pcc` is declared HERE so the\n"
        "# threshold cannot be chosen after the number is seen. The\n"
        "# verdict composes with phase12.BASAL_CONFOUND_OBSERVED\n"
        "# (r(AR, mean) = +0.1601): this is its multivariate version.\n"
        "#\n"
        "# DESCRIPTIVE, report-never-gate: no ladder entry, no ledger row.\n"
        "#\n"
        + _provenance(inputs)
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{CONFOUND_NAME}\"\n\n"
    ) + body


def render_occlusion(band: str):
    """P2's extraction arm for one band. The band is the ONLY difference."""

    def render() -> str:
        name, probe_name, out_version = _occlusion_names(band)
        acknowledged = _cohort_flag()
        inputs = [
            _cohort_entry("manifest_v1"),
            _cohort_entry("staged_v1"),
        ]
        payload = {
            "schema_version": 1,
            "phase": "p13",
            "tier": "keeper",
            "seed": 1337,
            "inputs": inputs,
            "task": {
                "kind": "extract_occluded_embeddings",
                "occluded_band": band,
                "manifest_artifact": "manifest_v1",
                "staged_artifact": "staged_v1",
                "backbone": "vit_b16",
                "init": "imagenet",
                "geometry": "g1",
                "out_version": out_version,
                "cleft_reconstruction_acknowledged": acknowledged,
                "expect_patients": 237,
                "extract_batch_size": 32,
            },
        }
        body = yaml.safe_dump(
            payload, sort_keys=False, default_flow_style=False
        )
        gate_line = (
            "# **cleft_reconstruction_acknowledged: true -- A DATED\n"
            "# CONFIRMATION, INHERITED** from the cohort config: the gate\n"
            "# rides wherever cohort pixels are touched.\n"
            if acknowledged else
            "# **cleft_reconstruction_acknowledged: false -- THE TASK WILL\n"
            "# REFUSE.** The flag is the edit, carried by the\n"
            "# generator from the cohort config.\n"
        )
        return (
            f"# PHASE 13 ADDENDUM P2: RE-EMBED THE COHORT WITH THE {band.upper()}\n"
            "# THIRD BLANKED TO WHITE. phase13.CLOSING_ADDENDUM_REGISTERED.\n"
            "#\n"
            "# GENERATED by scripts/generate_phase13_configs.py. THREE\n"
            "# configs share ONE kind and differ in `occluded_band`\n"
            "# ALONE -- which is what makes the three one-factor by\n"
            "# construction, the view-ablation precedent.\n"
            "#\n"
            "# **THE OCCLUDED CROPS LIVE IN MEMORY ONLY.** What lands is\n"
            "# the embedding set: patient-derived, CLUSTER-ONLY. Blanked\n"
            "# to WHITE, the value the staging pad already uses, so an\n"
            "# occluded band is indistinguishable from pad downstream.\n"
            "#\n"
            "# **THE GATE RIDES BY INHERITANCE AND CAUTION**: occlusion\n"
            "# MODIFIES an existing crop rather than GENERATING a new\n"
            "# image, so the gate's registered trigger does not strictly\n"
            "# reach it -- the conservative reading costs nothing and the\n"
            "# distinction is recorded, not blurred.\n"
            "#\n"
            + gate_line
            + "#\n"
            f"# The probe on this set is a SEPARATE run ({probe_name}),\n"
            "# A's recipe byte-identical. A GPU job.\n"
            "#\n"
            + _provenance(inputs)
            + "#\n"
            f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
            f"#     python -m cleft.run --config configs/{name}\"\n\n"
        ) + body

    return render


def render_occlusion_probe(band: str):
    """P2's probe arm for one band: A's task block, one key changed."""

    def render() -> str:
        name, probe_name, out_version = _occlusion_names(band)
        ladder_payload = source(LADDER_CONFIG)
        ladder_inputs = {e["name"]: e for e in ladder_payload["inputs"]}
        carried = _carried_named_entry(probe_name, "embeddings_occluded")
        entry = carried or {
            "name": "embeddings_occluded",
            "path": f"{CLUSTER_ROOT}/data/embeddings/{out_version}",
            "rollup_sha256": PLACEHOLDER,
        }
        inputs = [
            dict(ladder_inputs["manifest_v1"]),
            dict(ladder_inputs["staged_v1"]),
            entry,
        ]
        task = dict(ladder_payload["task"])
        task["embeddings_artifact"] = "embeddings_occluded"
        payload = {
            "schema_version": 1,
            "phase": "p13",
            "tier": "keeper",
            "seed": 1337,
            "inputs": inputs,
            "task": task,
        }
        body = yaml.safe_dump(
            payload, sort_keys=False, default_flow_style=False
        )
        provenance = (
            "# **THE embeddings_occluded HASH IS AN ALL-ZERO PLACEHOLDER**\n"
            f"# (the set exists only after {name} runs). Fill via\n"
            "# declare_inputs.py; guard 3 refuses until it is real.\n"
            if set(entry["rollup_sha256"]) == {"0"} else
            "# **RESOLVED.** Every input declared with a verified hash.\n"
        )
        return (
            f"# PHASE 13 ADDENDUM P2: THE PROBE ON THE {band.upper()}-OCCLUDED\n"
            "# EMBEDDINGS. phase13.CLOSING_ADDENDUM_REGISTERED.\n"
            "#\n"
            "# GENERATED by scripts/generate_phase13_configs.py, whose\n"
            f"# task block is COPIED FROM {LADDER_CONFIG} with exactly\n"
            "# ONE substitution: embeddings_artifact -> the occluded set.\n"
            "# 'A's recipe byte-identical' is a fact about this file,\n"
            "# checked by --check, not a claim in a comment.\n"
            "#\n"
            "# **DESCRIPTIVE: no ladder entry, NO PAIRED CLAIM.** A's\n"
            "# 0.2505 is stated CONTEXT, exactly as it was for (d).\n"
            "#\n"
            "# **CLUSTER-ONLY**: the input set is patient-derived.\n"
            "#\n"
            + provenance
            + "#\n"
            f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
            f"#     python -m cleft.run --config configs/{probe_name}\"\n\n"
        ) + body

    return render


def _recon_occlusion_names(band: str) -> tuple[str, str, str]:
    """(extract config, probe config, artifact version) for one P3 band."""
    return (
        f"p13_occlude_recon_{band}.yaml",
        f"p13_probe_occluded_recon_{band}.yaml",
        f"embeddings_occluded_recon_{band}_v1",
    )


def render_recon_occlusion(band: str):
    """P3's extraction arm for one band: reconstructions regenerated in
    memory, occluded, re-embedded. The band is the ONLY difference."""

    def render() -> str:
        name, probe_name, out_version = _recon_occlusion_names(band)
        acknowledged = _cohort_flag()
        inputs = [
            _cohort_entry("decoder_run"),
            _cohort_entry("embeddings"),
            _cohort_entry("manifest_v1"),
            _cohort_entry("staged_v1"),
        ]
        payload = {
            "schema_version": 1,
            "phase": "p13",
            "tier": "keeper",
            "seed": 1337,
            "inputs": inputs,
            "task": {
                "kind": "extract_occluded_recon_embeddings",
                "occluded_band": band,
                "decoder_run": "decoder_run",
                "checkpoint_epoch": 20,
                "cleft_embeddings": "embeddings",
                "manifest_artifact": "manifest_v1",
                "staged_artifact": "staged_v1",
                "backbone": "vit_b16",
                "init": "imagenet",
                "geometry": "g1",
                "out_version": out_version,
                "cleft_reconstruction_acknowledged": acknowledged,
                "expect_patients": 237,
                "batch_size": 32,
                "extract_batch_size": 32,
            },
        }
        body = yaml.safe_dump(
            payload, sort_keys=False, default_flow_style=False
        )
        gate_line = (
            "# **cleft_reconstruction_acknowledged: true -- A DATED\n"
            "# CONFIRMATION, INHERITED.** This task REGENERATES cohort\n"
            "# reconstructions, squarely inside the gate's own trigger.\n"
            if acknowledged else
            "# **cleft_reconstruction_acknowledged: false -- THE TASK WILL\n"
            "# REFUSE.** The flag is the edit, carried by the\n"
            "# generator from the cohort config.\n"
        )
        return (
            f"# PHASE 13 ADDENDUM P3: RECONSTRUCTIONS WITH THE {band.upper()}\n"
            "# THIRD BLANKED, RE-EMBEDDED. phase13.P3_TRIGGERED -- the\n"
            "# registered condition FIRED (P2: nose -0.082, lips -0.162)\n"
            "# and the maintainer said run.\n"
            "#\n"
            "# GENERATED by scripts/generate_phase13_configs.py. THREE\n"
            "# configs share ONE kind and differ in `occluded_band` ALONE.\n"
            "#\n"
            "# **RECONSTRUCTIONS ARE REGENERATED IN MEMORY** through the\n"
            "# epoch-20 checkpoint (the shared gate-first helper), occluded\n"
            "# by the same band_rows thirds P2 used on originals, and\n"
            "# never persisted -- only the CLUSTER-ONLY embedding set lands.\n"
            "#\n"
            "# **THE BAND-SMEARING CAVEAT RIDES AS REGISTERED**: the\n"
            "# decoder's errors are band-smeared (the 3.23x everywhere-\n"
            "# gap), so per-band attribution on reconstructions is a\n"
            "# BLUNTER instrument than on originals.\n"
            "#\n"
            + gate_line
            + "#\n"
            f"# The probe on this set is a SEPARATE run ({probe_name}),\n"
            "# A's recipe byte-identical. A GPU job.\n"
            "#\n"
            + _provenance(inputs)
            + "#\n"
            f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
            f"#     python -m cleft.run --config configs/{name}\"\n\n"
        ) + body

    return render


def render_recon_occlusion_probe(band: str):
    """P3's probe arm for one band: A's task block, one key changed."""

    def render() -> str:
        name, probe_name, out_version = _recon_occlusion_names(band)
        ladder_payload = source(LADDER_CONFIG)
        ladder_inputs = {e["name"]: e for e in ladder_payload["inputs"]}
        carried = _carried_named_entry(probe_name, "embeddings_occluded")
        entry = carried or {
            "name": "embeddings_occluded",
            "path": f"{CLUSTER_ROOT}/data/embeddings/{out_version}",
            "rollup_sha256": PLACEHOLDER,
        }
        inputs = [
            dict(ladder_inputs["manifest_v1"]),
            dict(ladder_inputs["staged_v1"]),
            entry,
        ]
        task = dict(ladder_payload["task"])
        task["embeddings_artifact"] = "embeddings_occluded"
        payload = {
            "schema_version": 1,
            "phase": "p13",
            "tier": "keeper",
            "seed": 1337,
            "inputs": inputs,
            "task": task,
        }
        body = yaml.safe_dump(
            payload, sort_keys=False, default_flow_style=False
        )
        provenance = (
            "# **THE embeddings_occluded HASH IS AN ALL-ZERO PLACEHOLDER**\n"
            f"# (the set exists only after {name} runs). Fill via\n"
            "# declare_inputs.py; guard 3 refuses until it is real.\n"
            if set(entry["rollup_sha256"]) == {"0"} else
            "# **RESOLVED.** Every input declared with a verified hash.\n"
        )
        return (
            f"# PHASE 13 ADDENDUM P3: THE PROBE ON THE {band.upper()}-OCCLUDED\n"
            "# RECONSTRUCTION EMBEDDINGS. phase13.P3_TRIGGERED.\n"
            "#\n"
            "# GENERATED by scripts/generate_phase13_configs.py, whose\n"
            f"# task block is COPIED FROM {LADDER_CONFIG} with exactly\n"
            "# ONE substitution: embeddings_artifact -> the occluded set.\n"
            "#\n"
            "# **DESCRIPTIVE: no ladder entry, NO PAIRED CLAIM.** Splits\n"
            "# (d)'s 0.1693 by band against P2's split of A's 0.2505 --\n"
            "# both readings committed in phase13.P3_TRIGGERED, and the\n"
            "# band-smearing caveat rides whichever way it lands.\n"
            "#\n"
            "# **CLUSTER-ONLY**: the input set is patient-derived.\n"
            "#\n"
            + provenance
            + "#\n"
            f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
            f"#     python -m cleft.run --config configs/{probe_name}\"\n\n"
        ) + body

    return render


ASYM_PROBE_NAME = "p13_asym_encoding.yaml"
ASYMMETRY_RUN_PENDING = (
    f"{CLUSTER_ROOT}/runs/keeper/p13/PENDING_p13_asymmetry"
)


def _asymmetry_run_entry() -> dict:
    return _carried_named_entry(ASYM_PROBE_NAME, "asymmetry_run") or {
        "name": "asymmetry_run",
        "path": ASYMMETRY_RUN_PENDING,
        "rollup_sha256": PLACEHOLDER,
    }


def render_asym_probe() -> str:
    """The post-closing check: embeddings -> banked asym_orig, pod."""
    inputs = [
        _asymmetry_run_entry(),
        _cohort_entry("embeddings"),
        _cohort_entry("manifest_v1"),
    ]
    payload = {
        "schema_version": 1,
        "phase": "p13",
        "tier": "keeper",
        "seed": 1337,
        "inputs": inputs,
        "task": {
            "kind": "asymmetry_encoding_probe",
            "asymmetry_run": "asymmetry_run",
            "cleft_embeddings": "embeddings",
            "manifest_artifact": "manifest_v1",
            "seeds": [1337, 2024, 7, 99, 12345],
            "inner_val_frac": 0.2,
            "alpha": 1.0,
            "substantial_pcc": 0.10,
            "expect_patients": 237,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return (
        "# PHASE 13 POST-CLOSING CHECK: DOES THE EMBEDDING CARRY THE\n"
        "# MIRROR-SCALAR? phase13.ASYMMETRY_ENCODING_PROBE_REGISTERED.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase13_configs.py.\n"
        "#\n"
        "# **THE CONFLATION THIS RESOLVES**: (c)'s r +0.0082 cannot\n"
        "# distinguish 'never encoded' from 'encoded but not rendered'\n"
        "# -- a generative decoder can drop what the representation\n"
        "# carries. This probe BYPASSES the decoder: frozen 768-d\n"
        "# embeddings -> the BANKED asym_orig scalars (consumed from the\n"
        "# stop-3 run's metrics, never recomputed), ridge, cleft_v1\n"
        "# folds, five seeds. POD ARITHMETIC, no pixels, NO GATE.\n"
        "#\n"
        "# **BOTH READINGS COMMITTED, THRESHOLD DECLARED (0.10)** before\n"
        "# any number exists; the instrument limitation on (c) rides\n"
        "# either way (the scalar barely tracks grade, r +0.0131 -- this\n"
        "# probes ENCODING, not clinical relevance). The verdict amends\n"
        "# PHASE_13_CLOSING dated, in place. DESCRIPTIVE, no ledger row.\n"
        "#\n"
        + _provenance(inputs)
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{ASYM_PROBE_NAME}\"\n\n"
    ) + body


CONFIGS = {
    EXTRACT_NAME: render_extract,
    DECODER_NAME: render_decoder,
    COHORT_NAME: render_cohort,
    REGIONAL_NAME: render_regional,
    ASYMMETRY_NAME: render_asymmetry,
    RECON_EXTRACT_NAME: render_recon_extract,
    PROBE_NAME: render_probe,
    CONFOUND_NAME: render_confound,
    ASYM_PROBE_NAME: render_asym_probe,
}
for _band in OCCLUSION_BANDS:
    _extract_name, _probe_name, _ = _occlusion_names(_band)
    CONFIGS[_extract_name] = render_occlusion(_band)
    CONFIGS[_probe_name] = render_occlusion_probe(_band)
for _band in OCCLUSION_BANDS:
    _extract_name, _probe_name, _ = _recon_occlusion_names(_band)
    CONFIGS[_extract_name] = render_recon_occlusion(_band)
    CONFIGS[_probe_name] = render_recon_occlusion_probe(_band)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    print("scut inputs carried from the pretraining config")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
