"""Write Phase 15's stop-1 config from the registered decisions.

    PYTHONPATH=src python scripts/generate_phase15_configs.py [--check]

One config: the MEBeauty survey. The root is env-portable
(${CLEFT_MEBEAUTY_ROOT}, phase15.LANDING_CORRECTED -- the SCUT-root
precedent), and its rollup is a documented placeholder until the declare
pass fills it; the generator carries the fill (three-state).
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"
PLACEHOLDER = "0" * 64
SURVEY_NAME = "p15_survey.yaml"
MEBEAUTY_PATH = "${CLEFT_MEBEAUTY_ROOT}"
MEBEAUTY_KNOWN_LOCATION = "/home/user/codex/mebeauty/MEBeauty-database"


def _carried_root_hash(path=None) -> str:
    """The MEBeauty root's rollup, carried once declare_inputs fills it."""
    path = path or REPO / "configs" / SURVEY_NAME
    if not path.is_file():
        return PLACEHOLDER
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    for entry in payload.get("inputs") or []:
        if entry.get("name") == "mebeauty_root" and (
            entry.get("path") == MEBEAUTY_PATH
        ):
            rollup = str(entry.get("rollup_sha256") or "")
            if len(rollup) == 64 and set(rollup) != {"0"}:
                return rollup
    return PLACEHOLDER


def render_survey() -> str:
    root_hash = _carried_root_hash()
    payload = {
        "schema_version": 1,
        "phase": "p15",
        "tier": "keeper",
        "seed": 1337,
        "inputs": [
            {
                "name": "mebeauty_root",
                "path": MEBEAUTY_PATH,
                "rollup_sha256": root_hash,
            },
        ],
        "task": {
            "kind": "survey_mebeauty",
            "mebeauty_root": "mebeauty_root",
            "published_images": 2550,
            "frontal_max_offset": 0.08,
            "sheet_accept": 24,
            "sheet_reject": 24,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    provenance = (
        "# **THE mebeauty_root HASH IS AN ALL-ZERO PLACEHOLDER** until\n"
        "# declare_inputs.py verifies the clone (9,808 files, 651M --\n"
        "# phase15.CLONE_CONTENTS). Guard 3 refuses until it is real --\n"
        "# the PLACEHOLDER working, not a mistake.\n"
        if root_hash == PLACEHOLDER else
        "# **RESOLVED.** The clone declared with a verified hash.\n"
    )
    return (
        "# PHASE 15 — STOP 1: THE MEBEAUTY SURVEY. INVENTORY, THE\n"
        "# scores/ CARRIER STATEMENT, THE FRONTAL SCREEN, THE USABLE\n"
        "# COUNT, ACCEPT/REJECT SHEETS. phase15.STOP_1_BUILT.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase15_configs.py.\n"
        "#\n"
        "# **PUBLIC DATA, SHAREABLE THROUGHOUT, NO GATE** -- no patient\n"
        "# pixel is anywhere near this task. cropped_images/,\n"
        "# geometric_features.csv and FaceNet features are inventoried\n"
        "# and NOT consumed (exit criterion 3's boundary; any use of\n"
        "# the shipped crops is a dated decision).\n"
        "#\n"
        "# **THE ROOT IS ENV-PORTABLE** (phase15.LANDING_CORRECTED, the\n"
        "# SCUT-root precedent): export\n"
        f"#   CLEFT_MEBEAUTY_ROOT={MEBEAUTY_KNOWN_LOCATION}\n"
        "# on the pod, and set the job-form env var for cluster jobs.\n"
        "# The declared rollup verifies whatever the env resolves.\n"
        "#\n"
        "# **THE FRONTAL THRESHOLD IS DECLARED HERE** (0.08 normalised\n"
        "# centroid offset) BEFORE the screen runs -- a threshold\n"
        "# chosen after seeing the distribution is not a threshold\n"
        "# (phase15.FRONTAL_FRACTION_FIRST). The usable count this\n"
        "# banks is the phase's FIRST number, and every later\n"
        "# registration uses it, not the headline 2,550.\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{SURVEY_NAME}\"\n\n"
    ) + body


VERIFY_NAME = "p15_verify_mapping.yaml"


def render_verify() -> str:
    """Stop 2a: the mapping verification. Same root, no new declares."""
    root_hash = _carried_root_hash()
    payload = {
        "schema_version": 1,
        "phase": "p15",
        "tier": "keeper",
        "seed": 1337,
        "inputs": [
            {
                "name": "mebeauty_root",
                "path": MEBEAUTY_PATH,
                "rollup_sha256": root_hash,
            },
        ],
        "task": {
            "kind": "verify_mebeauty_mapping",
            "mebeauty_root": "mebeauty_root",
            "frontal_max_offset": 0.08,
            "expect_usable": 1519,
            "midline_tolerance": 0.02,
            "eye_symmetry_tolerance": 0.02,
            "corner_margin": 0.05,
            "sheet_faces": 32,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    provenance = (
        "# **THE mebeauty_root HASH IS AN ALL-ZERO PLACEHOLDER** until\n"
        "# declare_inputs.py verifies the clone.\n"
        if root_hash == PLACEHOLDER else
        "# **RESOLVED.** The clone declared with a verified hash --\n"
        "# CARRIED from the survey config; no new declaration.\n"
    )
    return (
        "# PHASE 15 — STOP 2a: VERIFY THE dlib-68 MAPPING, THEN RENDER\n"
        "# MAPPING SHEETS. phase15.STOP_2A_BUILT.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase15_configs.py.\n"
        "#\n"
        "# **THE MAPPING IS [LITERATURE], NOT MEASURED** (the maintainer's\n"
        "# ruling, phase15.STOP_2_RULINGS). These are SCUT's own three\n"
        "# checks re-run on this dataset: mirror-pair |x| of 33 and 51\n"
        "# near zero; eye-group centres symmetric (with the image-left\n"
        "# vs subject-right trap asserted); 48/54 the widest symmetric\n"
        "# pair.\n"
        "#\n"
        "# **THE THREE THRESHOLDS ARE DECLARED HERE, BEFORE THE RUN.**\n"
        "# If a check fails, the MAPPING reopens -- the check is NEVER\n"
        "# adjusted to fit the indices; that direction of accommodation\n"
        "# is the failure mode.\n"
        "#\n"
        "# **THE VERDICT READS LANDMARKS ONLY.** Pixels are touched\n"
        "# solely to render the review sheets, so a rendering problem\n"
        "# cannot corrupt a measurement. MEASURED, then SHEETS, then\n"
        "# BATCH -- 2b stages nothing until the visual check passes these.\n"
        "#\n"
        "# `expect_usable: 1519` re-derives stop 1's banked count from\n"
        "# the same declared screen; a mismatch means the two stops are\n"
        "# measuring different sets and the run refuses.\n"
        "#\n"
        "# **PUBLIC DATA, SHAREABLE, NO GATE.** Export\n"
        f"#   CLEFT_MEBEAUTY_ROOT={MEBEAUTY_KNOWN_LOCATION}\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{VERIFY_NAME}\"\n\n"
    ) + body


SCREEN_NAME = "p15_screen_landmarks.yaml"


def render_screen() -> str:
    """Stop 2a-ii: the landmark-quality screen. Same root, no new declares."""
    root_hash = _carried_root_hash()
    payload = {
        "schema_version": 1,
        "phase": "p15",
        "tier": "keeper",
        "seed": 1337,
        "inputs": [
            {
                "name": "mebeauty_root",
                "path": MEBEAUTY_PATH,
                "rollup_sha256": root_hash,
            },
        ],
        "task": {
            "kind": "screen_mebeauty_landmarks",
            "mebeauty_root": "mebeauty_root",
            "frontal_max_offset": 0.08,
            "expect_usable": 1519,
            "span_min": 0.15,
            "span_max": 1.10,
            "interocular_min": 0.25,
            "interocular_max": 0.70,
            "bounds_margin": 0.10,
            "bounds_max_points_outside": 10,
            "diagnose_images": [
                "119.jpg", "girl-3956612.jpg", "man-1868320.jpg",
            ],
            "sheet_survivors": 32,
            "sheet_rejected": 32,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    provenance = (
        "# **THE mebeauty_root HASH IS AN ALL-ZERO PLACEHOLDER** until\n"
        "# declare_inputs.py verifies the clone.\n"
        if root_hash == PLACEHOLDER else
        "# **RESOLVED.** The clone declared with a verified hash --\n"
        "# CARRIED from the survey config; no new declaration.\n"
    )
    return (
        "# PHASE 15 — STOP 2a-ii: THE LANDMARK-QUALITY SCREEN.\n"
        "# phase15.STOP_2A_II_BUILT.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase15_configs.py.\n"
        "#\n"
        "# **WHY THIS EXISTS**: the pose screen is BLIND to detector\n"
        "# failure -- a misplaced but SYMMETRIC cloud passes a\n"
        "# centroid-offset test happily. Faces with drifted, collapsed\n"
        "# or foreign-frame landmark sets reached the accepted 1,519 and\n"
        "# were caught only by eye on the mapping sheets\n"
        "# (phase15.MAPPING_SHEETS_REVIEWED). These five checks test\n"
        "# what the eye tested: degenerate rows, image bounds, face\n"
        "# span, vertical ordering, inter-ocular distance.\n"
        "#\n"
        "# **EVERY THRESHOLD IS DECLARED HERE, BEFORE THE RUN**, and a\n"
        "# face that fails is REJECTED -- the check is never loosened to\n"
        "# keep it (the 2a rule, unchanged).\n"
        "#\n"
        "# **THE VERDICT NEVER DECODES A PIXEL**: it reads landmark\n"
        "# geometry and image DIMENSIONS (PIL headers). Pixels are\n"
        "# decoded solely for the review sheets.\n"
        "#\n"
        "# `diagnose_images` must EXPLAIN THEMSELVES BY NAME in the\n"
        "# report: 119.jpg passed a screen it should never have reached\n"
        "# (no landmarks and no midline rendered on its mapping sheet),\n"
        "# and whatever let it through may not be unique to it. The\n"
        "# diagnosis is a declared list, not a one-off print.\n"
        "#\n"
        "# **THE BOUNDS TOLERANCES WERE STRICT (0.0 / 0) AND ARE NOW\n"
        "# 0.10 / 10** -- the ruling, a VISIBLE CONFIG DIFF.\n"
        "# The measured distribution over all 55 bounds-rejects fired\n"
        "# branch 1 and NOT branch 2: points outside per face median 3,\n"
        "# p90 7, max 9 of 68; max overshoot median 1.6%, p90 5.7%, max\n"
        "# 7.8% of the image. ONE continuous mode, no bimodality -- the\n"
        "# foreign-coordinate-frame population the check was built\n"
        "# against has NO INSTANCE in this dataset.\n"
        "#\n"
        "# The values sit JUST ABOVE the observed maxima (9 points,\n"
        "# 7.8%) because there is no measured basis for a cut inside a\n"
        "# single mode. **PROVENANCE, STATED IN THE OPEN: this value was\n"
        "# chosen from a measured distribution AFTER an eye pass**\n"
        "# (phase15.BOUNDS_TOLERANCE_RULED). The 0.08 pose threshold\n"
        "# remains untouched, per the registered distinction.\n"
        "#\n"
        "# **CONSEQUENCE, PLAINLY**: at this tolerance the quality\n"
        "# screen rejects NOTHING on MEBeauty -- its value here is\n"
        "# purely PROTECTIVE. It still fails the foreign-frame case it\n"
        "# was built for, and still catches collapsed clouds, broken\n"
        "# ordering and degenerate rows.\n"
        "#\n"
        "# The surviving count REPLACES 1,519 in every later\n"
        "# registration, and its fall is THE PRICE OF QUALITY -- the\n"
        "# 0.08 band's ~5% precedent.\n"
        "#\n"
        "# **PUBLIC DATA, SHAREABLE, NO GATE.** Export\n"
        f"#   CLEFT_MEBEAUTY_ROOT={MEBEAUTY_KNOWN_LOCATION}\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{SCREEN_NAME}\"\n\n"
    ) + body


STAGE_NAME = "p15_stage_mebeauty.yaml"


def render_stage() -> str:
    """Stop 2b: stage the survivors at G1 and G2, SCUT's composition."""
    root_hash = _carried_root_hash()
    payload = {
        "schema_version": 1,
        "phase": "p15",
        "tier": "keeper",
        "seed": 1337,
        "inputs": [
            {
                "name": "mebeauty_root",
                "path": MEBEAUTY_PATH,
                "rollup_sha256": root_hash,
            },
        ],
        "task": {
            "kind": "stage_mebeauty",
            "mebeauty_root": "mebeauty_root",
            "frontal_max_offset": 0.08,
            "span_min": 0.15,
            "span_max": 1.10,
            "interocular_min": 0.25,
            "interocular_max": 0.70,
            "bounds_margin": 0.10,
            "bounds_max_points_outside": 10,
            "expect_survivors": 1519,
            "expect_train": 932,
            "expect_test": 394,
            "out_version": "mebeauty_masked_v2",
            "variants": ["g1", "g2", "original"],
            "size": 224,
            "ar_sampling": "observed",
            "sheet_faces": 48,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    provenance = (
        "# **THE mebeauty_root HASH IS AN ALL-ZERO PLACEHOLDER** until\n"
        "# declare_inputs.py verifies the clone.\n"
        if root_hash == PLACEHOLDER else
        "# **RESOLVED.** The clone declared with a verified hash --\n"
        "# CARRIED from the survey config; no new declaration.\n"
    )
    return (
        "# PHASE 15 — STOP 2b: STAGE THE USABLE MEBEAUTY FACES AT G1\n"
        "# AND G2. phase15.STOP_2B_BUILT.\n"
        "#\n"
        "# GENERATED by scripts/generate_phase15_configs.py.\n"
        "#\n"
        "# **THE COMPOSITION IS SCUT'S, VERBATIM** -- masked.build_one\n"
        "# does the crop, the arrival mask, the staging and the G2\n"
        "# unwarp. The ONLY MEBeauty-specific step is the content box,\n"
        "# whose ANCHORS are dlib-68 (verified at 2a) and whose FORMULA\n"
        "# is the shared placement.box_from_anchors.\n"
        "#\n"
        "# **INHERITED, NOT RESTATED**: levelling OFF (the matched-\n"
        "# property argument), CLEFT_AR parity sampling from the 237\n"
        "# observed ratios, LOWER_MARGIN 0.06, and the frozen staging.\n"
        "# Parity is RE-RUN on the new artifact and reported as gaps,\n"
        "# never as a verdict.\n"
        "#\n"
        "# **BOTH SCREENS ARE DECLARED HERE** so the staged set is\n"
        "# REPRODUCED rather than re-decided, and `expect_survivors`\n"
        "# refuses a mismatch. The bounds tolerance is the ruled\n"
        "# 0.10 / 10 (phase15.BOUNDS_TOLERANCE_RULED).\n"
        "#\n"
        "# **ALL SURVIVORS ARE STAGED**; each face carries its split\n"
        "# (train / test / UNCOVERED) so pretraining selects the\n"
        "# split-covered subset without a second staging pass. The\n"
        "# shipped split covers 932 + 394 = 1,326 of the 1,519\n"
        "# (phase15.STOP_2A_BANKED's count gap), and both halves are\n"
        "# asserted.\n"
        "#\n"
        "# **v2, AND THE VERSION BUMP IS THE POINT.** v1 wrote\n"
        "# faces.csv and staged_<g>.npy; the frozen\n"
        "# pretrain.load_masked_features reads faces.json and\n"
        "# masked_<variant>.npy. v2 takes the SCUT artifact FORMAT so\n"
        "# that loader is reused UNCHANGED -- it exists because 'a\n"
        "# positional read would train every face against another\n"
        "# face's label and still produce a plausible number', and a\n"
        "# second loader would be a second home for that bug. Restaging\n"
        "# costs ~20s (phase15.ARTIFACT_FORMAT_IS_SCUTS).\n"
        "#\n"
        "# **`original` IS THE THIRD VARIANT**: the whole image through\n"
        "# the frozen stage -- no landmarks, no trapezium, no content\n"
        "# box -- byte-identically what SCUT's original arm stages. It\n"
        "# fills the third cell SCUT occupies (scut_original 0.1952,\n"
        "# SCUT's BEST transfer cell). Its pad fraction is MEASURED:\n"
        "# stage() pads non-square sources, and MEBeauty's are\n"
        "# non-square where SCUT's 350x350 are not\n"
        "# (phase15.ORIGINAL_ARM_PADS_TOO).\n"
        "#\n"
        "# **NOTHING IS EMBEDDED HERE.** The staged sheets go to El\n"
        "# visual check first -- the catch-net for the registered\n"
        "# anatomical blindness; if that class appears at any\n"
        "# noticeable rate the limitation is requantified BEFORE\n"
        "# pretraining.\n"
        "#\n"
        "# **PUBLIC DATA, SHAREABLE, NO GATE.** Export\n"
        f"#   CLEFT_MEBEAUTY_ROOT={MEBEAUTY_KNOWN_LOCATION}\n"
        "#\n"
        + provenance
        + "#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{STAGE_NAME}\"\n\n"
    ) + body


def source_config(name: str) -> dict:
    """One shipped config, read so a value can be DERIVED rather
    than restated."""
    return yaml.safe_load(
        (REPO / "configs" / name).read_text(encoding="utf-8")
    )


P6_CONFIG = "p6_pretrain_vit_b16_original.yaml"
#: A's shipped arm -- the probe recipe is DERIVED from it, so
#: "byte-identical" is a fact about the file, not a claim in prose.
LADDER_CONFIG = "p7_d1_vit_b16_imagenet_g1.yaml"
STAGED_PATH = (
    f"{CLUSTER_ROOT}/data/mebeauty_staged/mebeauty_masked_v2"
)
PRETRAIN_SOURCES = ("masked_g1", "masked_g2", "masked_original")


def _pretrain_name(source: str) -> str:
    return f"p15_pretrain_mebeauty_{source.removeprefix('masked_')}.yaml"


def _carried_staged_hash(name: str) -> str:
    path = REPO / "configs" / name
    if not path.is_file():
        return PLACEHOLDER
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    for entry in payload.get("inputs") or []:
        if entry.get("name") == "mebeauty_staged" and (
            entry.get("path") == STAGED_PATH
        ):
            rollup = str(entry.get("rollup_sha256") or "")
            if len(rollup) == 64 and set(rollup) != {"0"}:
                return rollup
    return PLACEHOLDER


def render_pretrain(source: str):
    """One MEBeauty pretraining arm. The RECIPE is derived from the
    shipped Phase 6 config, so 'byte-identical' is a fact about the
    file rather than a claim in a comment."""

    def render() -> str:
        name = _pretrain_name(source)
        p6 = source_config(P6_CONFIG)["task"]
        recipe = {
            key: p6[key]
            for key in (
                "epochs", "inner_val_frac", "monitor", "deterministic",
                "learning_rate", "weight_decay", "batch_size",
                "checkpoint_every",
            )
        }
        staged_hash = _carried_staged_hash(name)
        inputs = [
            {
                "name": "mebeauty_root",
                "path": MEBEAUTY_PATH,
                "rollup_sha256": _carried_root_hash(),
            },
            {
                "name": "mebeauty_staged",
                "path": STAGED_PATH,
                "rollup_sha256": staged_hash,
            },
        ]
        payload = {
            "schema_version": 1,
            "phase": "p15",
            "tier": "keeper",
            "seed": 1337,
            "inputs": inputs,
            "task": {
                "kind": "pretrain_mebeauty",
                "mebeauty_root": "mebeauty_root",
                "mebeauty_staged": "mebeauty_staged",
                "source": source,
                "backbone": p6["backbone"],
                "region_scheme": p6["region_scheme"],
                "expect_train": 932,
                "expect_test": 394,
                **recipe,
            },
        }
        body = yaml.safe_dump(
            payload, sort_keys=False, default_flow_style=False
        )
        provenance = (
            "# **THE mebeauty_staged HASH IS AN ALL-ZERO PLACEHOLDER**\n"
            "# until the v2 staging runs and declare_inputs.py verifies\n"
            "# it. Guard 3 refuses until then.\n"
            if staged_hash == PLACEHOLDER else
            "# **RESOLVED.** Every input declared with a verified hash.\n"
        )
        variant = source.removeprefix("masked_")
        comparator = (
            "scut_original 0.1952 (SCUT's BEST transfer cell)"
            if variant == "original" else
            f"scut_masked@{variant} "
            + ("0.0830" if variant == "g1" else "0.2001")
        )
        return (
            f"# PHASE 15 — STOP 3: PRETRAIN ON MEBEAUTY, source {source}.\n"
            "# phase15.STOP_3_AMENDED.\n"
            "#\n"
            "# GENERATED by scripts/generate_phase15_configs.py, whose\n"
            f"# recipe fields are COPIED FROM {P6_CONFIG}: epochs,\n"
            "# inner_val_frac, monitor, deterministic, learning_rate,\n"
            "# weight_decay, batch_size, checkpoint_every. **ONLY THE\n"
            "# DATA DIFFERS** -- 'the Phase 6 recipe byte-identical' is\n"
            "# checked by --check, not asserted in prose.\n"
            "#\n"
            "# Trains on the covered 932 (fit) with 394 held out -- the\n"
            "# SHIPPED universal split restricted to the staged\n"
            "# survivors, never a home-made cut, because a home-made\n"
            "# partition inside a cross-dataset comparison is a confound\n"
            "# the phase can avoid for free. The 193 uncovered faces are\n"
            "# staged and NOT pretrained on.\n"
            "#\n"
            "# **ONE CHECKPOINT PER SOURCE** (VARIANT_FOR_INIT): a\n"
            "# masked init is GEOMETRY-BOUND, so g1 and g2 are separate\n"
            "# runs and separate checkpoints, never one crossed between\n"
            "# them -- the phantom-findings trap.\n"
            "#\n"
            f"# ITS COMPARATOR, when the cleft-side probe runs: {comparator}\n"
            "# -- SAME-NAMED and SAME-GEOMETRY, asserted in code\n"
            "# (mebeauty.verdict_delta refuses a crossed pair). And the\n"
            "# ImageNet anchor (0.2520) rides in EVERY reading: an arm\n"
            "# that beats its SCUT cell while losing to ImageNet is not\n"
            "# a win.\n"
            "#\n"
            "# **THE SOURCE-SIDE PCC THIS RUN REPORTS IS PROVENANCE,\n"
            "# NOT THE VERDICT**: SCUT test PCC turned out not to\n"
            "# predict cleft transfer at all (ladder).\n"
            "#\n"
            "# **PUBLIC DATA, SHAREABLE, NO GATE.** Export\n"
            f"#   CLEFT_MEBEAUTY_ROOT={MEBEAUTY_KNOWN_LOCATION}\n"
            "#\n"
            + provenance
            + "#\n"
            f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
            f"#     python -m cleft.run --config configs/{name}\"\n\n"
        ) + body

    return render


def _provenance(inputs: list) -> str:
    """The two-pass state, said in the header so a reader can tell a
    deliberate placeholder from a mistake."""
    pending = sum(1 for e in inputs if "/PENDING_" in e["path"])
    unresolved = sum(
        1 for e in inputs if set(e["rollup_sha256"]) == {"0"}
    )
    if pending:
        return (
            f"# **{pending} PATH(S) PENDING and {unresolved} ALL-ZERO\n"
            "# PLACEHOLDER HASH(ES).** A run directory carries a SHA and\n"
            "# a job id, neither derivable on a laptop. Two passes:\n"
            "# paste the run directory, then declare_inputs.py. Guard 3\n"
            "# refuses until both are real -- the PLACEHOLDER working.\n"
        )
    if unresolved:
        return (
            f"# **{unresolved} ALL-ZERO PLACEHOLDER HASH(ES) REMAIN.**\n"
            "# Every path is real; declare_inputs.py fills the rest and\n"
            "# guard 3 refuses until it does.\n"
        )
    return (
        "# **RESOLVED.** Every input declared at a real path with a\n"
        "# verified hash.\n"
    )


#: The three cleft-side arms: (init, geometry, source, comparator).
#: Comparator SDs are the LADDER's own, quoted here so the threshold
#: uses both arms' spreads (PLAN 4.12.1) and declared BEFORE any number.
MEBEAUTY_ARMS = (
    {
        "init": "mebeauty_masked", "geometry": "g1",
        "source": "masked_g1", "run": "g1",
        "run_dir": "p15_pretrain_mebeauty_g1__dad0e892__p15-pretrain-mebeauty-g1",
        "comparator_init": "scut_masked", "comparator_geometry": "g1",
        "comparator_pcc": 0.0830, "comparator_sd": 0.0247,
    },
    {
        "init": "mebeauty_masked", "geometry": "g2",
        "source": "masked_g2", "run": "g2",
        "run_dir": "p15_pretrain_mebeauty_g2__dad0e892__p15-pretrain-mebeauty-g2",
        "comparator_init": "scut_masked", "comparator_geometry": "g2",
        "comparator_pcc": 0.2001, "comparator_sd": 0.0142,
    },
    {
        "init": "mebeauty_original", "geometry": "g1",
        "source": "masked_original", "run": "original",
        "run_dir": "p15_pretrain_mebeauty_original__dad0e892__p15-pretrain-mebeauty-original",
        "comparator_init": "scut_original", "comparator_geometry": "g1",
        "comparator_pcc": 0.1952, "comparator_sd": 0.0280,
    },
)
#: **PASTED 2026-08-24, the maintainer.** All three share the sha8
#: ``dad0e892`` because that field is the GIT COMMIT's short sha
#: (provenance/context.py:420), not the config's -- three runs launched
#: from one commit agree there and differ in the stem, which is what
#: these do. A shared sha8 across three DIFFERENT configs would be a
#: defect only if the field were per-config; it is not.
def _pretrain_run_path(arm: dict) -> str:
    return f"{CLUSTER_ROOT}/runs/keeper/p15/{arm['run_dir']}"


def _arm_name(arm: dict, stage: str) -> str:
    tag = arm["run"]
    return f"p15_{stage}_mebeauty_{tag}.yaml"


def _set_path(arm: dict) -> str:
    return (
        f"{CLUSTER_ROOT}/data/embeddings/"
        f"mebeauty_{arm['run']}_cleft_v1"
    )


def _carried_named(config_name: str, input_name: str, path: str) -> dict:
    """The generator owns the PATH; the shipped config carries only the
    HASH, and only when the two paths agree.

    The earlier version carried the whole entry whenever the shipped
    path was not a PENDING one. That made the CONFIG authoritative
    after the first fill: correcting a run directory here would have
    been silently ignored, and the stale path would have kept its
    already-verified hash -- a declared input pointing somewhere nobody
    intended, with a hash that still checks out. Pinning the carry to a
    matching path makes a corrected directory reset its hash to the
    placeholder instead, which guard 3 then refuses until it is
    re-declared. Same shape as ``_carried_staged_hash`` above.
    """
    entry = {"name": input_name, "path": path, "rollup_sha256": PLACEHOLDER}
    shipped = REPO / "configs" / config_name
    if not shipped.is_file():
        return entry
    payload = yaml.safe_load(shipped.read_text(encoding="utf-8")) or {}
    for candidate in payload.get("inputs") or []:
        if candidate.get("name") != input_name:
            continue
        if str(candidate.get("path")) != path:
            continue
        rollup = str(candidate.get("rollup_sha256") or "")
        if len(rollup) == 64 and set(rollup) != {"0"}:
            entry["rollup_sha256"] = rollup
    return entry


def render_extract_arm(arm: dict):
    def render() -> str:
        name = _arm_name(arm, "extract")
        ladder = {e["name"]: e for e in source_config(LADDER_CONFIG)["inputs"]}
        run_entry = _carried_named(
            name, "pretrain_run", _pretrain_run_path(arm),
        )
        inputs = [
            run_entry,
            dict(ladder["manifest_v1"]),
            dict(ladder["staged_v1"]),
        ]
        payload = {
            "schema_version": 1, "phase": "p15", "tier": "keeper",
            "seed": 1337, "inputs": inputs,
            "task": {
                "kind": "extract_mebeauty_embeddings",
                "pretrain_run": "pretrain_run",
                "expect_source": arm["source"],
                "init": arm["init"],
                "geometry": arm["geometry"],
                "manifest_artifact": "manifest_v1",
                "staged_artifact": "staged_v1",
                "backbone": "vit_b16",
                "out_version": _set_path(arm).rsplit("/", 1)[-1],
                "expect_patients": 237,
                "batch_size": 32,
            },
        }
        body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
        return (
            f"# PHASE 15 — STOP 4a: CLEFT EMBEDDINGS THROUGH THE\n"
            f"# {arm['source'].upper()} CHECKPOINT. phase15.STOP_4_BUILT.\n"
            "#\n"
            "# GENERATED by scripts/generate_phase15_configs.py.\n"
            "#\n"
            "# **THE ARM-TO-RUN MAPPING IS ASSERTED, NOT TRUSTED**: the\n"
            "# task reads the run's OWN metrics.json and refuses unless\n"
            f"# its recorded source is {arm['source']!r}. The mapping\n"
            "# cannot be confirmed from this machine (no cluster\n"
            "# access), so the check lives where the checkpoint is\n"
            "# consumed -- a swap fails here, not in a verdict.\n"
            "#\n"
            "# **MEBEAUTY'S OWN NAMESPACE.** The set is written by\n"
            "# mebeauty.save_set with init in MEBEAUTY_INITS; the\n"
            "# ladder's embeddings.INITS and its 24/12 arithmetic stay\n"
            "# untouched, and the two lattices are never pooled. Row\n"
            "# order is still checked with the LADDER's own\n"
            "# assert_row_order -- the property, reused.\n"
            "#\n"
            "# **CLUSTER-ONLY**: cleft-patient embeddings.\n"
            "#\n"
            + _provenance(inputs)
            + "#\n"
            f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
            f"#     python -m cleft.run --config configs/{name}\"\n\n"
        ) + body

    return render


def render_probe_arm(arm: dict):
    def render() -> str:
        name = _arm_name(arm, "probe")
        ladder_payload = source_config(LADDER_CONFIG)
        ladder_inputs = {e["name"]: e for e in ladder_payload["inputs"]}
        recipe_source = ladder_payload["task"]
        set_entry = _carried_named(
            name, "mebeauty_embeddings", _set_path(arm),
        )
        inputs = [
            dict(ladder_inputs["manifest_v1"]),
            dict(ladder_inputs["staged_v1"]),
            set_entry,
        ]
        recipe = {
            key: recipe_source[key]
            for key in (
                "label", "backbone", "trainable", "max_epochs", "patience",
                "inner_val_frac", "monitor", "seeds", "learning_rate",
                "weight_decay", "batch_size",
            )
        }
        payload = {
            "schema_version": 1, "phase": "p15", "tier": "keeper",
            "seed": 1337, "inputs": inputs,
            "task": {
                "kind": "probe_mebeauty",
                "mebeauty_embeddings": "mebeauty_embeddings",
                "manifest_artifact": "manifest_v1",
                "staged_artifact": "staged_v1",
                "init": arm["init"],
                "geometry": arm["geometry"],
                "patch_scheme": recipe_source.get("patch_scheme", "whole"),
                "feature_source": recipe_source.get("feature_source", "mirror"),
                **recipe,
                "comparator_init": arm["comparator_init"],
                "comparator_geometry": arm["comparator_geometry"],
                "comparator_sd": arm["comparator_sd"],
                "comparator_n": 5,
            },
        }
        body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
        return (
            f"# PHASE 15 — STOP 4b: A'S PROBE ON THE {arm['run'].upper()}\n"
            "# MEBEAUTY SET. phase15.STOP_4_BUILT.\n"
            "#\n"
            "# GENERATED by scripts/generate_phase15_configs.py, whose\n"
            f"# recipe keys are COPIED FROM {LADDER_CONFIG}: label,\n"
            "# backbone, trainable, max_epochs, patience,\n"
            "# inner_val_frac, monitor, seeds, learning_rate,\n"
            "# weight_decay, batch_size. **Identity is checked by a\n"
            "# difference-set test**, the occlusion probes' pattern.\n"
            "#\n"
            "# **ITS OWN KIND, NOT train_cv** (the ruling): a\n"
            "# SHARED VOCABULARY is what lets an undeclared swap\n"
            "# manufacture a factor effect, and a shared arm kind has\n"
            "# that property at the config layer just as a shared init\n"
            "# table has it at the set layer. Same phase3 entry point,\n"
            "# same derived recipe, second call site -- and the\n"
            "# ladder's train_cv vocabulary stays CLOSED.\n"
            "#\n"
            f"# **THE COMPARATOR IS DECLARED HERE, BEFORE ANY NUMBER**:\n"
            f"# {arm['comparator_init']}@{arm['comparator_geometry']} = "
            f"{arm['comparator_pcc']} (sd {arm['comparator_sd']}, n=5),\n"
            "# the ladder's own cell. The threshold is computed from\n"
            "# BOTH arms' five-seed SDs (phase3.combined_claimable_delta,\n"
            "# PLAN 4.12.1) and the within-geometry rule is asserted in\n"
            "# code. The ImageNet anchor (0.2520) rides in the reading:\n"
            "# an arm that beats its SCUT cell while losing to ImageNet\n"
            "# is NOT a win.\n"
            "#\n"
            "# **FOUR CAVEATS ARE BOUND** to whatever number this\n"
            "# produces (phase15.caveats_for): mechanism-ii asymmetry,\n"
            "# padding, framing variance, anatomical blindness.\n"
            "#\n"
            "# DESCRIPTIVE ranking; no ledger row without the paired\n"
            "# bar, and COHORT_CANNOT_RESOLVE is the expectation.\n"
            "#\n"
            "# **CLUSTER-ONLY**: the input set is patient-derived.\n"
            "#\n"
            + _provenance(inputs)
            + "#\n"
            f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
            f"#     python -m cleft.run --config configs/{name}\"\n\n"
        ) + body

    return render


CONFIGS = {
    SURVEY_NAME: render_survey,
    VERIFY_NAME: render_verify,
    SCREEN_NAME: render_screen,
    STAGE_NAME: render_stage,
}
for _source in PRETRAIN_SOURCES:
    CONFIGS[_pretrain_name(_source)] = render_pretrain(_source)
for _arm in MEBEAUTY_ARMS:
    CONFIGS[_arm_name(_arm, "extract")] = render_extract_arm(_arm)
    CONFIGS[_arm_name(_arm, "probe")] = render_probe_arm(_arm)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
