"""Write Phase 20's three configs from the shipped ones.

    PYTHONPATH=src python scripts/generate_phase20_configs.py [--check]

Four configs:

* ``p20_permutation_plain``      -- Arm P, the integrity gate (k = 1)
* ``p20_permutation_stratified`` -- Arm S, the attribution (k = 10)
* ``p20_confound_ceiling_mean``  -- Arm C, the like-for-like ceiling
* ``p20_stratification_diagnostic`` -- did Arm S preserve what it exists
  to preserve? Arm C's model on Arm S's own permuted labels
  [ADDED 2026-08-31]

**NO NEW HASH ENTERS THROUGH THIS GENERATOR.** Every input is CARRIED
VERBATIM -- same name, same path, same verified rollup -- from the config
that already declares it: the probe (``p7_d1_vit_b16_imagenet_g1``) for
P and S, the Phase 13 ceiling (``p13_confound_ceiling``) for C. Nothing
here computes a hash, and nothing here declares an artifact this project
has not already run against. A ``--check`` diff therefore fails if a
carried entry drifts from its source, which is the property that makes
the carrying worth doing.

**P and S are the probe's task block, copied, plus one key.** They are
built by copying rather than by hand for the reason the schema entry is:
the arms' whole claim is that they are the probe's fit path with one
vector reordered, and a hand-written near-copy would let them drift a
field at a time. ``seeds`` is asserted equal to the probe's rather than
restated -- the five-seed transformer regime is the probe's, not a
Phase 20 choice.

Arm C carries the Phase 13 ceiling's task block with the target switched
and the score sheet dropped: it reads a manifest column and never opens
the sheet, so declaring it would record an input the run does not use.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

from cleft import phase20  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"
PROBE_CONFIG = "p7_d1_vit_b16_imagenet_g1.yaml"
CEILING_CONFIG = "p13_confound_ceiling.yaml"

PLAIN_NAME = "p20_permutation_plain.yaml"
STRATIFIED_NAME = "p20_permutation_stratified.yaml"
ARM_C_NAME = "p20_confound_ceiling_mean.yaml"
DIAGNOSTIC_NAME = "p20_stratification_diagnostic.yaml"

#: The five-seed transformer regime, taken from the probe rather than
#: restated. Asserted below: if the probe's seeds ever move, this fails
#: loudly instead of silently measuring a control on a different set.
SEEDS = [1337, 2024, 7, 99, 12345]


def source(name: str) -> dict:
    return yaml.safe_load((REPO / "configs" / name).read_text(encoding="utf-8"))


def _probe() -> dict:
    probe = source(PROBE_CONFIG)
    if probe["task"]["seeds"] != SEEDS:
        raise SystemExit(
            f"the probe's seeds are {probe['task']['seeds']}, not {SEEDS}. "
            "The controls must run the arm's own seed set; fix SEEDS here "
            "deliberately rather than letting the two drift"
        )
    return probe


def _permutation_payload(kind: str, k: int) -> dict:
    """The probe's config, with the permutation block added and NOTHING
    else changed. Inputs are the probe's own entries, by reference."""
    probe = _probe()
    task = dict(probe["task"])
    task["kind"] = "p20_permutation"
    task["permutation"] = {"kind": kind, "k_strata": k}
    return {
        "schema_version": probe["schema_version"],
        "phase": "p20",
        "tier": "keeper",
        "seed": probe["seed"],
        # Carried verbatim: the manifest, the staged pixels (Arm S's
        # strata are fitted over them) and the probe's own embedding set.
        "inputs": [dict(entry) for entry in probe["inputs"]],
        "task": task,
    }


def _header(title: str, body: str, config_name: str) -> str:
    return (
        f"# {title}\n#\n"
        "# GENERATED by scripts/generate_phase20_configs.py. Do not\n"
        "# hand-edit: --check re-derives and diffs, and every input is\n"
        "# CARRIED VERBATIM from a shipped config, so a hand edit is how\n"
        "# a control quietly stops being the arm it controls.\n"
        f"#\n{body}#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{config_name}\"\n\n"
    )


def render_plain() -> str:
    payload = _permutation_payload("plain", 1)
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return _header(
        "PHASE 20 -- ARM P: THE PLAIN PERMUTATION. THE INTEGRITY GATE.",
        "# The probe's own config (p7_d1_vit_b16_imagenet_g1) with the\n"
        "# panel-mean labels SHUFFLED ACROSS ALL 237 and nothing else\n"
        "# touched -- same embeddings, same folds, same 769-parameter\n"
        "# head, same five seeds. phase20.ARM_P_REGISTERED.\n"
        "#\n"
        "# **THIS IS THE GATE.** If P is not near zero, Arm S is\n"
        "# uninterpretable and the phase STOPS: the finding becomes the\n"
        "# pipeline result, which is bigger than the attribution the\n"
        "# phase set out to measure (phase20.ORDERING_BOUND).\n"
        "#\n"
        "# k_strata: 1 -- a plain permutation IS the stratified one at a\n"
        "# single stratum, so there is no second implementation. Expected\n"
        "# fixed points: ~1 of 237 (0.42%), pre-registered, REPORTED per\n"
        "# seed and NEVER redrawn.\n"
        "#\n"
        "# NO LEDGER ROW (phase20.LEDGER_RULED): 'is the probe claimably\n"
        "# better than scrambled labels' is a category error dressed as a\n"
        "# result. Per-seed PCC with one-sample intervals against ZERO.\n",
        PLAIN_NAME,
    ) + body


def render_stratified() -> str:
    k = int(phase20.STRATIFICATION_RULED["k_strata"])
    payload = _permutation_payload("stratified", k)
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return _header(
        "PHASE 20 -- ARM S: THE STRATIFIED PERMUTATION. THE ATTRIBUTION.",
        "# The probe's config with the panel-mean labels shuffled WITHIN\n"
        "# STRATA of the confound model's fitted value, so the confound\n"
        f"# structure survives and the cleft-specific structure does not.\n"
        "#\n"
        "# **RUNS ONLY IF ARM P PASSES** (phase20.ORDERING_BOUND).\n"
        "#\n"
        f"# k_strata: {k} -- LOCKED 2026-08-31\n"
        "# (phase20.STRATIFICATION_RULED). The variable is the IN-SAMPLE\n"
        "# fitted value of a ridge over all five confound statistics\n"
        "# against the panel mean; it is NOT a config field, because a\n"
        "# pre-registration a config could edit is not one. k is a\n"
        "# locked scientific setting: never tuned across runs, movement\n"
        "# requires a dated amendment, and the loader refuses any other\n"
        "# value (_check_permutation).\n"
        "#\n"
        f"# Expected fixed points: {k} of 237 (4.2%) -- E[fixed] = 1 per\n"
        "# stratum for ANY stratum size. Pre-registered, reported per\n"
        "# seed, never discarded and never redrawn.\n"
        "#\n"
        "# NO LEDGER ROW (phase20.LEDGER_RULED): the quantity is an\n"
        "# ATTRIBUTION, not a method comparison. Reported descriptively\n"
        "# against the confound ceiling and 0.2520, with the residual\n"
        "# read against ladder.SMALLEST_RESOLVABLE_DIFFERENCE (0.1386).\n",
        STRATIFIED_NAME,
    ) + body


def render_arm_c() -> str:
    ceiling = source(CEILING_CONFIG)
    task = dict(ceiling["task"])
    # The score sheet is dropped WITH its input: Arm C reads a manifest
    # column and never opens the sheet, and an input a run does not use
    # has no business in its provenance.
    task.pop("scoresheet_artifact", None)
    task.pop("scoresheet_file", None)
    task["label"] = "mean"
    task["materially_different"] = 0.02
    if task["seeds"] != SEEDS:
        raise SystemExit(f"the ceiling's seeds are {task['seeds']}, not {SEEDS}")
    payload = {
        "schema_version": ceiling["schema_version"],
        "phase": "p20",
        "tier": "keeper",
        "seed": ceiling["seed"],
        "inputs": [
            dict(entry) for entry in ceiling["inputs"]
            if entry["name"] != "scoresheet_primary"
        ],
        "task": task,
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return _header(
        "PHASE 20 -- ARM C: THE LIKE-FOR-LIKE CONFOUND CEILING.",
        "# Phase 13's confound ceiling (p13_confound_ceiling) re-run\n"
        "# against the PANEL MEAN. Same five statistics, same closed-form\n"
        "# ridge over cleft_v1's own folds, same five seeds -- ONE key\n"
        "# differs, and it is the target. phase20.ARM_C_REGISTERED.\n"
        "#\n"
        "# **WHY IT EXISTS.** Phase 13's +0.1000 is scored against the\n"
        "# MEDIAN grade; the headline 0.2520 and Arm S are against the\n"
        "# PANEL MEAN, and the two are not the same quantity\n"
        "# (learnability: mean 0.6022 vs median 0.5708). Arm S had no\n"
        "# valid anchor in the record until this arm.\n"
        "#\n"
        "# **NOT A CORRECTION TO PHASE 13.** +0.1000 is correct for its\n"
        "# own quantity and its threshold was declared before the number\n"
        "# existed. What was wrong was a COMPARISON made later, in\n"
        "# conversation (phase20.CROSS_TARGET_ERROR_PROVENANCE). Nothing\n"
        "# in Phase 13's record is rewritten; it carries a dated pointer.\n"
        "#\n"
        "# INDEPENDENT OF THE GATE: this arm does not wait on Arm P.\n"
        "#\n"
        "# `materially_different: 0.02` is Arm C's READING THRESHOLD,\n"
        "# declared here so the cell that fires cannot be chosen after\n"
        "# the number is seen. It is Phase 13's own measured seed sd\n"
        "# (0.0228) rounded down: a gap smaller than one seed's spread\n"
        "# is not a gap this design can call material.\n"
        "#\n"
        "# DESCRIPTIVE, report-never-gate: NO LEDGER ROW\n"
        "# (phase20.LEDGER_RULED) -- a ceiling is not an arm claim.\n",
        ARM_C_NAME,
    ) + body


def render_diagnostic() -> str:
    """**Half Arm S, half Arm C, and both halves are COPIED.**

    The permutation block, the label, the seeds and the two artifacts
    come from Arm S's config -- if they were re-typed and drifted, this
    would score a permutation Arm S never trained on and nothing would
    say so. The recipe (alpha, inner_val_frac, expect_patients) comes
    from Arm C's, for the same reason: it must be the same fit.

    The embeddings input is NOT carried. This is five scalars and a
    closed-form ridge; it never opens them, and an input a run does not
    read has no business in its provenance.
    """
    arm_s = source(STRATIFIED_NAME)
    arm_c = source(ARM_C_NAME)
    s_task, c_task = arm_s["task"], arm_c["task"]

    task = {
        "kind": "p20_stratification_diagnostic",
        "manifest_artifact": s_task["manifest_artifact"],
        "staged_artifact": s_task["staged_artifact"],
        "label": s_task["label"],
        # Carried VERBATIM. A test asserts the two blocks are equal.
        "permutation": dict(s_task["permutation"]),
        "seeds": list(s_task["seeds"]),
        "inner_val_frac": c_task["inner_val_frac"],
        "alpha": c_task["alpha"],
        # Arm C's OBSERVED mean, from the record's structured home --
        # never re-typed from prose.
        "ceiling_pcc": float(phase20.ARMS_OBSERVED["arm_c"]["pcc_mean"]),
        "destroyed_fraction": 0.30,
        "survived_fraction": 0.70,
        "expect_patients": c_task["expect_patients"],
    }
    keep = {task["manifest_artifact"], task["staged_artifact"]}
    payload = {
        "schema_version": arm_s["schema_version"],
        "phase": "p20",
        "tier": "keeper",
        "seed": arm_s["seed"],
        "inputs": [
            dict(entry) for entry in arm_s["inputs"] if entry["name"] in keep
        ],
        "task": task,
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return _header(
        "PHASE 20 -- THE STRATIFICATION DIAGNOSTIC: DID ARM S PRESERVE\n"
        "# WHAT IT EXISTS TO PRESERVE?",
        "# Arm C's confound model fitted against ARM S'S OWN PERMUTED\n"
        "# LABELS, per seed. phase20.STRATIFICATION_DIAGNOSTIC.\n"
        "#\n"
        "# **WHY.** Stratifying on the fitted value into 10 quantile bins\n"
        "# preserves confound structure ONLY BETWEEN BINS. If the five\n"
        "# statistics' predictive power lives substantially WITHIN bin at\n"
        "# k = 10, Arm S destroyed the confound signal along with the\n"
        "# cleft signal -- and measures BOTH-DESTROYED rather than\n"
        "# CLEFT-DESTROYED. Those are opposite conclusions from S's one\n"
        "# number, and S cannot tell them apart.\n"
        "#\n"
        "# **A LIMITATION OF THE LOCK, not a tenth criterion.**\n"
        "# EXIT_CRITERIA keeps its nine byte-unchanged; the gap is\n"
        "# recorded as the lock's own clause requires\n"
        "# (phase20.LOCK_LIMITATION_STRATIFICATION_UNVERIFIED).\n"
        "#\n"
        "# **SAME PERMUTATION, NOT A LOOK-ALIKE.** The permutation block,\n"
        "# label, seeds and artifacts are CARRIED VERBATIM from\n"
        f"# {STRATIFIED_NAME}; the recipe from {ARM_C_NAME}.\n"
        "# The run reports its fixed-point counts, which MUST equal Arm\n"
        "# S's permutation.json exactly.\n"
        "#\n"
        "# `ceiling_pcc` is Arm C's OBSERVED mean and the denominator of\n"
        "# every reported fraction. `destroyed_fraction` / \n"
        "# `survived_fraction` are the two reading thresholds, declared\n"
        "# HERE so the cell cannot be chosen after the number is seen.\n"
        "# The middle band is deliberately WIDE: 'partial survival' is\n"
        "# the honest cell for anything ambiguous, and narrowing it would\n"
        "# push borderline outcomes into a confident reading.\n"
        "#\n"
        "# **BINDING, on every branch**: under NO branch does Arm S's\n"
        "# number alone license a claim about how much of 0.2520 is\n"
        "# cleft-specific. This decides whether S is INTERPRETABLE AT\n"
        "# ALL (phase20.DIAGNOSTIC_BINDING).\n"
        "#\n"
        "# No new artifact, no new hash, no backbone, NO GATE -- nothing\n"
        "# here generates or modifies a cohort pixel.\n",
        DIAGNOSTIC_NAME,
    ) + body


CONFIGS = {
    PLAIN_NAME: render_plain,
    STRATIFIED_NAME: render_stratified,
    ARM_C_NAME: render_arm_c,
    DIAGNOSTIC_NAME: render_diagnostic,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    print(
        "every input carried verbatim from p7_d1_vit_b16_imagenet_g1 and "
        "p13_confound_ceiling -- no new hash entered"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
