"""Write the two reckoning-input configs for Phase 22's restate.

    PYTHONPATH=src python scripts/generate_reckoning_configs.py [--check]

Two configs, neither of them Phase 22 machinery:

* ``p21_cohort_pair_separation`` -- how often two patients' panel means
  differ by less than the panel's own noise
  (``phase21.COHORT_PAIR_SEPARATION_DESIGNED``)
* ``p21_cross_arm_shrinkage``    -- sd(prediction)/sd(truth) across the
  ruled arm set (``phase21.CROSS_ARM_SHRINKAGE_REGISTERED``)

**NO NEW HASH ENTERS.** The separation config declares the manifest
alone, carried from the probe. The shrinkage config carries the same run
directories and manifest that ``p21_ensemble_probe`` already declares --
same names, same paths, same verified rollups. Nothing here computes a
hash, and the arm list is DERIVED from ``phase18.ARM_LIST_LOCKED``
filtered by ``phase21.ARM_SET_RULED``, so no glob exists anywhere in the
arm resolution.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

import yaml  # noqa: E402

CLUSTER_ROOT = "/home/user/codex/cleft-aesthetics"
PROBE_CONFIG = "p7_d1_vit_b16_imagenet_g1.yaml"
ENSEMBLE_CONFIG = "p21_ensemble_probe.yaml"

SEPARATION_NAME = "p21_cohort_pair_separation.yaml"
SHRINKAGE_NAME = "p21_cross_arm_shrinkage.yaml"

PROBE_ARM = "p7_d1_vit_b16_imagenet_g1"


def source(name: str) -> dict:
    return yaml.safe_load((REPO / "configs" / name).read_text(encoding="utf-8"))


def _header(title: str, body: str, config_name: str) -> str:
    return (
        f"# {title}\n#\n"
        "# GENERATED by scripts/generate_reckoning_configs.py. Do not\n"
        "# hand-edit: --check re-derives and diffs.\n"
        "#\n"
        "# A RECKONING INPUT for Phase 22's restate -- NOT Phase 22\n"
        "# machinery. DESCRIPTIVE, no ledger row, no lock touched.\n"
        "#\n"
        "# Every input is CARRIED VERBATIM from a shipped config. NO NEW\n"
        "# HASH ENTERS, no GPU, no new artifact, NO GATE -- nothing here\n"
        "# generates or modifies a cohort pixel.\n"
        f"#\n{body}#\n"
        f"#   bash -lc \"cd {CLUSTER_ROOT} && PYTHONPATH=src \\\n"
        f"#     python -m cleft.run --config configs/{config_name}\"\n\n"
    )


def render_separation() -> str:
    probe = source(PROBE_CONFIG)
    manifest = next(e for e in probe["inputs"] if e["name"] == "manifest_v1")
    payload = {
        "schema_version": probe["schema_version"],
        "phase": "p21", "tier": "keeper", "seed": probe["seed"],
        "inputs": [dict(manifest)],
        "task": {
            "kind": "cohort_pair_separation",
            "manifest_artifact": "manifest_v1",
            "label": "mean",
            "multiples": [1, 2, 3],
            "primary_scale": "se_diff",
            "primary_multiple": 1,
            "expect_patients": 237,
        },
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return _header(
        "COHORT-PAIR SEPARATION -- how often do two patients' panel\n"
        "# means differ by less than the panel's own noise?",
        "# phase21.COHORT_PAIR_SEPARATION_DESIGNED. Phase 22's cohort\n"
        "# ranking arm would train on patient pairs; a pair separated by\n"
        "# less than the panel's noise is ORDERED BY CHANCE, and a\n"
        "# ranking loss cannot tell a coin flip from a signal.\n"
        "#\n"
        "# THE NOISE SCALE IS DERIVED, NEVER CHOSEN: classical test\n"
        "# theory on reliability.RELIABILITY_237 (0.8158), giving\n"
        "# SE_single = sd_obs * 0.4292 and SE_diff = sd_obs * 0.6070.\n"
        "# sd_obs is COMPUTED FROM THE MANIFEST AT RUN TIME -- the\n"
        "# docstring figure 0.628 is not used, and reliability's own\n"
        "# item_total docstring carries those digits as a DIFFERENT\n"
        "# quantity (an item-total correlation).\n"
        "#\n"
        "# All six fractions are reported -- 1x, 2x, 3x of BOTH scales --\n"
        "# because a single threshold would be a choice and the profile\n"
        "# is not. `primary_scale`/`primary_multiple` declare which one\n"
        "# the READING turns on, so the cell cannot be chosen after.\n"
        "# se_diff is the proper scale: a pair's ordering turns on the\n"
        "# DIFFERENCE of two means, not on one mean.\n"
        "#\n"
        "# Both readings are committed. This bears on the COHORT arm\n"
        "# only -- the synthetic arm's ordering is exact by construction.\n",
        SEPARATION_NAME,
    ) + body


def render_shrinkage() -> str:
    ensemble = source(ENSEMBLE_CONFIG)
    task = ensemble["task"]
    payload = {
        "schema_version": ensemble["schema_version"],
        "phase": "p21", "tier": "keeper", "seed": ensemble["seed"],
        "inputs": [dict(entry) for entry in ensemble["inputs"]],
        "task": {
            "kind": "cross_arm_shrinkage",
            "manifest_artifact": "manifest_v1",
            "arms": [dict(arm) for arm in task["arms"]],
            "seeds": list(task["seeds"]),
            "probe_arm": PROBE_ARM,
            "fails_to_shrink_at": 0.90,
            "shrinks_substantially_at": 0.75,
            "varies_widely_at": 0.10,
            "expect_arms": len(task["arms"]),
            "expect_patients": 237,
        },
    }
    if len(task["arms"]) != 64:
        raise SystemExit(
            f"the ensemble config carries {len(task['arms'])} arms, not the "
            "64 phase21.ARM_SET_RULED declares"
        )
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False)
    return _header(
        "CROSS-ARM SHRINKAGE -- is shrinkage a property of the arms,\n"
        "# or of one run?",
        "# phase21.CROSS_ARM_SHRINKAGE_REGISTERED.\n"
        "# phase3.sanity_report has printed shrinkage =\n"
        "# sd(prediction)/sd(truth) on every arm since 2026-07-28, but\n"
        "# SHRINKAGE_MECHANISM's general claim rested on ONE SEED OF ONE\n"
        "# ARM on scrambled labels. This measures it instead.\n"
        "#\n"
        "# Recomputed from the cached PREDICTIONS_COLUMNS CSVs through\n"
        "# the Phase 21 reader -- NOT a second implementation. The truth\n"
        "# column is already in every CSV.\n"
        "#\n"
        "# THE DENOMINATOR IS A CONSTANT AND THE TASK VERIFIES IT: on\n"
        "# the 237 cohort every arm scores the same truth vector, so the\n"
        "# ratio is driven ENTIRELY by prediction spread. The task\n"
        "# asserts it across every arm and seed and against the\n"
        "# manifest's own mean column, and refuses to continue otherwise.\n"
        "#\n"
        "# 64 arms, not the locked 68: the four p12 arms are on 236\n"
        "# patients and carry their own denominator (ARM_SET_RULED).\n"
        "#\n"
        "# The three reading thresholds are DECLARED here with their\n"
        "# precedence, so two cells cannot both fire.\n"
        "#\n"
        "# varies_widely_at is the SAMPLE SD (ddof=1) of the per-arm\n"
        "# means, RULED 2026-09-01 at 0.10. A range statistic at 0.30\n"
        "# was built, simulated and REJECTED ON EVIDENCE: the range\n"
        "# grows with arm count, so at 64 arms it fired 94.65% of the\n"
        "# time on genuinely homogeneous arms where the SD fires\n"
        "# 0.33%. phase21.SHRINKAGE_DISPERSION_STATISTIC_RULED.\n",
        SHRINKAGE_NAME,
    ) + body


CONFIGS = {
    SEPARATION_NAME: render_separation,
    SHRINKAGE_NAME: render_shrinkage,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = 0
    for name, builder in CONFIGS.items():
        path = REPO / "configs" / name
        text = builder()
        if args.check:
            if not path.is_file():
                print(f"  DRIFT {name}: missing")
                drifted += 1
            elif path.read_text(encoding="utf-8") != text:
                print(f"  DRIFT {name}: differs from the derived config")
                drifted += 1
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {name}")
    if args.check:
        print(f"{len(CONFIGS)} configs checked, {drifted} drifted")
        return 1 if drifted else 0
    print(
        "inputs carried verbatim from p7_d1_vit_b16_imagenet_g1 and "
        "p21_ensemble_probe -- no new hash entered"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
